// AUTHORED presentation copy, governed by the existing public locale owner.
const es = {
  models: "Modelos", locations: "Dónde estamos", account: "Mi cuenta", home: "Inicio", menu: "Abrir menú", closeMenu: "Cerrar menú", navigation: "Navegación principal",
  eyebrow: "Movilidad eléctrica", homeTitle: "Tu próximo movimiento.", homeBody: "Encontrá tu modelo. Conocelo de cerca.", explore: "Ver modelos", findUs: "Encontrar atención",
  conceptual: "Imagen conceptual", heroAlt: "Bicicleta eléctrica conceptual en un estudio oscuro", collection: "La colección", catalogueTitle: "Modelos eléctricos", catalogueBody: "Elegí cómo querés moverte.",
  detail: "Conocer modelo", inquire: "Consultar este modelo", priceFrom: "Desde", included: "Impuestos incluidos", excluded: "Impuestos no incluidos", notApplicable: "Impuestos: no aplican", priceUnavailable: "Consultá el precio",
  variants: "Versiones", information: "En detalle", specifications: "Características", noMedia: "Imagen no disponible", noModels: "Estamos preparando nuevos modelos.", noModelsBody: "Encontrá un punto de atención para conocer las próximas opciones.",
  catalogueError: "No pudimos cargar los modelos.", catalogueErrorBody: "Probá de nuevo en un momento.", retry: "Volver a intentar", backModels: "Todos los modelos", loadModels: "Cargando modelos…", contact: "Contacto", 
  closer: "Más cerca de tu próxima salida.", closerBody: "Encontrá un punto de atención y resolvé tus dudas.", visit: "Conocenos de cerca.", visitBody: "Buscá atención, consultá por tu modelo o coordiná una visita.",
  noLocations: "Todavía no hay puntos de atención publicados.", noLocationsBody: "Podés dejarnos una consulta desde el modelo que te interesa.", locationError: "No pudimos cargar los puntos de atención.", call: "Llamar", email: "Enviar email", book: "Coordiná tu visita", bookBody: "Elegí un turno para continuar con tu consulta.", startInquiry: "Primero, elegí tu modelo.", startInquiryBody: "Dejanos tu consulta para coordinar una visita.", slotsError: "No pudimos cargar los turnos. Podés volver a intentar sin perder tu consulta.",
  talk: "Conversemos.", inquiryBody: "Dejanos tus datos y te contactamos sobre este modelo.", name: "Nombre", emailLabel: "Email", consent: "Acepto ser contactado sobre este modelo.", send: "Enviar consulta", sending: "Enviando…", received: "Recibimos tu consulta.", receivedBody: "Ya podés solicitar un turno para conocerlo de cerca.", next: "Reservar turno", invalid: "Revisá los datos e intentá nuevamente.", failed: "No pudimos enviar tu consulta. Conservamos tus datos.", uncertain: "Todavía no podemos confirmar el envío.", uncertainBody: "Volvé a intentar con estos mismos datos para comprobar el resultado sin duplicar tu consulta.", check: "Comprobar envío", reference: "Referencia de consulta", unavailable: "La consulta no está disponible en este momento.",
  bicycle: "Bicicleta", motorcycle: "Motocicleta", scooter: "Scooter", utility: "Utilitario", car: "Automóvil", other: "Movilidad", modelsOne: "modelo", modelsMany: "modelos", description: "Descripción", warranty: "Garantía", range: "Autonomía", weight: "Peso", motor: "Motor", battery: "Batería", speed: "Velocidad máxima", frame: "Cuadro", wheels: "Ruedas", brakes: "Frenos", modelLabel: "Modelo", viewLocations: "Ver puntos de atención"
} as const;
const en: Record<keyof typeof es, string> = {
  models:"Models", locations:"Locations", account:"My account",home:"Home",menu:"Open menu",closeMenu:"Close menu",navigation:"Main navigation",
  eyebrow:"Electric mobility",homeTitle:"Your next move.",homeBody:"Find your model. Get to know it.",explore:"Explore models",findUs:"Find support",conceptual:"Concept image",heroAlt:"Concept electric bicycle in a dark studio",collection:"The collection",catalogueTitle:"Electric models",catalogueBody:"Choose how you move.",
  detail:"Explore model",inquire:"Ask about this model",priceFrom:"From",included:"Taxes included",excluded:"Taxes not included",notApplicable:"Taxes: not applicable",priceUnavailable:"Ask for pricing",variants:"Versions",information:"In detail",specifications:"Features",noMedia:"Image unavailable",noModels:"New models are on their way.",noModelsBody:"Find a location to learn about upcoming options.",catalogueError:"We couldn’t load the models.",catalogueErrorBody:"Please try again in a moment.",retry:"Try again",backModels:"All models",loadModels:"Loading models…",contact:"Contact",
  closer:"Closer to your next ride.",closerBody:"Find a location and get your questions answered.",visit:"See it up close.",visitBody:"Find support, ask about your model or arrange a visit.",noLocations:"No locations have been published yet.",noLocationsBody:"You can send an inquiry from the model you’re interested in.",locationError:"We couldn’t load the locations.",call:"Call",email:"Send email",book:"Plan your visit",bookBody:"Choose an appointment to continue your inquiry.",startInquiry:"First, choose your model.",startInquiryBody:"Send an inquiry to arrange a visit.",slotsError:"We couldn’t load the appointments. You can retry without losing your inquiry.",
  talk:"Let’s talk.",inquiryBody:"Leave your details and we’ll contact you about this model.",name:"Name",emailLabel:"Email",consent:"I agree to be contacted about this model.",send:"Send inquiry",sending:"Sending…",received:"We received your inquiry.",receivedBody:"You can now request an appointment to see it up close.",next:"Book an appointment",invalid:"Check your details and try again.",failed:"We couldn’t send your inquiry. We kept your details.",uncertain:"We can’t confirm the submission yet.",uncertainBody:"Retry with these same details to check the result without duplicating your inquiry.",check:"Check submission",reference:"Inquiry reference",unavailable:"Inquiries are unavailable right now.",
  bicycle:"Bicycle",motorcycle:"Motorcycle",scooter:"Scooter",utility:"Utility vehicle",car:"Car",other:"Mobility",modelsOne:"model",modelsMany:"models",description:"Description",warranty:"Warranty",range:"Range",weight:"Weight",motor:"Motor",battery:"Battery",speed:"Maximum speed",frame:"Frame",wheels:"Wheels",brakes:"Brakes",modelLabel:"Model",viewLocations:"View locations"
};
export type PublicTextKey = keyof typeof es;
export function publicText(locale: string, key: PublicTextKey): string { return new Intl.Locale(locale).language === "en" ? en[key] : es[key]; }
