"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {campaignBatch,campaignCommand,campaignHumanState,campaignPage,campaignStatus,campaignTemplates,preparedCampaign,type CampaignCommand,type CampaignPage,type CampaignSelection,type CampaignStatus,type CampaignStep,type CampaignTemplates,type PreparedCampaign} from "@/platform/campaigns/contract";
import styles from "./campaign-workspace.module.css";
const endpoint="/api/enterprise/franchise/campaigns";
const title=(value:string)=>value.replaceAll("_"," ").replace(/^./,s=>s.toUpperCase());
const date=(value:string)=>new Intl.DateTimeFormat("es-AR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
class ReadError extends Error{constructor(readonly status:number){super("No se pudo consultar el resultado.")}}
async function read(kind:string,params:Record<string,string>={}){const r=await fetch(endpoint+"?"+new URLSearchParams({kind,...params}),{cache:"no-store",signal:AbortSignal.timeout(8000)});if(!r.ok)throw new ReadError(r.status);return r.json() as Promise<unknown>}
export function CampaignWorkspace({scope,subject,permissions}:{scope:string;subject:string;permissions:{read:boolean;prepare:boolean;review:boolean;stop:boolean}}){
 const [list,setList]=useState<CampaignPage|null>(null),[audience,setAudience]=useState<CampaignPage|null>(null),[templates,setTemplates]=useState<CampaignTemplates|null>(null);
 const [active,setActive]=useState<string|null>(null),[detail,setDetail]=useState<CampaignStatus|null>(null),[creating,setCreating]=useState(false);
 const [query,setQuery]=useState(""),[selected,setSelected]=useState<string[]>([]),[steps,setSteps]=useState<CampaignStep[]>([]),[draft,setDraft]=useState<CampaignSelection|null>(null),[prepared,setPrepared]=useState<PreparedCampaign|null>(null);
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[reason,setReason]=useState(""),[uncertain,setUncertain]=useState<CampaignCommand|null>(null),[retryConfirmed,setRetryConfirmed]=useState(false);
 const flight=useRef(false),generation=useRef(0),heading=useRef<HTMLHeadingElement>(null);const journalKey="campaign-operation:"+scope;
 async function refresh(after?:string){setLoading(true);setError("");try{setList(campaignPage.parse(await read("campaigns",after?{after}:{})))}catch{setError("No pudimos cargar las campañas. Tu trabajo sigue guardado.")}finally{setLoading(false)}}
 async function open(id:string){const n=++generation.current;setActive(id);setCreating(false);setDetail(null);setLoading(true);setError("");setReason("");try{const d=campaignStatus.parse(await read("status",{id}));if(n===generation.current){setDetail(d);heading.current?.focus()}}catch{if(n===generation.current)setError("No pudimos abrir esta campaña. Volvé a consultar su estado.")}finally{if(n===generation.current)setLoading(false)}}
 useEffect(()=>{void refresh();try{const raw=sessionStorage.getItem(journalKey);if(raw){const c=campaignCommand.parse(JSON.parse(raw));if(c.action!=="prepare"){setUncertain(c);setNotice("Hay una operación pendiente de confirmar.")}}}catch{setError("No pudimos recuperar la operación de esta sesión.")}return()=>{generation.current++}},[journalKey]);
 async function newCampaign(retry=false){setError("");setCreating(true);setActive(null);if(!retry){setPrepared(null);setDraft(null);setSelected([]);setSteps([])}setLoading(true);try{const [a,t]=await Promise.all([read("audience"),read("templates")]);const parsed=campaignTemplates.parse(t);setAudience(campaignPage.parse(a));setTemplates(parsed);heading.current?.focus()}catch{setError("No pudimos cargar los contactos o las plantillas. Reintentá sin perder la selección.")}finally{setLoading(false)}}
 async function moreAudience(){if(!audience?.next_cursor)return;setLoading(true);try{const a=campaignPage.parse(await read("audience",{after:audience.next_cursor}));setAudience(old=>({...a,audience:[...(old?.audience??[]),...(a.audience??[])].filter((v,i,all)=>all.findIndex(x=>x.lead_id===v.lead_id)===i)}))}catch{setError("No pudimos cargar más contactos.")}finally{setLoading(false)}}
 async function mutate(command:CampaignCommand){
  if(flight.current)return;flight.current=true;setBusy(true);setError("");setNotice("");
  const writes=command.action!=="prepare";
  try{
   const safe=campaignCommand.parse(command);
   // Durable business state stays on the server. The session journal stores the exact
   // requested selection/action for replay, never recipient numbers or provider profiles.
   if(writes)sessionStorage.setItem(journalKey,JSON.stringify(safe));
   const r=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(safe),signal:AbortSignal.timeout(12000)});
   if(!r.ok)throw Error("unconfirmed");const value:unknown=await r.json();
   if(command.action==="prepare"){setPrepared(preparedCampaign.parse(value));setNotice("Revisá los contactos y los horarios antes de crear la campaña.")}
   else{
    if(command.action!=="stop")campaignBatch.parse(value);else if(!value||typeof value!=="object"||!("stopped"in value)||value.stopped!==true)throw Error("invalid stop");
    sessionStorage.removeItem(journalKey);setUncertain(null);setRetryConfirmed(false);setPrepared(null);setNotice(command.action==="create"?"Campaña creada. Falta la revisión de otra persona.":command.action==="stop"?"Campaña detenida.":"Decisión registrada. Consultá el estado actualizado.");
    await open(command.action==="create"?command.selection.campaign_id:command.campaign_id);await refresh();
   }
  }catch{
   if(writes){setUncertain(command);setRetryConfirmed(false);setError("El resultado todavía no está confirmado. Consultalo antes de repetir la operación.")}
   else setError("La selección cambió o ya no está disponible. Revisá contactos, plantilla y horarios.");
  }finally{flight.current=false;setBusy(false)}
 }
 async function recover(){if(!uncertain||uncertain.action==="prepare")return;setLoading(true);setError("");const id=uncertain.action==="create"?uncertain.selection.campaign_id:uncertain.campaign_id;try{const d=campaignStatus.parse(await read("status",{id}));setActive(id);setCreating(false);setDetail(d);setRetryConfirmed(true);setNotice("Estado consultado. Revisá el resultado; si falta completar la operación, podés reenviar la misma solicitud.");if(uncertain.action==="create"){sessionStorage.removeItem(journalKey);setUncertain(null);setRetryConfirmed(false)}}catch(e){if(e instanceof ReadError&&e.status===404&&uncertain.action==="create"){setRetryConfirmed(true);setNotice("La campaña aún no está registrada. Podés reenviar la misma solicitud.")}else setError("Todavía no pudimos confirmar el resultado. Conservamos la operación.")}finally{setLoading(false)}}
 function addStep(){if(!templates||steps.length>=templates.max_steps)return;const t=templates.templates[0];if(!t)return;const start=new Date(Date.now()+(steps.length+1)*2*3600000),end=new Date(start.getTime()+3600000);setSteps(v=>[...v,{template_name:t.name,language_code:t.language_code,body_parameters:Array.from({length:t.body_parameter_count},()=>""),not_before:start.toISOString(),expires_at:end.toISOString()}]);setPrepared(null)}
 function updateStep(index:number,change:Partial<CampaignStep>){setSteps(values=>values.map((s,i)=>i===index?{...s,...change}:s));setPrepared(null)}
 function prepare(e:FormEvent){e.preventDefault();const value={campaign_id:draft?.campaign_id??crypto.randomUUID(),lead_ids:selected,steps};setDraft(value);void mutate({action:"prepare",selection:value})}
 const visible=(list?.campaigns??[]).filter(c=>title(c.template_name).toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 const selectionLabels=new Map((audience?.audience??[]).map(c=>[c.lead_id,c.name]));
 const locked=busy||uncertain!==null;
 const reviewable=detail?.items.some(item=>item.schedule?.approval_state==="pending")??false;
 return <div className={styles.workspace} data-campaign-workspace>
  <header className={styles.header}><div><p className={styles.eyebrow}>Comercial</p><h1>Campañas</h1></div>{permissions.prepare&&!creating?<button className="button" disabled={locked} onClick={()=>void newCampaign()}>Nueva campaña</button>:null}</header>
  {uncertain?<section className={styles.recovery} aria-label="Operación pendiente"><p>{error||"Hay una operación pendiente de confirmar."}</p><button className="button" disabled={busy||loading} onClick={()=>void recover()}>Consultar resultado</button>{retryConfirmed?<button disabled={busy} onClick={()=>void mutate(uncertain)}>Reenviar la misma solicitud</button>:null}</section>:error?<div className={styles.notice} role="alert"><p>{error}</p><button disabled={loading} onClick={()=>void(active?open(active):creating?newCampaign(true):refresh())}>Reintentar</button></div>:null}
  {notice?<p role="status" className={styles.notice}>{notice}</p>:null}
  <div className={styles.columns} data-detail={Boolean(active||creating)}>
   <section className={styles.list} aria-label="Campañas disponibles"><label className={styles.search}>Buscar en esta página<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nombre de la plantilla"/></label>
    {loading&&!list?<p role="status">Cargando campañas…</p>:null}
    {!loading&&list&&visible.length===0?<div className={styles.empty}><h2>{query?"Sin coincidencias":"Todavía no hay campañas"}</h2><p>{query?"Probá otra búsqueda.":"Prepará un seguimiento para tus contactos."}</p></div>:null}
    {visible.map(c=><button key={c.campaign_id} className={styles.row} aria-current={active===c.campaign_id?"true":undefined} disabled={busy} onClick={()=>void open(c.campaign_id)}><span className={styles.rowIcon} aria-hidden="true">↗</span><span><strong>{title(c.template_name)}</strong><small>{c.members} {c.members===1?"contacto":"contactos"} · {c.steps} {c.steps===1?"mensaje":"mensajes"}</small><small>{date(c.created_at)}</small></span><span className={styles.state}>{c.stopped?"Detenida":"Ver estado"}</span></button>)}
    <nav className={styles.paging} aria-label="Páginas de campañas"><button disabled={loading} onClick={()=>void refresh()}>Inicio</button>{list?.next_cursor?<button disabled={loading} onClick={()=>void refresh(list.next_cursor)}>Siguientes</button>:null}</nav>
   </section>
   <section className={styles.detail} aria-label="Detalle de campaña">
    {active||creating?<button className={styles.back} onClick={()=>{generation.current++;setActive(null);setCreating(false)}}>← Campañas</button>:null}
    {!active&&!creating?<div className={styles.empty}><h2>Todo el seguimiento, en un lugar</h2><p>Elegí una campaña para revisar sus mensajes y resultados.</p></div>:null}
    {active&&loading&&!detail?<p role="status">Cargando el detalle…</p>:null}
    {creating?<><h2 tabIndex={-1} ref={heading}>Nueva campaña</h2><form onSubmit={prepare}>
     <fieldset disabled={locked||loading}><legend>Contactos</legend><div className={styles.contacts}>{(audience?.audience??[]).map(c=><label key={c.lead_id}><input type="checkbox" checked={selected.includes(c.lead_id)} onChange={e=>{setSelected(v=>e.target.checked?[...v,c.lead_id]:v.filter(id=>id!==c.lead_id));setPrepared(null)}} disabled={!selected.includes(c.lead_id)&&selected.length>=(templates?.max_members??20)}/><span>{c.name}<small>{c.contact_hint}</small></span></label>)}</div>{audience&&!audience.audience?.length?<p>No hay contactos disponibles con consentimiento vigente.</p>:null}{audience?.next_cursor?<button type="button" onClick={()=>void moreAudience()}>Cargar más contactos</button>:null}</fieldset>
     <fieldset disabled={locked||loading}><legend>Mensajes</legend>{steps.map((s,i)=><div className={styles.step} key={i}><div className={styles.stepHeading}><h3>Mensaje {i+1}</h3><button type="button" onClick={()=>{setSteps(v=>v.filter((_,n)=>n!==i));setPrepared(null)}}>Quitar</button></div><label>Plantilla<select value={s.template_name+"|"+s.language_code} onChange={e=>{const t=templates?.templates.find(t=>t.name+"|"+t.language_code===e.target.value);if(t)updateStep(i,{template_name:t.name,language_code:t.language_code,body_parameters:Array.from({length:t.body_parameter_count},()=>"")})}}>{templates?.templates.map(t=><option key={t.name+"|"+t.language_code} value={t.name+"|"+t.language_code}>{title(t.name)} · {t.language_code}</option>)}</select></label>{s.body_parameters.map((p,j)=><label key={j}>Dato {j+1} del mensaje<input value={p} maxLength={1024} required onChange={e=>updateStep(i,{body_parameters:s.body_parameters.map((v,n)=>n===j?e.target.value:v)})}/></label>)}<div className={styles.dates}><label>Programar para<input type="datetime-local" required value={localDate(s.not_before)} onChange={e=>{if(e.target.value)updateStep(i,{not_before:new Date(e.target.value).toISOString()})}}/></label><label>Válido hasta<input type="datetime-local" required value={localDate(s.expires_at)} onChange={e=>{if(e.target.value)updateStep(i,{expires_at:new Date(e.target.value).toISOString()})}}/></label></div></div>)}<button type="button" disabled={!templates?.templates.length||steps.length>=(templates?.max_steps??3)} onClick={addStep}>+ Agregar mensaje</button></fieldset>
     {!prepared?<button className="button" disabled={locked||loading||selected.length===0||steps.length===0}>{busy?"Preparando…":"Revisar campaña"}</button>:null}
    </form>{prepared&&draft?<section className={styles.confirm}><h3>Confirmá la campaña</h3><p>{prepared.snapshot.members.length} contactos · {prepared.snapshot.request.steps.length} mensajes</p><details><summary>Ver contactos y horarios</summary><ul>{prepared.snapshot.members.map(m=><li key={m.lead_id}>{selectionLabels.get(m.lead_id)??"Contacto seleccionado"}</li>)}</ul>{prepared.snapshot.request.steps.map((s,i)=><p key={i}>{title(s.template_name)} · {date(s.not_before)}</p>)}</details><button className="button" disabled={locked} onClick={()=>void mutate({action:"create",selection:draft,campaign_sha256:prepared.campaign_sha256})}>Crear para revisión</button></section>:null}</>:null}
    {detail&&!creating?<><h2 tabIndex={-1} ref={heading}>{title(detail.snapshot.request.steps[0]?.template_name??"Campaña")}</h2><p className={styles.subtle}>{detail.snapshot.members.length} {detail.snapshot.members.length===1?"contacto":"contactos"} · {detail.snapshot.request.steps.length} {detail.snapshot.request.steps.length===1?"mensaje":"mensajes"}{detail.stopped?" · Detenida":""}</p><div className={styles.messageList}>{detail.items.map(item=><article key={item.delivery_key}><div><strong>Mensaje {item.step} · •••• {detail.snapshot.members.find(m=>m.lead_id===item.lead_id)?.recipient.slice(-4)}</strong><small>{date(detail.snapshot.request.steps[item.step-1]?.not_before??new Date().toISOString())}</small></div><span className={styles.state}>{campaignHumanState(item)}</span></article>)}</div>
     <details><summary>Contenido y horarios</summary>{detail.snapshot.request.steps.map((s,i)=><article key={i}><h3>Mensaje {i+1} · {title(s.template_name)}</h3><p>{s.body_parameters.join(" · ")}</p><p>{date(s.not_before)} — {date(s.expires_at)}</p></article>)}</details>
     {detail.conversions.length?<section><h3>Pedidos relacionados</h3><p>{detail.conversions.length} pedidos registrados después de un mensaje aceptado.</p><a href="/franchise?task=orders">Ver pedidos</a></section>:null}
     {!detail.stopped&&(permissions.review&&reviewable&&detail.snapshot.requester!==subject||permissions.stop)?<section className={styles.actions}><label>Motivo<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={2048} rows={2}/></label><div>{permissions.review&&reviewable&&detail.snapshot.requester!==subject?<><button className="button" disabled={locked||!reason.trim()} onClick={()=>void mutate({action:"decision",campaign_id:detail.snapshot.request.campaign_id,campaign_sha256:detail.campaign_sha256,approve:true,reason})}>Aprobar</button><button disabled={locked||!reason.trim()} onClick={()=>void mutate({action:"decision",campaign_id:detail.snapshot.request.campaign_id,campaign_sha256:detail.campaign_sha256,approve:false,reason})}>Rechazar</button></>:null}{permissions.stop?<button disabled={locked||!reason.trim()} onClick={()=>void mutate({action:"stop",campaign_id:detail.snapshot.request.campaign_id,campaign_sha256:detail.campaign_sha256,reason})}>Detener campaña</button>:null}</div></section>:null}
     {permissions.prepare&&detail.snapshot.requester===subject&&detail.items.some(i=>i.preparation==="NOT_PREPARED")?<button disabled={locked} onClick={()=>void mutate({action:"resume",campaign_id:detail.snapshot.request.campaign_id,campaign_sha256:detail.campaign_sha256})}>Completar preparación</button>:null}
     <button disabled={busy||loading} onClick={()=>void open(detail.snapshot.request.campaign_id)}>Actualizar estado</button>
    </>:null}
   </section>
  </div>
 </div>;
}
function localDate(value:string){const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
