#requires -Version 7.0
param([string]$SshKeygen='ssh-keygen')
$ErrorActionPreference='Stop'
function Fail([string]$Message){throw "SIGNED_RELEASE_PACK: $Message"}
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
$expected=[ordered]@{'openssh-ed25519.pub'='1b53846ff8047b6e038c315c4351c35547f5e25756c340bdabe863b9882617e9';'openssh-ed25519.sig'='7e2222d980c5fdcea433cc2b9a9d00dcc28ed5b4a8b9d1fde7822802f6872e9c';'openssh-namespace'='df08227309c92f2f3f030b423009e697445371283d89352a26d064d39fb73c36';'openssh-signed-data'='3d69dd3e7115cb2f5e44836852a8a8dcf0c3642a15faee1b34bbf1bf9f9980f6'}
$ssh=(Get-Command $SshKeygen -ErrorAction Stop).Source;$auth=Get-AuthenticodeSignature -LiteralPath $ssh;if($auth.Status-ne'Valid'-or$auth.SignerCertificate.Subject-notmatch'O=Microsoft Corporation'){Fail 'ssh-keygen is not Microsoft Authenticode-valid'}
$work=Join-Path $env:TEMP ('elite-sshsig-public-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path $work|Out-Null
try{foreach($e in $expected.GetEnumerator()){$bytes=[Convert]::FromBase64String((Get-Content -LiteralPath (Join-Path $PSScriptRoot ('fixtures/'+$e.Key+'.b64')) -Raw).Trim());$path=Join-Path $work $e.Key;[IO.File]::WriteAllBytes($path,$bytes);if((Sha $path)-cne$e.Value){Fail "fixture hash mismatch: $($e.Key)"}};$pub=(Get-Content -LiteralPath (Join-Path $work 'openssh-ed25519.pub') -Raw).Trim();$allowed=Join-Path $work 'allowed_signers';[IO.File]::WriteAllText($allowed,"openssh-test $pub`n",[Text.UTF8Encoding]::new($false));function TestSignature([byte[]]$Bytes){$psi=[Diagnostics.ProcessStartInfo]::new();$psi.FileName=$ssh;foreach($a in @('-Y','verify','-f',$allowed,'-I','openssh-test','-n',(Get-Content -LiteralPath (Join-Path $work 'openssh-namespace') -Raw).Trim(),'-s',(Join-Path $work 'openssh-ed25519.sig'))){[void]$psi.ArgumentList.Add($a)};$psi.UseShellExecute=$false;$psi.RedirectStandardInput=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$p=[Diagnostics.Process]::Start($psi);$p.StandardInput.BaseStream.Write($Bytes,0,$Bytes.Length);$p.StandardInput.Close();$p.WaitForExit();$p.ExitCode};$bytes=[IO.File]::ReadAllBytes((Join-Path $work 'openssh-signed-data'));if((TestSignature $bytes)-ne0){Fail 'official positive signature rejected'};$bad=[byte[]]$bytes.Clone();$bad[0]=[byte]($bad[0]-bxor1);if((TestSignature $bad)-eq0){Fail 'tampered payload accepted'};foreach($script in @('build_release.ps1','verify_release.ps1','verify_pack.ps1')){$errors=$null;[void][Management.Automation.Language.Parser]::ParseFile((Join-Path $PSScriptRoot $script),[ref]$null,[ref]$errors);if($errors.Count){Fail "$script parse failed"}};Write-Output "PORTABLE_SIGNED_RELEASE_PACK_PASS openssh_vector=1 tamper_rejected=1 authenticode=Valid"}finally{if(Test-Path -LiteralPath $work){$resolved=[IO.Path]::GetFullPath($work);$temp=[IO.Path]::GetFullPath([IO.Path]::GetTempPath());if($resolved.StartsWith($temp+'elite-sshsig-public-',[StringComparison]::OrdinalIgnoreCase)){Remove-Item -LiteralPath $resolved -Recurse -Force}}}
