import{beforeEach,it,expect,vi}from"vitest";
import{isValidElement,type ReactElement}from"react";
const m=vi.hoisted(()=>({session:vi.fn(),get:vi.fn(),post:vi.fn(),lead:vi.fn(),appointment:vi.fn()}));
vi.mock("@/platform/auth/session",()=>({readSession:m.session,allowed:(s:{permissions:string[]},p:string)=>s.permissions.includes(p)||s.permissions.includes("*")}));
vi.mock("@/platform/auth/oidc-client",()=>({applicationBaseUrl:()=>new URL("https://portal.example.test")}));
vi.mock("@/platform/backend/protected-client",()=>({protectedGet:m.get,protectedPost:m.post}));
vi.mock("@/platform/backend/public-client",()=>({captureLead:m.lead,requestAppointment:m.appointment,BackendProblem:class extends Error{status=502;code="FIXTURE"}}));
vi.mock("@/platform/experience/options",()=>({organizationLabel:async()=>"Store",validateGuidedSelection:async()=>true}));
vi.mock("@/platform/i18n/load-private-i18n",()=>({loadPrivateI18n:async()=>({locale:{language:"es",locale:"es-AR",timeZone:"UTC"},t:(x:string)=>x,controlled:(x:string)=>x})}));
vi.mock("@/platform/config/load",()=>({loadBusinessConfig:async()=>({features:{whatsapp_status_history:false}})}));
vi.mock("next/navigation",()=>({redirect:(v:string)=>{throw new Error(v)},usePathname:()=>"/franchise",useRouter:()=>({refresh(){}})}));
import FranchisePage from"../app/franchise/page";
import{POST as lead}from"../app/api/enterprise/leads/route";
import{POST as appointment}from"../app/api/enterprise/appointments/route";
import{POST as wa}from"../app/api/enterprise/franchise/whatsapp/replies/route";
import{POST as command}from"../app/api/enterprise/franchise/commands/route";
const session=(permissions=['*'])=>({tenantId:'tenant',subject:'user',organizations:['store'],permissions,accessToken:'fixture-token'});
function request(path:string,body:unknown,prefix=''){return new Request('https://portal.example.test'+path,{method:'POST',headers:{origin:'https://portal.example.test','content-type':'application/json','idempotency-key':'request-key-fixture'},body:prefix+JSON.stringify(body)})}
const nodes=(v:unknown):ReactElement<any>[]=>Array.isArray(v)?v.flatMap(nodes):isValidElement(v)?[v,...nodes((v.props as any).children)]:[];
beforeEach(()=>{vi.clearAllMocks();m.session.mockResolvedValue(session());m.get.mockImplementation(async(_s,path)=>path==='/v1/franchise/leads'?{items:Array.from({length:50},(_,i)=>({id:'lead'+i,organization_id:'store',state:'new',source_code:'website',version:1})),next_cursor:'cursor50'}:path==='/v1/commerce/orders'?{orders:[],truncated:false}:{items:[],resources:[],appointments:[]});m.post.mockResolvedValue({id:'quote',organization_id:'store',state:'accepted',version:2,order_id:'order'});m.lead.mockResolvedValue({value:{id:'lead'},status:201});m.appointment.mockResolvedValue({value:{id:'appointment'},status:201})});
it.each(['quote:write','lead:assign','lead:update'])('CUIP007 policy: %s alone grants no contact discovery',async p=>{const s=session([p]);m.session.mockResolvedValue(s);await FranchisePage({searchParams:Promise.resolve({})});expect(m.get).not.toHaveBeenCalled();expect(s.permissions).toEqual([p])});
it('CUIP007 policy: read plus quote permission exposes existing contact owner without extra grants',async()=>{m.session.mockResolvedValue(session(['lead:read','quote:write']));const tree=await FranchisePage({searchParams:Promise.resolve({})});const panel=nodes(tree).find(n=>typeof n.type==='function'&&n.type.name==='FranchiseCommandPanel');expect(panel?.props.leads).toHaveLength(50);expect(panel?.props.permissions).toEqual(['lead:read','quote:write']);});
it('CUIP003 forwards existing lead cursor and exposes next page',async()=>{const tree=await FranchisePage({searchParams:Promise.resolve({task:'daily',leads_after:'cursor50'} as any)});expect(m.get).toHaveBeenCalledWith(expect.anything(),'/v1/franchise/leads',expect.objectContaining({after:'cursor50'}));expect(nodes(tree).some(n=>typeof n.props.href==='string'&&n.props.href.includes('leads_after=cursor50'))).toBe(true)});
it('CUIP004 agenda GET preserves task identity',async()=>{const tree=await FranchisePage({searchParams:Promise.resolve({task:'agenda'})});const form=nodes(tree).find(n=>n.type==='form'&&n.props.action==='/franchise');expect(nodes(form).some(n=>n.type==='input'&&n.props.name==='task'&&n.props.value==='agenda')).toBe(true)});
it.each([{id:'other'},{organization_id:'foreign'},{version:88},{order_id:''}])('CUIP001 rejects mismatched acceptance receipt %j',async delta=>{m.post.mockResolvedValue({id:'quote',organization_id:'store',state:'accepted',version:2,order_id:'order',...delta});expect((await command(request('/api/enterprise/franchise/commands',{action:'accept-quote',organizationId:'store',quoteId:'quote',version:1}) as any)).status).toBe(502)});
it('CUIP001 accepts exact owner receipt once',async()=>{const r=await command(request('/api/enterprise/franchise/commands',{action:'accept-quote',organizationId:'store',quoteId:'quote',version:1}) as any);expect(r.status).toBe(200);expect(m.post).toHaveBeenCalledTimes(1)});
const rows=[['lead',lead,{name:'Persona',email:'person@example.test',consentGranted:true}],['appointment',appointment,{leadId:'lead',kind:'consultation',startsAt:'2026-10-01T12:00:00Z'}],['wa',wa,{action:'send',request_id:'wa-reply:'+'a'.repeat(64),payload_sha256:'a'.repeat(64)}]] as const;
it.each(rows)('CUIP002 %s bounds consumed bytes before effect',async(_name,fn,body)=>{const r=await fn(request('/api/enterprise/fixture',body,' '.repeat(5000)) as any);expect(r.status).toBe(413);expect(m.post).not.toHaveBeenCalled();expect(m.lead).not.toHaveBeenCalled();expect(m.appointment).not.toHaveBeenCalled()});
it.each(rows)('CUIP002 %s rejects malformed JSON as client error before effect',async(_name,fn)=>{const r=await fn(new Request('https://portal.example.test/api/enterprise/fixture',{method:'POST',headers:{origin:'https://portal.example.test','content-type':'application/json','idempotency-key':'request-key-fixture'},body:'{'}) as any);expect(r.status).toBe(400);expect(m.post).not.toHaveBeenCalled();expect(m.lead).not.toHaveBeenCalled();expect(m.appointment).not.toHaveBeenCalled()});

it('CUIP002 wa enforces byte budget with multibyte reason',async()=>{const r=await wa(request('/api/enterprise/franchise/whatsapp/replies',{action:'decision',request_id:'wa-reply:'+'a'.repeat(64),payload_sha256:'a'.repeat(64),approved:false,reason:'é'.repeat(2048)}) as any);expect(r.status).toBe(413);expect(m.post).not.toHaveBeenCalled()});

it.each(rows)('CUIP002 %s preserves same-origin rejection before effect',async(_name,fn,body)=>{const r=request('/api/enterprise/fixture',body);r.headers.set('origin','https://foreign.example.test');expect((await fn(r as any)).status).toBe(403);expect(m.post).not.toHaveBeenCalled();expect(m.lead).not.toHaveBeenCalled();expect(m.appointment).not.toHaveBeenCalled()});
it('CUIP002 lead keeps consent and stable idempotency contract',async()=>{const body={name:'Persona',email:'person@example.test',consentGranted:true};expect((await lead(request('/api/enterprise/leads',body))).status).toBe(201);expect(m.lead.mock.calls[0]?.[1]).toBe('request-key-fixture');m.lead.mockClear();expect((await lead(request('/api/enterprise/leads',{...body,consentGranted:false}))).status).toBe(400);expect(m.lead).not.toHaveBeenCalled()});
it('CUIP001 command keeps organization and action permission denial before effect',async()=>{const body={action:'accept-quote',organizationId:'foreign',quoteId:'quote',version:1};expect((await command(request('/api/enterprise/franchise/commands',body) as any)).status).toBe(403);m.session.mockResolvedValue(session(['lead:read']));expect((await command(request('/api/enterprise/franchise/commands',{...body,organizationId:'store'}) as any)).status).toBe(403);expect(m.post).not.toHaveBeenCalled()});
