import {z} from "zod";
export const MAX_FRAME_BYTES=4194312;
export const captureText=z.string().min(1).refine(value=>new TextEncoder().encode(value).length<=1024&&!/[\u0000-\u001f\u007f]/u.test(value));
export const decodeSchema=z.object({schema:z.literal("elite-qr-image-decode/v1"),status:z.enum(["DECODED","MULTIPLE","NOT_FOUND","REJECTED","BUSY","TIMEOUT"]),reason:z.string().max(200).nullable().optional(),candidates:z.array(z.object({text:captureText,symbology:z.enum(["QR_CODE","CODE_128","EAN_13"]),points:z.array(z.tuple([z.number().int().min(0).max(4096),z.number().int().min(0).max(4096)])).length(4)}).strict()).max(8),authorized:z.literal(false),business_effect:z.literal(false)}).strict().refine(value=>value.status==="DECODED"?value.candidates.length===1:value.status==="MULTIPLE"?value.candidates.length>1:value.candidates.length===0);
export const resolveCommand=z.object({text:captureText,encoding:z.enum(["QR_REFERENCE","SERIAL"]),operation:z.literal("lookup")}).strict();
const record=z.object({kind:z.enum(["stock_unit","factory_unit","order"]),id:z.string().uuid(),label:z.string().min(1).max(500),serial:z.string().max(128),organization_id:z.string().min(1).max(200),state:z.string().max(100),version:z.string().regex(/^(?:|[0-9]+)$/u),variant_id:z.string().max(100)}).strict();
export const resolutionSchema=z.object({schema:z.literal("capture-resolution/v1"),status:z.enum(["RESOLVED","MULTIPLE","REFINE_SELECTION"]),records:z.array(record).max(8),authorized:z.boolean(),business_effect:z.literal(false),operation:z.literal("lookup")}).strict().refine(value=>value.status==="REFINE_SELECTION"?!value.authorized&&value.records.length===0:value.authorized&&(value.status==="RESOLVED"?value.records.length===1:value.records.length>1));
export type CaptureRecord=z.infer<typeof record>;export type DecodedCapture=z.infer<typeof decodeSchema>;export type CaptureResolution=z.infer<typeof resolutionSchema>;
export function validFrame(bytes:Uint8Array){if(bytes.length<8||bytes.length>MAX_FRAME_BYTES||bytes[0]!==69||bytes[1]!==71||bytes[2]!==89||bytes[3]!==49)return false;const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),w=view.getUint16(4),h=view.getUint16(6);return w>20&&h>20&&w<=4096&&h<=4096&&w*h<=4194304&&bytes.length===8+w*h}
