// AUTHORED fixed-route read-only adapter. Decoder output never grants access.
import {allowed,type PortalSession} from "@/platform/auth/session";
import {boundedDocumentBytes} from "@/platform/documents-vnext/gateway";
import {MAX_FRAME_BYTES,decodeSchema,resolveCommand,resolutionSchema,validFrame} from "./contract";
export type CaptureTransport=(session:PortalSession,action:"decode"|"resolve",body:Uint8Array|string)=>Promise<Response>;
const reply=(status:number,body:unknown)=>Response.json(body,{status,headers:{"cache-control":"no-store","x-content-type-options":"nosniff"}});
export function captureAllowed(session:PortalSession){return /^[a-f0-9-]{36}$/iu.test(session.tenantId)&&Boolean(session.subject)&&(session.organizations.length>0||allowed(session,"*"))&&["inventory:allocate","payment:create","handover:manage","admin:read","inventory:read","factory:read","supply:read","supply:factory-read"].some(permission=>allowed(session,permission))}
export function createCaptureGateway(deps:{session:()=>Promise<PortalSession|null>;config:()=>{origin:string};transport:CaptureTransport}){return async(request:Request)=>{
 const session=await deps.session();if(!session)return reply(401,{code:"UNAUTHENTICATED",business_effect:false});if(!captureAllowed(session))return reply(403,{code:"FORBIDDEN",business_effect:false});let origin:string;try{origin=deps.config().origin}catch{return reply(503,{code:"CAPTURE_UNAVAILABLE",business_effect:false})}
 if(request.method!=="POST"||request.headers.get("origin")!==origin)return reply(403,{code:"CROSS_ORIGIN_REJECTED",business_effect:false});const url=new URL(request.url),action=url.searchParams.get("action");if([...url.searchParams.keys()].length!==1||!['decode','resolve'].includes(action??''))return reply(400,{code:"INVALID_QUERY",business_effect:false});
 let body:Uint8Array|string;
 try{if(action==="decode"){if(request.headers.get("content-type")!=="application/octet-stream")throw new Error("TYPE");const frame=await boundedDocumentBytes(request,MAX_FRAME_BYTES);if(!validFrame(frame))throw new Error("FRAME");body=frame}else{if(request.headers.get("content-type")!=="application/json")throw new Error("TYPE");body=JSON.stringify(resolveCommand.parse(JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(await boundedDocumentBytes(request,8192)))))} }catch{return reply(400,{code:"INVALID_CAPTURE",business_effect:false})}
 try{const response=await deps.transport(session,action as "decode"|"resolve",body);if(!response.ok)return reply([401,403,404,408,429,503].includes(response.status)?response.status:502,{code:response.status===404?"NOT_FOUND":"CAPTURE_UNAVAILABLE",business_effect:false});const value=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(await boundedDocumentBytes(response,65536)));if(action==="decode")return reply(200,decodeSchema.parse(value));const result=resolutionSchema.parse(value);if(result.records.some(record=>!allowed(session,"*")&&!session.organizations.includes(record.organization_id)))throw new Error("ORGANIZATION");return reply(200,result)}catch{return reply(503,{code:"CAPTURE_UNAVAILABLE",business_effect:false})}
}}
