<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>all</NuGetAuditMode>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../bridge/src/Elite.Arca.Wsfe.Bridge/Elite.Arca.Wsfe.Bridge.csproj" />
    <ProjectReference Include="../../generated/Elite.Arca.Wsfe.Generated.csproj" />
    <ProjectReference Include="../../../credentials/src/Elite.Arca.Credentials/Elite.Arca.Credentials.csproj" />
  </ItemGroup>
</Project>
