import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { notificationExplanation, notificationHistorySchema, STATUS_VIEW_VERSION, type NotificationStatus } from "./status-contract";
const status: NotificationStatus = { delivery_key: "test-delivery-reference", fence_state: "accepted", delivery_status: "not_observed_by_this_reader", provider_event_count: 0, approval_expires_at: "2026-09-07T01:00:00Z", approval_expired: true, accepted_at: "2026-09-06T01:00:00Z", observed_at: "2026-09-07T02:00:00Z", reconciliation_required: false };
const item = { confirmation_event_id: "11111111-1111-4111-8111-111111111111", status };
const history = { organization_id: "store", appointment_id: "appointment", items: [item] };
describe("notification projection and operational explanation", () => {
  it("ships the same operational guide version as the UI", () => { const guide=readFileSync(new URL("../../../docs/whatsapp-status-operations.md", import.meta.url),"utf8"); expect(guide).toContain(`Guía: ${STATUS_VIEW_VERSION}`); expect(guide).toContain("no marca automáticamente personas capacitadas"); });
  it("does not equate accepted with delivery or business acceptance", () => { expect(notificationHistorySchema.safeParse(history).success).toBe(true); expect(notificationExplanation(status).title).toContain("entrega sin verificar"); expect(STATUS_VIEW_VERSION).toBe("whatsapp-status-view/1.0.0"); });
  it.each(["observed_sent", "observed_delivered", "observed_read", "observed_failed", "observed_deleted"] as const)("labels verified %s as a provider report", delivery_status => { const value = { ...status, delivery_status, provider_event_count: 1, provider_timestamp: 1603086314 }; expect(notificationHistorySchema.safeParse({ ...history, items: [{ ...item, status: value }] }).success).toBe(true); expect(notificationExplanation(value).title).toContain("proveedor informó"); expect(notificationExplanation(value).guidance).toContain("no acredita una venta"); });
  it("keeps ambiguous and unknown states actionable without resend", () => { expect(notificationExplanation({ ...status, delivery_status: "ambiguous_latest_timestamp" }).title).toContain("contradictorios"); expect(notificationExplanation({ ...status, fence_state: "unknown", reconciliation_required: true }).guidance).toContain("No reenvíes"); });
  it.each([{ ...status, provider_timestamp: 1 }, { ...status, provider_event_count: 1 }, { ...status, fence_state: "unknown" }, { ...status, accepted_at: undefined }, { ...status, delivery_status: "unrecognized" }, { ...status, raw_message: "secret" }])("rejects contradictory/unknown fields", invalid => { expect(notificationHistorySchema.safeParse({ ...history, items: [{ ...item, status: invalid }] }).success).toBe(false); });
  it("rejects duplicate or oversized history", () => { expect(notificationHistorySchema.safeParse({ ...history, items: [item, item] }).success).toBe(false); expect(notificationHistorySchema.safeParse({ ...history, items: Array(21).fill(item) }).success).toBe(false); });
});
