"use client";
import{useEffect,useRef,useState}from"react";
import{clientAccessSchema,pageSchema,resultSchema,markerSchema,commandSchema,digest,expectedProjection,minorDisplay,minorSchema,type FinanceAccess,type FinanceAction,type FinanceMarker,type FinancePayload,type FinanceResult}from"@/platform/finance-vnext/contract";
import{FinanceForm,labels,rowID,rowLabel,type FinanceRow}from"./finance-form";
import s from"./finance.module.css";
const endpoint='/api/enterprise/finance-vnext',groups=['Contabilidad','Regalías','Cambio de moneda']as const;
const views={Contabilidad:[['journals','Asientos'],['periods','Períodos'],['accounts','Cuentas']],Regalías:[['settlements','Liquidaciones'],['policies','Políticas'],['agreements','Acuerdos']],"Cambio de moneda":[['conversions','Conversiones']]}as const;
const human:Record<string,string>={draft:'Borrador',posted:'Contabilizado',reversed:'Revertido',closed:'Cerrado',open:'Abierto',active:'Activo',captured:'Confirmado',refunded:'Devuelto',matched:'Conciliado',mismatch:'Diferencia detectada'};
const storeKey=(scope:string)=>'elite.finance.pending.v1.'+scope;
function storage(scope:string,marker:FinanceMarker|null){if(marker)sessionStorage.setItem(storeKey(scope),JSON.stringify(marker));else sessionStorage.removeItem(storeKey(scope))}
function saved(scope:string){const raw=sessionStorage.getItem(storeKey(scope));if(raw===null)return null;return markerSchema.parse(JSON.parse(raw))}
function resultText(value:FinanceResult,access:FinanceAccess){const r=value.result as any;if(value.action==='fx_conversion'){const c=r.conversion;const decimals=access.fx.currencies.find(v=>v.code===c.to_currency)?.minor_unit_decimals;return c.to_currency+' '+minorDisplay(c.output_minor,decimals)+' · Conversión calculada. Todavía no fue contabilizada.'}if(value.action==='fx_journal')return 'Asiento de conversión preparado. Revisalo antes de contabilizar.';if(value.action==='royalty_reconcile')return human[r.status]??'Conciliación registrada.';const exact:Partial<Record<FinanceAction,string>>={royalty_policy:'Política guardada.',royalty_accrue:'Regalía registrada.',royalty_open:'Liquidación abierta.',royalty_close:'Liquidación cerrada.',royalty_reverse:'Liquidación revertida.',accounting_account:'Cuenta creada.',accounting_period:'Período abierto.',accounting_journal:'Asiento preparado. Revisalo antes de contabilizar.',accounting_post:'Asiento contabilizado.',accounting_reverse:'Asiento revertido.',accounting_close:'Período cerrado.'};return exact[value.action]??'Operación confirmada.'}
export function FinanceWorkspace(){
 const[access,setAccess]=useState<FinanceAccess|null>(null),[start,setStart]=useState<'loading'|'error'|'forbidden'|'ready'>('loading'),[group,setGroup]=useState<typeof groups[number]>('Contabilidad'),[view,setView]=useState('journals'),[rows,setRows]=useState<FinanceRow[]>([]),[cursor,setCursor]=useState<string|null>(null),[listState,setListState]=useState<'loading'|'ready'|'error'|'forbidden'>('loading'),[selected,setSelected]=useState<FinanceRow|null>(null),[query,setQuery]=useState(''),[action,setAction]=useState<FinanceAction|null>(null),[attempt,setAttempt]=useState(0),[key,setKey]=useState(''),[initial,setInitial]=useState<Record<string,string>>({}),[pending,setPending]=useState<FinanceMarker|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[outcome,setOutcome]=useState<FinanceResult|null>(null),[readResult,setReadResult]=useState<FinanceRow[]|null>(null),[readBusy,setReadBusy]=useState(false),[detailCursor,setDetailCursor]=useState<string|null>(null);
 const alive=useRef(true),listAbort=useRef<AbortController|null>(null),readAbort=useRef<AbortController|null>(null),effectLock=useRef(false),scopeRef=useRef('');
 async function loadAccess(){setStart('loading');try{const r=await fetch(endpoint,{cache:'no-store',signal:AbortSignal.timeout(10000)});if(r.status===401||r.status===403){setAccess(null);setStart('forbidden');return}if(!r.ok)throw new Error();const a=clientAccessSchema.parse(await r.json());if(!alive.current)return;scopeRef.current=a.scope;setAccess(a);try{const marker=saved(a.scope);setPending(marker);if(marker){setAction(marker.action);setKey(marker.key);setMessage('Hay una operación pendiente de confirmar. Consultá su resultado antes de continuar.')}}catch{setMessage('No pudimos leer la operación pendiente. Conservá esta sesión y pedí ayuda antes de volver a confirmar.');effectLock.current=true}if(!a.actions.includes('accounting_read')){setGroup('Regalías');setView('settlements')}setStart('ready')}catch{if(alive.current)setStart('error')}}
 useEffect(()=>{alive.current=true;void loadAccess();return()=>{alive.current=false;listAbort.current?.abort();readAbort.current?.abort()}},[]);
 async function loadList(next?:string){if(!access)return;listAbort.current?.abort();const c=new AbortController();listAbort.current=c;setListState('loading');try{const r=await fetch(endpoint+'?view='+view+'&limit=25'+(next?'&cursor='+encodeURIComponent(next):''),{cache:'no-store',signal:AbortSignal.any([c.signal,AbortSignal.timeout(10000)])});if(r.status===401||r.status===403){if(!c.signal.aborted){setRows([]);setSelected(null);setListState('forbidden')}return}if(!r.ok)throw new Error();const p=pageSchema.parse(await r.json());if(p.organization_id!==access.organization_id||p.view!==view)throw new Error();if(!c.signal.aborted){setRows(old=>next?[...old,...p.items]:p.items);setCursor(p.next_cursor);setListState('ready')}}catch{if(!c.signal.aborted)setListState('error')}}
 useEffect(()=>{setRows([]);setCursor(null);setSelected(null);setReadResult(null);setQuery('');readAbort.current?.abort();if(access)void loadList();return()=>listAbort.current?.abort()},[access?.scope,view]);
 function open(a:FinanceAction,data:Record<string,string>={}){if(!access||!access.actions.includes(a)||busy||pending||effectLock.current)return;setInitial(data);setAction(a);setKey(crypto.randomUUID());setAttempt(v=>v+1);setOutcome(null);setMessage('')}
 async function accept(value:unknown,marker:FinanceMarker){if(!access)throw new Error();const r=resultSchema.parse(value);if(r.organization_id!==access.organization_id||r.action!==marker.action||r.key!==marker.key||r.proof_sha256!==marker.proof_sha256)throw new Error('RECEIPT_MISMATCH');storage(access.scope,null);setPending(null);if(r.outcome==='REJECTED'){setOutcome(null);setMessage(r.result.code==='STATE_CONFLICT'?'El registro cambió o no admite esa operación. Volvé a consultar las opciones.':'Los datos no cumplen las condiciones de la operación. Corregilos antes de confirmar.');setKey(crypto.randomUUID());return r}setOutcome(r);setAction(null);setMessage('');setSelected(null);void loadList();return r}
 async function submit(payload:FinancePayload){if(!access||!action||effectLock.current)return;effectLock.current=true;setBusy(true);setMessage('');let marker:FinanceMarker|null=pending;try{const command=commandSchema.parse({action,key,payload}),requestSHA=await digest(command),proofSHA=await digest(expectedProjection(action,payload,access.organization_id));if(marker&&(marker.request_sha256!==requestSHA||marker.proof_sha256!==proofSHA))throw new Error('CHANGED');marker={key,action,request_sha256:requestSHA,proof_sha256:proofSHA};storage(access.scope,marker);setPending(marker);const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(command),signal:AbortSignal.timeout(12000)});const value=await r.json();if(!r.ok){if(value.effect==='NOT_ATTEMPTED'&&!pending){storage(access.scope,null);setPending(null);setMessage(r.status===403?'No tenés permiso para esta operación.':'Revisá los datos. La operación no se envió.');return}throw new Error('UNCONFIRMED')}await accept(value,marker)}catch(e){if(alive.current)setMessage(e instanceof Error&&e.message==='CHANGED'?'Los datos no coinciden con el intento pendiente. Conservá los valores originales o consultá el resultado.':marker?'Aún no pudimos confirmar el resultado. Consultalo antes de hacer otra operación.':'Revisá los datos. No se envió la operación.')}finally{effectLock.current=false;if(alive.current)setBusy(false)}}
 async function recover(){if(!access||!pending||effectLock.current)return;effectLock.current=true;setBusy(true);setMessage('');try{const r=await fetch(endpoint+'?result='+pending.action+'&key='+encodeURIComponent(pending.key),{cache:'no-store',signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(String(r.status));await accept(await r.json(),pending)}catch(e){if(alive.current)setMessage(e instanceof Error&&e.message==='404'?'El resultado todavía no está disponible. Si reintentás, usá exactamente los mismos datos.':'No pudimos recuperar el resultado. La operación sigue pendiente.')}finally{effectLock.current=false;if(alive.current)setBusy(false)}}
 async function readDetail(kind:'journal_lines'|'trial_balance',next?:string){if(!access||!selected)return;readAbort.current?.abort();const c=new AbortController();readAbort.current=c;setReadBusy(true);setMessage('');try{const r=await fetch(endpoint+'?view='+kind+'&record='+encodeURIComponent(rowID(selected))+(kind==='journal_lines'?'&limit=25'+(next?'&cursor='+encodeURIComponent(next):''):''),{cache:'no-store',signal:AbortSignal.any([c.signal,AbortSignal.timeout(10000)])});if(!r.ok)throw new Error();const raw=await r.json();const value=kind==='journal_lines'?pageSchema.parse(raw):null;const items=value?.items??raw;if(!Array.isArray(items))throw new Error();if(!c.signal.aborted){setReadResult(old=>next?[...(old??[]),...items]:items);setDetailCursor(value?.next_cursor??null)}}catch{if(!c.signal.aborted)setMessage('No pudimos cargar el detalle. Volvé a consultar.')}finally{if(!c.signal.aborted)setReadBusy(false)}}
 const allowedGroups=groups.filter(g=>g==='Regalías'?access?.actions.some(a=>a.startsWith('royalty_')):access?.actions.includes('accounting_read'));
 const available=access?.actions.filter((a):a is FinanceAction=>a in labels&&(group==='Regalías'?a.startsWith('royalty_'):group==='Cambio de moneda'?a.startsWith('fx_'):a.startsWith('accounting_')))??[];
 const visibleRows=rows.filter(r=>rowLabel(view,r).toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 if(start==='loading')return <div className={s.root} data-finance-state="loading"><h1>Finanzas</h1><p role="status">Cargando…</p></div>;
 if(start==='forbidden')return <div className={s.root} data-finance-state="forbidden"><h1>Finanzas</h1><p>No tenés acceso a este espacio.</p></div>;
 if(start==='error'||!access)return <div className={s.root} data-finance-state="error"><h1>Finanzas</h1><p role="alert">No pudimos cargar el espacio.</p><button onClick={()=>void loadAccess()}>Volver a intentar</button></div>;
 return <div className={s.root} data-testid="finance-workspace" data-finance-state={pending?'uncertain':outcome?'success':'ready'}>
 <header className={s.heading}><div><p className={s.eyebrow}>{access.organization_name}</p><h1>Finanzas</h1></div></header>
 {message?<p className={s.notice} role="alert">{message}</p>:null}
 {pending?<section className={s.pending} aria-label="Operación pendiente"><div><strong>Confirmación pendiente</strong><p>{labels[pending.action]}</p></div><button className={s.primary} disabled={busy} onClick={()=>void recover()}>{busy?'Consultando…':'Consultar resultado'}</button>{!action?<button className={s.link} disabled={busy} onClick={()=>{setAction(pending.action);setKey(pending.key)}}>Revisar datos del intento</button>:null}</section>:null}
 {outcome?<section className={s.success} role="status"><strong>{resultText(outcome,access)}</strong>{outcome.action==='fx_conversion'&&access.actions.includes('fx_journal')?<button className={s.link} onClick={()=>{setGroup('Cambio de moneda');setView('conversions');open('fx_journal',{conversion:String(outcome.result.conversion_id)})}}>Preparar su asiento</button>:null}</section>:null}
 {action?<FinanceForm key={action+':'+attempt} action={action} access={access} busy={busy} pending={!!pending} keyValue={key} initial={initial} onSubmit={payload=>void submit(payload)} onCancel={()=>{setAction(null);setMessage('')}}/>:<>
 <nav className={s.tabs} aria-label="Área financiera">{allowedGroups.map(g=><button key={g} aria-current={group===g?'page':undefined} disabled={busy} onClick={()=>{setGroup(g);setView(views[g][0][0])}}>{g}</button>)}</nav>
 <div className={s.toolbar}><nav className={s.subnav} aria-label="Registros financieros">{views[group].map(([v,label])=><button key={v} aria-current={view===v?'page':undefined} onClick={()=>{setView(v);setSelected(null)}}>{label}</button>)}</nav>{available.length?<details className={s.newOperation}><summary aria-disabled={!!pending}>Nueva operación</summary><div>{available.map(a=><button key={a} disabled={!!pending||busy} onClick={()=>open(a)}>{labels[a]}</button>)}</div></details>:null}</div>
 {selected?<section className={s.detail} data-testid="finance-detail"><button className={s.back} onClick={()=>{readAbort.current?.abort();setSelected(null);setReadResult(null);setDetailCursor(null)}}>← Volver a la lista</button><h2>{rowLabel(view,selected)}</h2>{selected.status?<p>{human[selected.status]??selected.status}</p>:null}
 {view==='journals'?<><p>Debe {selected.currency} {minorDisplay(selected.total_debit_minor_units,access.fx.currencies.find(c=>c.code===selected.currency)?.minor_unit_decimals)} · Haber {minorDisplay(selected.total_credit_minor_units,access.fx.currencies.find(c=>c.code===selected.currency)?.minor_unit_decimals)}</p><button className={s.link} disabled={readBusy} onClick={()=>void readDetail('journal_lines')}>Ver movimientos</button><div className={s.actions}>{selected.status==='draft'&&available.includes('accounting_post')?<button className={s.primary} disabled={!!pending} onClick={()=>open('accounting_post',{journal:rowID(selected)})}>Contabilizar asiento</button>:null}{selected.status==='posted'&&available.includes('accounting_reverse')?<button className={s.secondary} disabled={!!pending} onClick={()=>open('accounting_reverse',{journal:rowID(selected)})}>Revertir asiento</button>:null}</div></>:null}
 {view==='periods'?<><button className={s.link} disabled={readBusy} onClick={()=>void readDetail('trial_balance')}>Ver balance de comprobación</button>{selected.status==='open'&&available.includes('accounting_close')?<button className={s.secondary} disabled={!!pending} onClick={()=>open('accounting_close',{period:rowID(selected)})}>Cerrar período</button>:null}</>:null}
 {view==='settlements'?<><p>Importe: {selected.currency} {minorDisplay(selected.expected_minor_units,access.fx.currencies.find(c=>c.code===selected.currency)?.minor_unit_decimals)}</p><div className={s.actions}>{(['royalty_close','royalty_reverse','royalty_reconcile']as const).filter(a=>available.includes(a)&&selected.status===(a==='royalty_close'?'draft':'closed')).map(a=><button className={a==='royalty_reverse'?s.secondary:s.primary} key={a} disabled={!!pending} onClick={()=>open(a,{settlement:rowID(selected)})}>{labels[a]}</button>)}</div></>:null}
 {view==='conversions'?<><p>Resultado calculado: {selected.conversion?.to_currency} {minorDisplay(selected.conversion?.output_minor,access.fx.currencies.find(c=>c.code===selected.conversion?.to_currency)?.minor_unit_decimals)}</p><p className={s.hint}>La conversión no contabiliza un asiento por sí sola.</p>{available.includes('fx_journal')?<button className={s.primary} disabled={!!pending} onClick={()=>open('fx_journal',{conversion:rowID(selected)})}>Preparar su asiento</button>:null}</>:null}
 {view==='accounts'?<p>{selected.label} · {human[selected.active?'active':'inactive']??'Inactiva'}</p>:null}
 {readBusy?<p role="status">Cargando movimientos…</p>:null}{readResult?<div className={s.ledger}>{readResult.length===0?<p>No hay movimientos para mostrar.</p>:readResult.map((r,i)=><div className={s.line} key={i}><span>{String(r.label??r.account_code??'Cuenta')}<small>{String(r.description??r.currency??'')}</small></span><span>Debe {minorDisplay(r.debit_minor_units,access.fx.currencies.find(c=>c.code===(r.currency??selected.currency))?.minor_unit_decimals)} · Haber {minorDisplay(r.credit_minor_units,access.fx.currencies.find(c=>c.code===(r.currency??selected.currency))?.minor_unit_decimals)}</span></div>)}{view==='journals'&&detailCursor?<button className={s.link} disabled={readBusy} onClick={()=>void readDetail('journal_lines',detailCursor!)}>Cargar siguientes movimientos</button>:null}</div>:null}
 </section>:<><label className={s.search}>Buscar en los registros cargados<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar…"/></label><div className={s.list} data-testid="finance-list" data-state={listState==='ready'&&!visibleRows.length?'empty':listState}>{listState==='loading'?<p role="status">Cargando registros…</p>:null}{listState==='error'?<p role="alert">No pudimos cargar los registros. <button className={s.link} onClick={()=>void loadList()}>Volver a intentar</button></p>:null}{listState==='forbidden'?<p>No tenés permiso para ver estos registros.</p>:null}{listState==='ready'&&!visibleRows.length?<p>{query?'No hay coincidencias en los registros cargados.':'Todavía no hay registros.'}</p>:null}{visibleRows.map(row=><button className={s.row} key={rowID(row)} data-record-id={rowID(row)} onClick={()=>{setSelected(row);setReadResult(null);setDetailCursor(null)}}><span>{rowLabel(view,row)}<small>{human[row.status]??''}</small></span><span aria-hidden="true">→</span></button>)}</div>{cursor?<button className={s.link} disabled={listState==='loading'} onClick={()=>void loadList(cursor!)}>Cargar más registros</button>:null}</>}
 </>}
 </div>
}
