"use client";
import{useEffect,useRef,useState}from"react";
import{pageSchema,journalLineSchema,decimalMinor,minorDisplay,versionSchema,type FinanceAccess,type FinanceAction,type FinancePayload}from"@/platform/finance-vnext/contract";
import s from"./finance.module.css";
export type FinanceRow=Record<string,any>;const endpoint="/api/enterprise/finance-vnext";
export const labels:Record<FinanceAction,string>={fx_conversion:"Calcular conversión",fx_journal:"Preparar asiento de conversión",royalty_policy:"Nueva política de regalías",royalty_accrue:"Registrar regalía de un pago",royalty_open:"Nueva liquidación",royalty_close:"Cerrar liquidación",royalty_reverse:"Revertir liquidación",royalty_reconcile:"Conciliar liquidación",accounting_account:"Nueva cuenta",accounting_period:"Abrir período",accounting_journal:"Nuevo asiento manual",accounting_post:"Contabilizar asiento",accounting_reverse:"Revertir asiento",accounting_close:"Cerrar período"};
export function rowID(row:FinanceRow){return String(row.id??row.conversion_id??'')}
export function rowLabel(view:string,row:FinanceRow){if(view==='conversions')return `${row.conversion?.from_currency} → ${row.conversion?.to_currency} · ${minorDisplay(row.conversion?.output_minor,row.conversion?.to_decimals)} · ${row.conversion?.conversion_date}`;if(view==='periods')return `${row.starts_on} — ${row.ends_on}`;if(view==='settlements')return `${row.currency} · ${String(row.period_start).slice(0,10)} — ${String(row.period_end).slice(0,10)}`;if(view==='payments')return `${row.currency} · ${row.state==='captured'?'Pago confirmado':'Pago devuelto'} · ${String(row.updated_at??'').slice(0,10)}`;if(view==='journals')return `${row.currency} · ${row.posting_date} · ${row.description||'Asiento contable'}`;if(view==='policies')return `${row.currency} · ${Number(row.rate_basis_points)/100}% · ${String(row.valid_from).slice(0,10)}`;return String(row.label??row.name??row.id??'Registro')}
const needs:Record<FinanceAction,string[]>={fx_conversion:[],fx_journal:['conversions','accounts','periods'],royalty_policy:['agreements'],royalty_accrue:['payments'],royalty_open:[],royalty_close:['settlements'],royalty_reverse:['settlements'],royalty_reconcile:['settlements'],accounting_account:[],accounting_period:[],accounting_journal:['accounts','periods'],accounting_post:['journals'],accounting_reverse:['journals'],accounting_close:['periods']};
const utc=(value:string|undefined)=>{if(!value)throw new Error('Fecha requerida');const d=new Date(value.length===10?value+'T00:00:00Z':value.endsWith('Z')?value:value+'Z');if(Number.isNaN(d.getTime()))throw new Error('Fecha inválida');return d.toISOString().replace(/\.000Z$/u,'Z')};
export function FinanceForm({action,access,busy,pending,keyValue,initial={},onSubmit,onCancel}:{action:FinanceAction;access:FinanceAccess;busy:boolean;pending:boolean;keyValue:string;initial?:Record<string,string>;onSubmit:(payload:FinancePayload)=>void;onCancel:()=>void}){
 const [fields,setFields]=useState<Record<string,string>>(initial),[lists,setLists]=useState<Record<string,FinanceRow[]>>({}),[cursors,setCursors]=useState<Record<string,string|null>>({}),[loading,setLoading]=useState<Record<string,boolean>>({}),[error,setError]=useState(''),[journalLines,setJournalLines]=useState<FinanceRow[]>([]),[lineCursor,setLineCursor]=useState<string|null>(null),[lineState,setLineState]=useState<'idle'|'loading'|'ready'|'error'>('idle');
 const [entries,setEntries]=useState([{account:'',side:'debit',amount:'',description:''},{account:'',side:'credit',amount:'',description:''}]);const alive=useRef(true),abort=useRef(new AbortController()),lineAbort=useRef<AbortController|null>(null);
 const set=(name:string,value:string)=>setFields(old=>({...old,[name]:value}));
 async function choices(view:string,cursor?:string){setLoading(old=>({...old,[view]:true}));try{const response=await fetch(endpoint+'?view='+view+'&limit=25'+(cursor?'&cursor='+encodeURIComponent(cursor):''),{cache:'no-store',signal:AbortSignal.any([abort.current.signal,AbortSignal.timeout(10000)])});if(!response.ok)throw new Error('LIST');const data=pageSchema.parse(await response.json());if(data.organization_id!==access.organization_id||data.view!==view)throw new Error('SCOPE');if(alive.current){setLists(old=>({...old,[view]:cursor?[...(old[view]??[]),...data.items]:data.items}));setCursors(old=>({...old,[view]:data.next_cursor}));setError('')}}catch{if(alive.current)setError('No pudimos cargar las opciones. Volvé a consultar.')}finally{if(alive.current)setLoading(old=>({...old,[view]:false}))}}
 useEffect(()=>{alive.current=true;abort.current=new AbortController();for(const view of needs[action])void choices(view);return()=>{alive.current=false;abort.current.abort();lineAbort.current?.abort()}},[action,access.scope]);
 async function lines(id:string,cursor?:string){lineAbort.current?.abort();const controller=new AbortController();lineAbort.current=controller;setLineState('loading');try{const response=await fetch(endpoint+'?view=journal_lines&record='+encodeURIComponent(id)+'&limit=25'+(cursor?'&cursor='+encodeURIComponent(cursor):''),{cache:'no-store',signal:AbortSignal.any([controller.signal,AbortSignal.timeout(10000)])});if(!response.ok)throw new Error('LINES');const data=pageSchema.parse(await response.json());if(data.organization_id!==access.organization_id||data.view!=='journal_lines')throw new Error('SCOPE');data.items=data.items.map(row=>journalLineSchema.parse(row));if(!controller.signal.aborted){setJournalLines(old=>cursor?[...old,...data.items]:data.items);setLineCursor(data.next_cursor);setLineState('ready')}}catch{if(!controller.signal.aborted)setLineState('error')}}
 useEffect(()=>{if(initial.journal&&(action==='accounting_post'||action==='accounting_reverse'))void lines(initial.journal)},[action,initial.journal]);
 const chosen=(view:string,key:string)=>lists[view]?.find(row=>rowID(row)===fields[key]);
 const field=(name:string,label:string,type='text',optional=false)=><label key={name}>{label}<input name={name} type={type} value={fields[name]??''} required={!optional} disabled={busy} maxLength={type==='text'?250:undefined} inputMode={['amount','rate','actual'].includes(name)?'decimal':undefined} onChange={e=>set(name,e.target.value)}/></label>;
 function picker(name:string,label:string,view:string,filter:(row:FinanceRow)=>boolean=()=>true){return <div className={s.picker} key={name}><label>{label}<select aria-label={label} required value={fields[name]??''} disabled={busy||loading[view]} onChange={e=>{set(name,e.target.value);if(name==='journal'){setJournalLines([]);setLineCursor(null);if(e.target.value)void lines(e.target.value);else{lineAbort.current?.abort();setLineState('idle')}}}}><option value="">{loading[view]?'Cargando…':'Elegí una opción'}</option>{(lists[view]??[]).filter(filter).map(row=><option key={rowID(row)} value={rowID(row)}>{rowLabel(view,row)}</option>)}</select></label>{cursors[view]?<button type="button" className={s.link} disabled={busy||loading[view]} onClick={()=>void choices(view,cursors[view]!)}>Cargar más opciones</button>:null}{!loading[view]&&lists[view]?.filter(filter).length===0?<p className={s.hint}>No hay opciones disponibles.</p>:null}</div>}
 function currency(name='currency',label='Moneda'){const values=access.fx.currencies;return values.length?<label key={name}>{label}<select aria-label={label} value={fields[name]??''} required disabled={busy} onChange={e=>set(name,e.target.value)}><option value="">Elegí una moneda</option>{values.map(c=><option value={c.code} key={c.code}>{c.code}</option>)}</select></label>:field(name,label+' (código ISO)')}
 function decimals(code:string|undefined){return access.fx.currencies.find(c=>c.code===code)?.minor_unit_decimals}
 function amount(value:string,code:string|undefined){const precision=decimals(code);return decimalMinor(value,precision??0)}
 function moneyLabel(label:string,code?:string){return decimals(code)===undefined?label+' (unidades mínimas de '+(code||'la moneda')+')':label+(code?' · '+code:'')}
 function payload():FinancePayload{let row:FinanceRow|undefined;switch(action){
 case'fx_conversion':if(!access.fx.enabled)throw new Error('No hay un tipo de cambio disponible.');return{from_currency:fields.from,to_currency:fields.to,amount_minor:amount(fields.amount!,fields.from),conversion_date:fields.date};
 case'fx_journal':row=chosen('conversions','conversion');if(!row)throw new Error('Elegí una conversión');return{conversion_id:row.conversion_id,conversion_request_key:row.request_key,period_id:fields.period,debit_account:fields.debit,credit_account:fields.credit,description:fields.description??''};
 case'royalty_policy':return{agreement_id:fields.agreement,currency:fields.currency,rate_basis_points:Number(decimalMinor(fields.rate!,2)),valid_from:utc(fields.from),...(fields.until?{valid_until:utc(fields.until)}:{})};
 case'royalty_open':return{currency:fields.currency,period_start:utc(fields.from),period_end:utc(fields.until)};
 case'royalty_accrue':row=chosen('payments','payment');if(!row)throw new Error('Elegí un pago');return{payment_attempt_id:row.id,payment_expected_version:versionSchema.parse(Number(row.version)),state:row.state,occurred_at:utc(fields.occurred),source_event_key:keyValue};
 case'royalty_close':case'royalty_reverse':row=chosen('settlements','settlement');if(!row)throw new Error('Elegí una liquidación');return{settlement_id:row.id,expected_version:versionSchema.parse(Number(row.version)),...(action==='royalty_reverse'?{reason:fields.reason}:{})};
 case'royalty_reconcile':row=chosen('settlements','settlement');if(!row)throw new Error('Elegí una liquidación');return{settlement_id:row.id,external_reference:fields.reference,actual_minor_units:amount(fields.actual!,row.currency)};
 case'accounting_account':return{code:fields.code,name:fields.name,type:fields.type};
 case'accounting_period':return{starts_on:utc(fields.from),ends_on:utc(fields.until)};
 case'accounting_journal':return{period_id:fields.period,source_type:'MANUAL',source_id:fields.reference,currency:fields.currency,posting_date:utc(fields.date),lines:entries.map((v,i)=>({line_no:i+1,account_code:v.account,description:v.description,debit_minor_units:v.side==='debit'?amount(v.amount,fields.currency):'0',credit_minor_units:v.side==='credit'?amount(v.amount,fields.currency):'0'}))};
 case'accounting_post':case'accounting_reverse':row=chosen('journals','journal');if(!row||lineState!=='ready'||lineCursor)throw new Error('Revisá todas las líneas antes de confirmar.');return{journal_id:row.id,expected_version:versionSchema.parse(Number(row.version)),...(action==='accounting_reverse'?{reason:fields.reason}:{})};
 case'accounting_close':row=chosen('periods','period');if(!row)throw new Error('Elegí un período');return{period_id:row.id,expected_version:versionSchema.parse(Number(row.version))};
 }}
 const settlement=chosen('settlements','settlement'),journal=chosen('journals','journal');
 return <form className={s.form} onSubmit={e=>{e.preventDefault();try{setError('');onSubmit(payload())}catch(err){setError(err instanceof Error?err.message:'Revisá los campos')}}} data-testid="finance-form">
 <button type="button" className={s.back} disabled={busy} onClick={onCancel}>← Volver</button><h2>{labels[action]}</h2>
 {error?<p role="alert" className={s.error}>{error} {needs[action].length?<button className={s.link} type="button" disabled={busy} onClick={()=>needs[action].forEach(view=>void choices(view))}>Volver a consultar</button>:null}</p>:null}
 <div className={s.fields}>
 {action==='fx_conversion'?<>{currency('from','Moneda de origen')}{currency('to','Moneda de destino')}{field('amount',moneyLabel('Importe',fields.from))}{field('date','Fecha de conversión','date')}</>:null}
 {action==='fx_journal'?<>{picker('conversion','Conversión','conversions')}{picker('period','Período','periods',r=>r.status==='open')}{picker('debit','Cuenta al debe','accounts',r=>r.active)}{picker('credit','Cuenta al haber','accounts',r=>r.active)}{field('description','Descripción','text',true)}</>:null}
 {action==='royalty_policy'?<>{picker('agreement','Acuerdo','agreements',r=>r.status==='active')}{currency()}{field('rate','Porcentaje de regalía')}{field('from','Vigente desde · UTC','date')}{field('until','Hasta, sin incluir · UTC','date',true)}</>:null}
 {action==='royalty_open'?<>{currency()}{field('from','Inicio · UTC','date')}{field('until','Fin, sin incluir · UTC','date')}</>:null}
 {action==='royalty_accrue'?<>{picker('payment','Pago','payments',r=>['captured','refunded'].includes(r.state))}{field('occurred','Fecha del evento confirmada · UTC','datetime-local')}</>:null}
 {['royalty_close','royalty_reverse','royalty_reconcile'].includes(action)?<>{picker('settlement','Liquidación','settlements',r=>r.status===(action==='royalty_close'?'draft':'closed')&&(action!=='royalty_reverse'||!r.reversal_of))}{action==='royalty_reverse'?field('reason','Motivo de la reversión'):null}{action==='royalty_reconcile'?<>{field('reference','Referencia del comprobante')}{field('actual',moneyLabel('Importe confirmado',settlement?.currency))}</>:null}</>:null}
 {action==='accounting_account'?<>{field('code','Código contable')}{field('name','Nombre de la cuenta')}<label>Tipo<select aria-label="Tipo de cuenta" value={fields.type??''} required disabled={busy} onChange={e=>set('type',e.target.value)}><option value="">Elegí un tipo</option>{[['asset','Activo'],['liability','Pasivo'],['equity','Patrimonio'],['revenue','Ingreso'],['expense','Gasto']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></>:null}
 {action==='accounting_period'?<>{field('from','Inicio · UTC','date')}{field('until','Fin, sin incluir · UTC','date')}</>:null}
 {action==='accounting_journal'?<>{picker('period','Período','periods',r=>r.status==='open')}{currency()}{field('date','Fecha contable · UTC','date')}{field('reference','Referencia del asiento')}</>:null}
 {action==='accounting_post'||action==='accounting_reverse'?<>{picker('journal','Asiento','journals',r=>r.status===(action==='accounting_post'?'draft':'posted'))}{action==='accounting_reverse'?field('reason','Motivo de la reversión'):null}</>:null}
 {action==='accounting_close'?picker('period','Período','periods',r=>r.status==='open'):null}
 </div>
 {action==='accounting_journal'?<section className={s.entries}><h3>Movimientos</h3>{entries.map((entry,index)=><fieldset key={index}><legend>Movimiento {index+1}</legend><div className={s.fields}><label>Cuenta<select aria-label={'Cuenta del movimiento '+(index+1)} required disabled={busy} value={entry.account} onChange={e=>setEntries(old=>old.map((v,i)=>i===index?{...v,account:e.target.value}:v))}><option value="">Elegí una cuenta</option>{(lists.accounts??[]).filter(r=>r.active).map(r=><option value={r.id} key={r.id}>{r.label}</option>)}</select></label><label>Movimiento<select aria-label={'Tipo del movimiento '+(index+1)} disabled={busy} value={entry.side} onChange={e=>setEntries(old=>old.map((v,i)=>i===index?{...v,side:e.target.value}:v))}><option value="debit">Debe</option><option value="credit">Haber</option></select></label><label>{moneyLabel('Importe',fields.currency)}<input aria-label={'Importe del movimiento '+(index+1)} value={entry.amount} required disabled={busy} inputMode="decimal" onChange={e=>setEntries(old=>old.map((v,i)=>i===index?{...v,amount:e.target.value}:v))}/></label><label>Descripción<input aria-label={'Descripción del movimiento '+(index+1)} value={entry.description} maxLength={250} disabled={busy} onChange={e=>setEntries(old=>old.map((v,i)=>i===index?{...v,description:e.target.value}:v))}/></label></div>{entries.length>2?<button type="button" className={s.link} disabled={busy} onClick={()=>setEntries(old=>old.filter((_,i)=>i!==index))}>Quitar movimiento</button>:null}</fieldset>)}{cursors.accounts?<button type="button" className={s.link} onClick={()=>void choices('accounts',cursors.accounts!)}>Cargar más cuentas</button>:null}<button type="button" className={s.secondary} disabled={busy||entries.length>=100} onClick={()=>setEntries(old=>[...old,{account:'',side:'debit',amount:'',description:''}])}>Agregar movimiento</button></section>:null}
 {journal?<section className={s.review}><h3>Revisar asiento</h3><p>{journal.currency} · {minorDisplay(journal.total_debit_minor_units,decimals(journal.currency))}</p>{lineState==='loading'?<p role="status">Cargando movimientos…</p>:lineState==='error'?<button type="button" className={s.link} onClick={()=>void lines(journal.id)}>Volver a cargar movimientos</button>:null}{journalLines.map((line,i)=><div className={s.line} key={i}><span>{line.label}<small>{line.description}</small></span><span>{BigInt(String(line.debit_minor_units))>0?'Debe':'Haber'} · {minorDisplay(BigInt(String(line.debit_minor_units))>0?line.debit_minor_units:line.credit_minor_units,decimals(journal.currency))}</span></div>)}{lineCursor?<button type="button" className={s.link} disabled={lineState==='loading'} onClick={()=>void lines(journal.id,lineCursor!)}>Cargar siguientes movimientos</button>:null}</section>:null}
 {settlement?<p className={s.hint}>Importe de la liquidación: {settlement.currency} {minorDisplay(settlement.expected_minor_units,decimals(settlement.currency))}</p>:null}
 {['accounting_account','accounting_period','accounting_close'].includes(action)?<p className={s.hint}>El plan de cuentas y los períodos son compartidos por las sedes. {action==='accounting_close'?'Este cierre se aplica al período completo.':''}</p>:null}
 <div className={s.actions}><button className={s.primary} disabled={busy||Object.values(loading).some(Boolean)||(action==='fx_conversion'&&!access.fx.enabled)}>{busy?'Confirmando…':pending?'Reintentar la misma operación':labels[action]}</button></div>
 </form>
}
