import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { BackendProblem, captureLead, listAppointmentSlots, listLocations, listModels, requestAppointment } from "./public-client";
beforeEach(() => { process.env.ENTERPRISE_API_BASE_URL = "https://api.example.test/"; process.env.ENTERPRISE_TENANT_CODE = "elite-mobility"; process.env.ENTERPRISE_ORGANIZATION_CODE = "central-store"; });
afterEach(() => { vi.unstubAllGlobals(); });
describe("public backend client", () => {
  it("preserves a Go problem response without accepting it as successful data", async () => {
    vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response(JSON.stringify({ code: "IDEMPOTENCY_CONFLICT", status: 409 }), { status: 409, headers: { "content-type": "application/problem+json; charset=utf-8" } })));
    await expect(captureLead({ sourceCode: "public-web", contact: { email: "a@example.test" }, consentGranted: true }, "lead-request-problem-0001")).rejects.toEqual(new BackendProblem(409, "IDEMPOTENCY_CONFLICT"));
  });
  it("rejects a problem document on a successful HTTP response", async () => {
    vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response(JSON.stringify({ code: "BROKEN" }), { status: 200, headers: { "content-type": "application/problem+json" } })));
    await expect(listModels()).rejects.toEqual(new BackendProblem(502, "INVALID_CONTENT_TYPE"));
  });
  it("uses the fixed tenant path and parses models", async () => { const fetch = vi.fn().mockResolvedValue(new Response(JSON.stringify({ models: [{ id: "m", code: "urban", displayName: "Urban", vehicleClass: "bicycle", specification: {} }] }), { status: 200, headers: { "content-type": "application/json" } })); vi.stubGlobal("fetch", fetch); expect((await listModels())[0]?.id).toBe("m"); expect(String(fetch.mock.calls[0]?.[0])).toBe("https://api.example.test/v1/public/elite-mobility/models"); });
  it("forwards the same idempotency key", async () => { const fetch = vi.fn().mockResolvedValue(new Response(JSON.stringify({ lead_id: "l", status: "accepted" }), { status: 200, headers: { "content-type": "application/json", "idempotency-replayed": "true" } })); vi.stubGlobal("fetch", fetch); const result = await captureLead({ modelId: "m", sourceCode: "public-web", contact: { email: "a@example.test" }, consentGranted: true }, "lead-request-00000001"); expect(result.replayed).toBe(true); expect((fetch.mock.calls[0]?.[1] as RequestInit).headers).toMatchObject({ "idempotency-key": "lead-request-00000001" }); });
  it("uses the same public scope for locations and appointment replay", async () => { const fetch = vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({ items: [{ organization_id: "store", code: "central-store", name: "Central", city: "Cordoba", region: "Cordoba", country: "AR" }] }), { status: 200, headers: { "content-type": "application/json" } })).mockResolvedValueOnce(new Response(JSON.stringify({ id: "appointment", state: "requested", starts_at: "2026-09-01T15:00:00Z" }), { status: 200, headers: { "content-type": "application/json", "idempotency-replayed": "true" } })); vi.stubGlobal("fetch", fetch); expect((await listLocations())[0]?.code).toBe("central-store"); const result = await requestAppointment({ leadId: "lead", modelId: "model", kind: "test-drive", startsAt: "2026-09-01T15:00:00Z" }, "appointment-key-0001"); expect(result.replayed).toBe(true); expect(String(fetch.mock.calls[1]?.[0])).toContain("/v1/public/elite-mobility/central-store/appointments"); });
  it("queries bounded server-owned appointment capacity", async () => { const fetch = vi.fn().mockResolvedValue(new Response(JSON.stringify({ items: [{ id: "slot", organization_id: "store", kind: "service", starts_at: "2026-09-01T15:00:00Z", ends_at: "2026-09-01T16:00:00Z", capacity: 2, booked: 1, state: "open", version: 1 }] }), { status: 200, headers: { "content-type": "application/json" } })); vi.stubGlobal("fetch", fetch); const slots = await listAppointmentSlots("service", "2026-09-01T00:00:00Z", "2026-09-02T00:00:00Z"); expect(slots[0]?.booked).toBe(1); const target = String(fetch.mock.calls[0]?.[0]); expect(target).toContain("/v1/public/elite-mobility/central-store/appointment-slots?"); expect(target).toContain("kind=service"); });
  it("rejects non-json upstream responses", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response("gateway", { status: 502, headers: { "content-type": "text/plain" } }))); await expect(listModels()).rejects.toEqual(new BackendProblem(502, "INVALID_CONTENT_TYPE")); });
  it("rejects credentials in the base URL", async () => { process.env.ENTERPRISE_API_BASE_URL = "https://user:pass@example.test"; await expect(listModels()).rejects.toThrow("unsafe"); });
});
