"use client";
import {useCallback,useEffect,useRef,useState,type FormEvent} from "react";
import {actions,pageSchema,type Action,type Dataset,type Field,type Page,type Row} from "@/platform/warehouse/contract";
import styles from "./warehouse.module.css";
import {warehouseEnglish} from "@/platform/warehouse/messages";

type Access={scope:string;organizations:string[];canWrite:boolean};
type Pending={action:string;organization:string;id?:string;request:string;version?:string;digest:string;key:string};
type Payload=Record<string,string|number|boolean>;
const groups=[['balances','Existencias'],['activities','Movimientos'],['reservations','Reservas'],['transfers','Traslados'],['items','Artículos'],['bins','Ubicaciones'],['policies','Mínimos y capacidad'],['crossdock','Cruce directo'],['uoms','Unidades'],['entries','Historial']] as const;
const names:Record<string,string>={open:'Pendiente',registered:'Completado',cancelled:'Cancelado',released:'Liberado',reservation:'Reservado',consumed:'Consumido',physical:'Existencia física',blocked:'Bloqueado',expired:'Vencido',available:'Disponible',received:'Recibido',shipped:'Despachado','partially-shipped':'Despacho parcial','partially-received':'Recepción parcial',none:'Sin lote',lot:'Por lote',fifo:'Primero en entrar',specific:'Costo específico',receive:'Recepción',ship:'Salida','put-away':'Ubicación',pick:'Preparación',putpick:'Ubicación y preparación',qc:'Control de calidad',fixed:'Fija',normal:'Normal',base:'Base',alternative:'Alternativa',enabled:'Habilitado',disabled:'Deshabilitado',replenishment:'Reposición',purchase:'Compra',manual:'Trabajo interno',breakbulk:'Abrir bultos',gather:'Reunir bultos',transfer:'Traslado'};
const en:Record<string,string>={...warehouseEnglish,'Almacén':'Warehouse','Existencias':'Stock','Movimientos':'Movements','Reservas':'Reservations','Traslados':'Transfers','Artículos':'Items','Ubicaciones':'Bins','Mínimos y capacidad':'Minimums and capacity','Cruce directo':'Cross-docking','Unidades':'Units','Historial':'History','Buscar':'Search','Cargar más':'Load more','Actualizar':'Refresh','Volver':'Back','Nueva operación':'New operation','Confirmar':'Confirm','Cancelar':'Cancel','Consultar resultado':'Check result','Reintentar los mismos datos':'Retry the same request','Operación completada':'Operation completed','Todavía no hay registros.':'No records yet.','Seleccioná un registro':'Select a record','Cargando…':'Loading…','No pudimos cargar los registros.':'We could not load the records.','Resultado todavía sin confirmar.':'The result is not confirmed yet.','Revisá los datos antes de confirmar.':'Review the details before confirming.','Acceso no disponible.':'Access unavailable.','No se pudo guardar la recuperación en este navegador.':'Recovery could not be saved in this browser.'};
function Icon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m3 7 9-4 9 4v10l-9 4-9-4Z M3 7l9 4 9-4 M12 11v10 M8 5l9 4"/></svg>}
async function digest(value:unknown){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(value)));return Array.from(new Uint8Array(bytes),x=>x.toString(16).padStart(2,'0')).join('')}
async function read(dataset:Dataset,organization:string,extra:Record<string,string>={},signal?:AbortSignal):Promise<Page>{const q=new URLSearchParams({dataset,organization_id:organization,limit:'25',...extra});const r=await fetch('/api/enterprise/warehouse?'+q,{cache:'no-store',...(signal?{signal}:{})});if(!r.ok)throw Object.assign(new Error('READ_FAILED'),{status:r.status});return pageSchema.parse(await r.json())}
function initial(action:Action,organization:string,row?:Row):Payload{const value:Payload={};const request=crypto.randomUUID();for(const f of action.fields){if(f.kind==='constant')value[f.key]=f.value!;else if(f.kind==='organization')value[f.key]=organization;else if(f.kind==='request')value[f.key]=request;else if(f.kind==='version'){const v=Number(row?.version);if(Number.isSafeInteger(v)&&v>0)value[f.key]=v}else if(f.kind==='selected'){const v=row?.data[f.key];if(typeof v==='string')value[f.key]=v}else if(f.kind==='boolean')value[f.key]=false;else if(f.kind==='date'&&!f.optional)value[f.key]=new Date().toISOString().slice(0,10);else value[f.key]=''}return value}
function commandPayload(action:Action,form:Payload):Payload{const out:Payload={};for(const field of action.fields){let v=form[field.key];if(v===''&&field.optional)continue;if(field.kind==='date'&&typeof v==='string')v=new Date(v+'T00:00:00Z').toISOString();if(field.kind==='integer')v=Number(v);out[field.key]=v!}return out}
function SelectRecord({field,organization,form,value,onChange,t}:{field:Field;organization:string;form:Payload;value:string;onChange:(v:string)=>void;t:(s:string)=>string}){
 const [options,setOptions]=useState<Row[]>([]),[next,setNext]=useState<string|null>(null),[query,setQuery]=useState(''),[loading,setLoading]=useState(false),[failed,setFailed]=useState(false);const generation=useRef(0);
 const selectedOrganization=field.organizationField?String(form[field.organizationField]??''):organization;
 const itemId=field.source==='items'||field.source==='organizations'||field.source==='bins'||field.source==='orders'?'':String(form.item_id??'');const parent=field.parentField?String(form[field.parentField]??''):'';
 const load=useCallback(async(cursor?:string)=>{const ticket=++generation.current;if(!selectedOrganization||(field.parentField&&!parent)){setOptions([]);setNext(null);return}setLoading(true);setFailed(false);try{const p=await read(field.source as Dataset,selectedOrganization,{...(itemId?{item_id:itemId}:{}),...(parent?{parent_id:parent}:{}),...(query?{search:query}:{}),...(cursor?{cursor}:{})});if(ticket!==generation.current)return;setOptions(old=>cursor?[...old,...p.rows]:p.rows);setNext(p.next_cursor)}catch{if(ticket===generation.current){setFailed(true);setOptions([]);setNext(null)}}finally{if(ticket===generation.current)setLoading(false)}},[field.source,field.parentField,selectedOrganization,itemId,parent,query]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),180);return()=>{clearTimeout(timer);generation.current++}},[load]);
 const optionValue=(r:Row)=>field.value==='id'||!field.value?r.id:String(r.data[String(field.value)]??'');const filtered=options.filter((r,i,all)=>{const val=optionValue(r);if(!val)return false;if(field.key==='lot_id'&&form.bin_id&&r.data.bin_id!==form.bin_id)return false;if(field.key==='receive_bin_id'&&r.data.type!=='receive')return false;if(field.key==='ship_bin_id'&&r.data.type!=='ship')return false;if(field.key==='warehouse_activity_id'&&r.state!=='registered')return false;return true}).filter((r,i,all)=>all.findIndex(x=>optionValue(x)===optionValue(r))===i);
 return <div className={styles.picker}><label>{t(field.label)}<select aria-label={t(field.label)} required={!field.optional} value={value} onChange={e=>onChange(e.target.value)} aria-busy={loading}><option value="">{loading?t('Cargando…'):t('Seleccioná un registro')}</option>{filtered.map(r=><option key={r.id} value={optionValue(r)}>{r.label}</option>)}{value&&!filtered.some(r=>optionValue(r)===value)&&<option value={value}>{t('Selección guardada')}</option>}</select></label><details><summary>{t('Buscar')}</summary><input aria-label={t('Buscar')+' '+t(field.label)} type="search" value={query} onChange={e=>setQuery(e.target.value)}/></details>{next&&<button type="button" onClick={()=>void load(next)} disabled={loading}>{t('Cargar más')}</button>}{failed&&<button type="button" onClick={()=>void load()}>{t('No pudimos cargar los registros.')} {t('Actualizar')}</button>}</div>
}
function displayValue(value:unknown){const s=String(value);return /^\d+\.\d+$/u.test(s)?s.replace(/0+$/u,'').replace(/\.$/u,''):s}
function equivalent(a:unknown,b:unknown){if(a===b)return true;if(typeof a==='string'&&typeof b==='string'&&/^\d+(\.\d+)?$/u.test(a)&&/^\d+(\.\d+)?$/u.test(b)){const norm=(v:string)=>v.includes('.')?v.replace(/0+$/u,'').replace(/\.$/u,''):v;return norm(a)===norm(b)}return false}

export function WarehouseWorkspace({language='es'}:{language?:string}){
 const t=(s:string)=>language==='en'?en[s]??s:s;
 const [access,setAccess]=useState<Access|null>(null),[org,setOrg]=useState(''),[dataset,setDataset]=useState<Dataset>('balances'),[page,setPage]=useState<Page|null>(null),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState<Row|null>(null),[lines,setLines]=useState<Row[]>([]),[orgLabels,setOrgLabels]=useState<Record<string,string>>({}),[action,setAction]=useState<Action|null>(null),[drafts,setDrafts]=useState<Record<string,Payload>>({}),[pending,setPending]=useState<Pending|null>(null),[menu,setMenu]=useState(false),[review,setReview]=useState(false),[reconstructing,setReconstructing]=useState(false);
 const retained=useRef<{body:unknown;serialized:string}|null>(null),generation=useRef(0);const formKey=action?action.id+':'+(selected?.id??'new')+':'+org:'';const form=drafts[formKey]??{};const storageKey=access?'warehouse.pending.'+access.scope:'';
 useEffect(()=>{let alive=true;void fetch('/api/enterprise/warehouse',{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error();const a=await r.json() as Access;if(!/^[a-f0-9]{64}$/u.test(a.scope)||!Array.isArray(a.organizations)||a.organizations.length===0)throw new Error();if(alive){setAccess(a);setOrg(a.organizations[0]!);try{const raw=sessionStorage.getItem('warehouse.pending.'+a.scope);if(raw){const p=JSON.parse(raw) as Pending;if(actions.some(x=>x.id===p.action)&&a.organizations.includes(p.organization)&&/^[a-f0-9]{64}$/u.test(p.digest)){setPending(p);setOrg(p.organization)}}}catch{setError(t('No se pudo guardar la recuperación en este navegador.'))}}}).catch(()=>{if(alive)setError(t('Acceso no disponible.'))});return()=>{alive=false}},[]);
 useEffect(()=>{if(!access)return;let alive=true;void(async()=>{let cursor:string|undefined;const labels:Record<string,string>={};for(let page=0;page<5;page++){const response=await read('organizations',access.organizations[0]!,cursor?{cursor}:{});for(const row of response.rows)labels[row.id]=row.label;if(!response.next_cursor){if(alive)setOrgLabels(labels);return}cursor=response.next_cursor}throw new Error('organization page bound')})().catch(()=>{if(alive)setError('No pudimos cargar los registros.')});return()=>{alive=false}},[access]);
 const load=useCallback(async(cursor?:string)=>{if(!org)return;const ticket=++generation.current;setBusy(true);setError('');try{const p=await read(dataset,org,{...(search?{search}:{}),...(cursor?{cursor}:{})});if(ticket!==generation.current)return;setPage(old=>cursor&&old?{...p,rows:[...old.rows,...p.rows]}:p)}catch(e){if(ticket===generation.current){const status=(e as {status?:number}).status;if(status===401||status===403){setPage(null);setSelected(null);setAction(null);setAccess(a=>a?{...a,canWrite:false}:a)}setError('No pudimos cargar los registros.')}}finally{if(ticket===generation.current)setBusy(false)}},[dataset,org,search]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),160);return()=>{clearTimeout(timer);generation.current++}},[load]);
 useEffect(()=>{setLines([]);if(selected&&dataset==='activities'){const c=new AbortController();void read('activity-lines',org,{parent_id:selected.id},c.signal).then(p=>setLines(p.rows)).catch(()=>{if(!c.signal.aborted)setError('No pudimos cargar los registros.')});return()=>c.abort()}},[selected,dataset,org]);
 function open(a:Action){if(pending)return;setAction(a);setMenu(false);setReview(false);const key=a.id+':'+(selected?.id??'new')+':'+org;setDrafts(old=>old[key]?old:{...old,[key]:initial(a,org,selected??undefined)});setNotice('')}
 function clearPending(){if(storageKey)sessionStorage.removeItem(storageKey);setPending(null);setReconstructing(false);retained.current=null}
 async function send(retry=false){
  if(!action||!access)return;setError('');setNotice('');let body:unknown,serialized:string;
  if(retry){if(!retained.current||!pending||await digest(retained.current.body)!==pending.digest){setError('Volvé a cargar exactamente los mismos datos para reintentar.');return};({body,serialized}=retained.current)}else{body={action:action.id,organization:org,...(action.selection&&selected?{id:selected.id}:{}),payload:commandPayload(action,form)};serialized=JSON.stringify(body);const p:Pending={action:action.id,organization:org,...(selected?{id:selected.id,version:selected.version}:{}),request:String(form.request_id??''),digest:await digest(body),key:formKey};try{sessionStorage.setItem(storageKey,JSON.stringify(p))}catch{setError('No se pudo guardar la recuperación en este navegador.');return};setPending(p);retained.current={body,serialized}}
  setBusy(true);try{const response=await fetch('/api/enterprise/warehouse',{method:'POST',headers:{'content-type':'application/json'},body:serialized});const result=await response.json() as {effect?:string};if(response.ok&&result.effect==='CONFIRMED'){clearPending();setAction(null);setReview(false);setNotice('Operación completada');await load()}else if((result.effect==='NOT_ATTEMPTED'||result.effect==='REJECTED')&&!retry){clearPending();setError('Revisá los datos y los permisos antes de volver a intentar.')}else setError('Resultado todavía sin confirmar.')}catch{setError('Resultado todavía sin confirmar.')}finally{setBusy(false)}
 }
 async function recover(){if(!pending)return;const a=actions.find(x=>x.id===pending.action)!;setBusy(true);setError('');try{
  let confirmed=false;
  if(a.recovery==='reservation-request'){const r=await fetch('/api/enterprise/warehouse?'+new URLSearchParams({reservation_request:pending.request,organization_id:pending.organization}),{cache:'no-store'});if(r.ok){const v=await r.json();confirmed=v.result?.schema==='warehouse-reservation-receipt/v1'&&v.result.request_id===pending.request}}
  else{let ds=a.recovery as Dataset;const params:Record<string,string>={};if(a.id==='transfer-ship'||a.id==='transfer-receive'){ds=a.id==='transfer-ship'?'transfer-shipments':'transfer-receipts';params.parent_id=pending.id!;params.request_id=pending.request}else if(a.requestRecovery)params.request_id=pending.request;else if(a.selection)params.id=pending.id!;const p=await read(ds,pending.organization,params);if(a.requestRecovery||a.id==='transfer-ship'||a.id==='transfer-receive')confirmed=p.rows.length===1&&p.rows[0]?.data.request_id===pending.request;else if(a.terminal)confirmed=p.rows.some(r=>r.id===pending.id&&r.state===a.terminal&&BigInt(r.version)>BigInt(pending.version??'0'));else if(retained.current){const body=retained.current.body as {payload:Payload};confirmed=p.rows.filter(r=>Object.entries(body.payload).every(([k,v])=>k==='version'||equivalent(r.data[k],v))).length===1}}
  if(confirmed){clearPending();setAction(null);setNotice('Operación completada');await load()}else setError('Resultado todavía sin confirmar.');
 }catch{setError('No pudimos cargar los registros.')}finally{setBusy(false)}}
 async function resumeExact(){if(!pending)return;const a=actions.find(x=>x.id===pending.action)!;let row:Row|undefined;if(a.selection&&pending.id){const p=await read(a.selection as Dataset,pending.organization,{id:pending.id});row=p.rows[0];if(!row){setError('No pudimos cargar los registros.');return}row={...row,version:pending.version??row.version};setSelected(row)}setOrg(pending.organization);setAction(a);const key=a.id+':'+(row?.id??'new')+':'+pending.organization;const value=initial(a,pending.organization,row);for(const f of a.fields)if(f.kind==='request')value[f.key]=pending.request;setDrafts(old=>({...old,[key]:value}));setReconstructing(true);setReview(false)}
 async function submit(e:FormEvent){e.preventDefault();if(!review){setReview(true);return}if(pending&&reconstructing&&action){const body={action:action.id,organization:org,...(action.selection&&selected?{id:selected.id}:{}),payload:commandPayload(action,form)};if(await digest(body)!==pending.digest){setError('Los datos no coinciden con la solicitud pendiente.');setReview(false);return}retained.current={body,serialized:JSON.stringify(body)};void send(true);return}void send()}
 const rowActions=selected?actions.filter(a=>a.selection===dataset&&(!a.activityType||selected.data.type===a.activityType)):[];
 const canAct=Boolean(access?.canWrite)&&!pending&&!busy;
 return <section className={styles.root} data-testid="warehouse-workspace"><header className={styles.header}><div className={styles.heading}><Icon/><h1>{t('Almacén')}</h1></div><div className={styles.controls}>{access&&<label className={styles.org}><span className={styles.sr}>{t('Almacén')}</span><select value={org} onChange={e=>{setOrg(e.target.value);setSelected(null);setAction(null);setPage(null)}} disabled={!!pending||Object.keys(orgLabels).length===0}>{access.organizations.map(id=><option key={id} value={id}>{orgLabels[id]??t('Cargando…')}</option>)}</select></label>}<button className={styles.primary} disabled={!canAct} onClick={()=>setMenu(!menu)} aria-expanded={menu}>{t('Nueva operación')}</button></div></header>
  {pending&&<div role="status" className={styles.recovery}><span>{t('Resultado todavía sin confirmar.')}</span><button onClick={()=>void recover()} disabled={busy}>{t('Consultar resultado')}</button>{!retained.current&&<button onClick={()=>void resumeExact().catch(()=>setError('No pudimos cargar los registros.'))} disabled={busy}>{t('Reingresar datos para reintento exacto')}</button>}{retained.current&&<button onClick={()=>void send(true)} disabled={busy}>{t('Reintentar los mismos datos')}</button>}</div>}
  {notice&&<p role="status" className={styles.notice}>{t(notice)}</p>}{error&&<p role="alert" className={styles.error}>{t(error)} <button onClick={()=>void load()} disabled={busy}>{t('Actualizar')}</button></p>}
  {menu&&<div className={styles.menu}>{actions.filter(a=>a.group!=='row'&&a.group!=='config').map(a=><button key={a.id} onClick={()=>open(a)}>{t(a.label)}</button>)}<details className={styles.configMenu}><summary>{t('Configurar almacén')}</summary>{actions.filter(a=>a.group==='config').map(a=><button key={a.id} onClick={()=>open(a)}>{t(a.label)}</button>)}</details></div>}
  <nav aria-label={t('Almacén')} className={styles.tabs}>{groups.slice(0,4).map(([key,label])=><button key={key} aria-current={dataset===key?'page':undefined} onClick={()=>{setDataset(key);setSelected(null);setAction(null);setPage(null);setSearch('')}}>{t(label)}</button>)}<label className={styles.configView}><span className={styles.sr}>{t('Configuración e historial')}</span><select aria-label={t('Configuración e historial')} value={groups.slice(4).some(([key])=>key===dataset)?dataset:''} onChange={e=>{if(e.target.value){setDataset(e.target.value as Dataset);setSelected(null);setAction(null);setPage(null);setSearch('')}}}><option value="">{t('Más vistas')}</option>{groups.slice(4).map(([key,label])=><option key={key} value={key}>{t(label)}</option>)}</select></label></nav>
  <div className={styles.split} data-detail-open={!!selected||!!action}><div className={styles.list}><form onSubmit={e=>{e.preventDefault();void load()}} className={styles.search}><input type="search" aria-label={t('Buscar')} placeholder={t('Buscar')} value={search} onChange={e=>setSearch(e.target.value)}/><button aria-label={t('Actualizar')} disabled={busy}>{t('Actualizar')}</button></form>{busy&&!page&&<p role="status">{t('Cargando…')}</p>}{page?.rows.length===0&&<p className={styles.empty}>{t('Todavía no hay registros.')}</p>}<ul>{page?.rows.map(row=><li key={row.id}><button className={styles.row} onClick={()=>{setSelected(row);setAction(null);setMenu(false)}} aria-current={selected?.id===row.id}><Icon/><span><strong>{row.label}</strong><small>{t(names[row.state]??row.state)}</small></span><span aria-hidden="true">›</span></button></li>)}</ul>{page?.next_cursor&&<button onClick={()=>void load(page.next_cursor!)} disabled={busy}>{t('Cargar más')}</button>}</div>
  <div className={styles.content}>{(selected||action)&&<button className={styles.back} onClick={()=>{setSelected(null);setAction(null);setReview(false)}}>‹ {t('Volver')}</button>}
  {action?<form onSubmit={submit} className={styles.form}><h2>{t(action.label)}</h2>{review&&<p>{t('Revisá los datos antes de confirmar.')}</p>}<fieldset disabled={busy||(!!pending&&!reconstructing)||review}><div className={styles.fields}>{action.fields.filter(f=>!f.hidden).map(field=>{const value=form[field.key];const change=(v:string|boolean)=>{setReview(false);setDrafts(old=>{const next={...old[formKey],[field.key]:v};if(field.key==='item_id')for(const dependent of action.fields)if(['uoms','balances','order-lines'].includes(dependent.source??''))next[dependent.key]='';if(field.key==='bin_id')next.lot_id='';if(field.key==='demand_id')next.demand_line_id='';if(field.key==='to_organization_id')next.receive_bin_id='';return {...old,[formKey]:next}})};if(field.kind==='select')return <SelectRecord key={field.key} field={field} organization={org} form={form} value={String(value??'')} onChange={change} t={t}/>;if(field.kind==='boolean')return <label key={field.key} className={styles.check}><input type="checkbox" checked={value===true} onChange={e=>change(e.target.checked)}/>{t(field.label)}</label>;if(field.kind==='choice')return <label key={field.key}>{t(field.label)}<select aria-label={t(field.label)} required value={String(value??'')} onChange={e=>change(e.target.value)}><option value="">{t('Seleccioná una opción')}</option>{field.choices?.map(c=><option key={c} value={c}>{t(names[c]??c)}</option>)}</select></label>;return <label key={field.key}>{t(field.label)}<input required={!field.optional} maxLength={128} type={field.kind==='date'?'date':field.kind==='integer'?'number':'text'} inputMode={['decimal','cost'].includes(field.kind)?'decimal':undefined} min={field.kind==='integer'?0:undefined} value={String(value??'')} onChange={e=>change(e.target.value)}/></label>})}</div></fieldset><div className={styles.actions}>{review?<><button type="button" onClick={()=>setReview(false)} disabled={busy}>{t('Volver')}</button><button type="submit" className={styles.primary} disabled={!canAct&&!reconstructing||busy}>{t(pending?'Reintentar los mismos datos':'Confirmar')}</button></>:<button type="submit" className={styles.primary} disabled={!canAct&&!reconstructing||busy}>{t('Continuar')}</button>}<button type="button" onClick={()=>setAction(null)} disabled={busy}>{t('Cancelar')}</button></div></form>:
   selected?<article className={styles.detail}><header><h2>{selected.label}</h2><span>{t(names[selected.state]??selected.state)}</span></header><dl>{['quantity','reserved_quantity','unreserved_quantity','shipped_quantity','received_quantity','lot_no','expiration_date','base_uom','min_quantity','max_quantity','cost_amount'].filter(k=>selected.data[k]!==undefined&&selected.data[k]!==null&&selected.data[k]!=='').map(k=><div key={k}><dt>{({quantity:'Cantidad',reserved_quantity:'Reservado',unreserved_quantity:'Sin reservar',shipped_quantity:'Despachado',received_quantity:'Recibido',lot_no:'Lote',expiration_date:'Vencimiento',base_uom:'Unidad',min_quantity:'Mínimo',max_quantity:'Máximo',cost_amount:'Costo'} as Record<string,string>)[k]}</dt><dd title={String(selected.data[k])}>{displayValue(selected.data[k])}</dd></div>)}</dl>{lines.length>0&&<ul className={styles.lines}>{lines.map(line=><li key={line.id}><strong>{line.label}</strong><span>{String(line.data.quantity)} {String(line.data.uom_code)}{line.data.lot_no?' · '+String(line.data.lot_no):''}</span></li>)}</ul>}<details className={styles.reference}><summary>{t('Referencia')}</summary><code>{selected.id}</code>{Boolean(selected.data.source_id)&&<p>{String(selected.data.source_id)}</p>}</details><div className={styles.actions}>{rowActions.map(a=><button key={a.id} onClick={()=>open(a)} disabled={!canAct||(dataset==='activities'&&selected.state!=='open')||(a.id==='release'&&selected.state!=='reservation')}>{t(a.label)}</button>)}</div></article>:<div className={styles.placeholder}><Icon/><p>{t('Seleccioná un registro')}</p></div>}
  </div></div></section>
}
