import{test,expect}from'@playwright/test';
test.use({ locale: 'es-AR' });
import{createHash}from'node:crypto';import{createRequire}from'node:module';import{resolve}from'node:path';import{pathToFileURL}from'node:url';
test('CMS publish read history withdraw with actual role forms',async({page,context},info)=>{
 if(process.env.ELITE_HELP_CMS_BROWSER!=='1')throw new Error('explicit fixture required');const base=process.env.ELITE_BASE_URL;expect(new URL(base).hostname).toBe('127.0.0.1');expect(new URL(base).protocol).toBe('https:');page.setDefaultTimeout(12000);
 const require=createRequire(resolve(process.env.ELITE_WEB_ROOT,'package.json')),{EncryptJWT}=await import(pathToFileURL(require.resolve('jose')).href),identities=JSON.parse(process.env.ELITE_HELP_IDENTITIES);
 async function identity(name){const jwt=await new EncryptJWT(identities[name]).setProtectedHeader({alg:'dir',enc:'A256GCM',typ:'JWT'}).setIssuedAt().setExpirationTime('300s').encrypt(createHash('sha256').update(process.env.AUTH_SESSION_SECRET).digest());await context.clearCookies();await context.addCookies([{name:'__Host-elite_session',value:jwt,url:base+'/',secure:true,httpOnly:true,sameSite:'Lax'}])}
 const errors=[],posts=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST'&&r.url().includes('/api/enterprise/help/cms'))posts.push(r.url())});
 const box=name=>page.getByRole('textbox',{name,exact:true}),button=name=>page.getByRole('button',{name,exact:true}),select=name=>page.getByRole('combobox',{name,exact:true});
 async function click(name){await button(name).click();await expect(page.locator('main [role="status"][aria-live="polite"]')).toContainText('Operación registrada.');await expect(button('Consultar artículo actual')).toBeEnabled()}
 async function consult(id){if(id)await box('Referencia del artículo').fill(id);await button('Consultar artículo actual').click();await expect(page.locator('main [role="status"][aria-live="polite"]')).toContainText('Artículo actual consultado.');await expect(button('Consultar artículo actual')).toBeEnabled()}
 async function drop(action){let done=false;await page.route('**/api/enterprise/help/cms**',async route=>{if(done||route.request().method()!=='POST'||route.request().postDataJSON().action!==action){await route.continue();return}done=true;const response=await route.fetch();expect(response.status()).toBe(200);await route.abort('failed')})}
 async function recover(){await expect(page.locator('main [role="status"][aria-live="polite"]')).toContainText('Resultado sin confirmar');const n=posts.length;await page.unrouteAll();await page.reload();await button('Consultar resultado pendiente').click();await expect(page.locator('main [role="status"][aria-live="polite"]')).toContainText('Resultado recuperado');expect(posts.length).toBe(n)}
 await identity('unprivileged');await page.goto('/help/library');await expect(page.getByText('No tenés permiso para consultar este espacio.',{exact:true})).toBeVisible();
 await identity('editor');await page.goto('/help/library');await box('Título del artículo').fill('Recepción segura');await box('Texto del artículo').fill('Contenido <script>window.CMS_UNSAFE=1</script> literal.');await drop('create');await button('Guardar borrador').click();await recover();const es=await box('Referencia del artículo').inputValue();expect(es).toMatch(/^[a-f0-9-]{36}$/);await expect(button('Publicar artículo')).toBeDisabled();
 await identity('reader');await page.goto('/help/library');await box('Referencia del artículo').fill(es);await button('Consultar artículo actual').click();await expect(page.locator('main [role="status"][aria-live="polite"]')).toContainText('Artículo no disponible');await expect(button('Guardar borrador')).toHaveCount(0);
 await identity('editor');await page.goto('/help/library');await consult(es);await box('Título del artículo').fill('Recepción revisada');await box('Texto del artículo').fill('Respetar la aprobación humana. <script>window.CMS_UNSAFE=1</script>');await click('Guardar revisión');await consult();await click('Publicar artículo');await consult();
 await button('Consultar historial').click();await expect(page.locator('main [role="status"][aria-live="polite"]')).toContainText('Historial consultado');await button('Ver versión 1 · Borrador').click();await expect(page.locator('main [role="status"][aria-live="polite"]')).toContainText('Versión histórica consultada');await expect(button('Guardar revisión')).toBeDisabled();await consult();await expect(button('Guardar revisión')).toBeDisabled();
 await button('Preparar artículo nuevo').click();await select('Idioma del contenido').selectOption('en');await box('Título del artículo').fill('Safe receiving');await box('Texto del artículo').fill('Review the serial and retain evidence.');await click('Guardar borrador');const en=await box('Referencia del artículo').inputValue();await consult();await click('Publicar artículo');
 await identity('reader');await page.goto('/help/library');await box('Buscar en título y texto').fill('APROBACIÓN');await button('Buscar artículos').click();await expect(button('Recepción revisada · Publicado')).toBeVisible();await button('Recepción revisada · Publicado').click();await expect(page.locator('main [role="status"][aria-live="polite"]')).toContainText('Artículo actual consultado');await expect(page.getByText('Respetar la aprobación humana. <script>window.CMS_UNSAFE=1</script>',{exact:true})).toBeVisible();expect(await page.evaluate(()=>window.CMS_UNSAFE)).toBeUndefined();await expect(button('Consultar historial')).toHaveCount(0);
 await select('Idioma del contenido').selectOption('en');await box('Buscar en título y texto').fill('');await button('Buscar artículos').click();await expect(button('Safe receiving · Publicado')).toBeVisible();await expect(button('Recepción revisada · Publicado')).toHaveCount(0);
 await page.screenshot({path:info.outputPath('help-reader-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('help-reader-mobile.png'),fullPage:true});
 await identity('editor');await page.goto('/help/library');await consult(es);await drop('archive');await button('Archivar artículo').click();await recover();await consult();await expect(page.getByText('Estado: Archivado. Versión 4. Idioma es.',{exact:true})).toBeVisible();
 await identity('reader');await page.goto('/help/library');await box('Referencia del artículo').fill(es);await button('Consultar artículo actual').click();await expect(page.locator('main [role="status"][aria-live="polite"]')).toContainText('Artículo no disponible');
 expect((await context.request.get(base+'/api/enterprise/help/cms?'+new URLSearchParams({kind:'article',organization_id:'root',id:es,version:'3'}))).status()).toBe(409);
 await identity('foreign');await page.goto('/help/library');await expect(select('Organización')).toBeVisible();expect(await select('Organización').locator('option[value="root"]').count()).toBe(0);expect((await context.request.get(base+'/api/enterprise/help/cms?'+new URLSearchParams({kind:'article',organization_id:'root',id:en}))).status()).toBe(403);
 expect(posts).toHaveLength(6);expect(errors).toEqual([]);
});
