import{test,expect}from'@playwright/test';
test.use({ locale: 'es-AR' });
import{createHash}from'node:crypto';import{createRequire}from'node:module';import{resolve}from'node:path';import{pathToFileURL}from'node:url';
test('Role metrics from PG preserve exactness scope failures and survey updates',async({page,context},info)=>{
 if(process.env.ELITE_ROLE_METRICS_BROWSER!=='1')throw new Error('explicit fixture required');const base=process.env.ELITE_BASE_URL;expect(new URL(base).hostname).toBe('127.0.0.1');expect(new URL(base).protocol).toBe('https:');page.setDefaultTimeout(12000);
 const require=createRequire(resolve(process.env.ELITE_WEB_ROOT,'package.json')),{EncryptJWT}=await import(pathToFileURL(require.resolve('jose')).href),identities=JSON.parse(process.env.ELITE_METRIC_IDENTITIES);
 async function identity(name){const jwt=await new EncryptJWT(identities[name]).setProtectedHeader({alg:'dir',enc:'A256GCM',typ:'JWT'}).setIssuedAt().setExpirationTime('300s').encrypt(createHash('sha256').update(process.env.AUTH_SESSION_SECRET).digest());await context.clearCookies();await context.addCookies([{name:'__Host-elite_session',value:jwt,url:base+'/',secure:true,httpOnly:true,sameSite:'Lax'}]);await page.goto('/dashboard')}
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const area=()=>page.getByRole('region',{name:'Indicadores operativos'}),select=name=>area().getByRole('combobox',{name,exact:true});
 async function read(kind,id){if(kind)await select('Indicador').selectOption(kind);if(id)await select('Programa o encuesta').selectOption(id);const response=page.waitForResponse(r=>r.url().includes('/api/enterprise/metrics?'));await area().getByRole('button',{name:'Consultar indicador',exact:true}).click();return response}
 await identity('none');await expect(page.getByText('No tenés permisos de indicadores asignados.',{exact:true})).toBeVisible();
 await identity('customer');expect(await select('Indicador').locator('option').evaluateAll(xs=>xs.map(x=>x.value))).toEqual(['own-orders','own-cases','own-appointments']);
 expect((await read()).status()).toBe(200);await expect(area().getByRole('cell',{name:'9007199254745993',exact:true})).toBeVisible();await expect(area().getByRole('cell',{name:'100',exact:true})).toBeVisible();
 const forbidden=await page.evaluate(async()=>{const r=await fetch('/api/enterprise/metrics?kind=orders&organization_id=store');return r.status});expect(forbidden).toBe(403);
 await identity('admin');expect((await read()).status()).toBe(200);await expect(area().getByRole('cell',{name:'300',exact:true})).toBeVisible();await expect(area().getByRole('cell',{name:'9007199254745993',exact:true})).toBeVisible();
 await select('Organización').selectOption('other');await expect(area().getByRole('table')).toHaveCount(0);expect((await read()).status()).toBe(200);await expect(area().getByRole('cell',{name:'300',exact:true})).toBeVisible();
 await select('Organización').selectOption('store');expect((await read('stored-value','reference-gift_card')).status()).toBe(200);await expect(area().getByText('Sin registros para este alcance.',{exact:true})).toBeVisible();
 expect((await read('survey','survey')).status()).toBe(200);await expect(area().getByText('Respuestas: 0',{exact:true})).toBeVisible();await expect(area().getByText('NPS no disponible: no se alcanzó el mínimo configurado.',{exact:true})).toBeVisible();
 for(const [name,score]of[['customer',10],['customer-2',2]]){await identity(name);expect(await page.evaluate(async score=>{const r=await fetch('/api/enterprise/surveys?organizationId=store&surveyId=survey',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({score,consent:true,consent_version:'v1'})});return r.status},score)).toBe(201);await identity('admin');expect((await read('survey','survey')).status()).toBe(200);if(score===10)await expect(area().getByText('NPS no disponible: no se alcanzó el mínimo configurado.',{exact:true})).toBeVisible()}
 await expect(area().getByText('Respuestas: 2',{exact:true})).toBeVisible();await expect(area().getByText('NPS: 0',{exact:true})).toBeVisible();
 await page.route('**/api/enterprise/metrics?**',route=>route.fulfill({status:503,contentType:'application/json',body:'{"code":"METRIC_UNAVAILABLE"}'}));expect((await read()).status()).toBe(503);await expect(area().getByRole('alert')).toBeVisible();await expect(area().getByText('NPS: 0',{exact:true})).toHaveCount(0);await page.unrouteAll();
 expect((await read('orders')).status()).toBe(200);await page.screenshot({path:info.outputPath('metrics-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:info.outputPath('metrics-mobile.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);expect(errors).toEqual([]);
});
