import {test,expect} from '@playwright/test';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
test('role supply order to factory replacement, partial receiving, reinspection and available stock',async({page,context},info)=>{
 if(process.env.ELITE_SUPPLY_ROLE_BROWSER!=='1')throw new Error('explicit fixture required');
 const base=process.env.ELITE_BASE_URL;expect(new URL(base).protocol).toBe('https:');expect(new URL(base).hostname).toBe('127.0.0.1');page.setDefaultTimeout(12000);
 const require=createRequire(resolve(process.env.ELITE_WEB_ROOT,'package.json')),{EncryptJWT}=await import(pathToFileURL(require.resolve('jose')).href),identities=JSON.parse(process.env.ELITE_SUPPLY_IDENTITIES);
 async function identity(name){const jwt=await new EncryptJWT(identities[name]).setProtectedHeader({alg:'dir',enc:'A256GCM',typ:'JWT'}).setIssuedAt().setExpirationTime('300s').encrypt(createHash('sha256').update(process.env.AUTH_SESSION_SECRET).digest());await context.clearCookies();await context.addCookies([{name:'__Host-elite_session',value:jwt,url:base+'/',secure:true,httpOnly:true,sameSite:'Lax'}])}
 const errors=[],posts=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST'&&r.url().includes('/api/enterprise/supply'))posts.push(r.url())});
 async function evidence(suffix='initial'){await page.getByLabel('Archivo de evidencia',{exact:true}).setInputFiles({name:'fixture.txt',mimeType:'text/plain',buffer:Buffer.from('Authorized synthetic evidence '+suffix)});await expect(page.getByText('Evidencia preparada.',{exact:true})).toBeVisible();await page.getByRole('textbox',{name:'Motivo de revisión',exact:true}).fill('Revisión explícita de la evidencia sintética '+suffix)}
 async function open(name,order=''){await identity(name);await page.goto('/supply'+(order?'?order='+encodeURIComponent(order):''));await expect(page.getByRole('heading',{name:'Suministro por serie',exact:true})).toBeVisible();if(order){await page.getByRole('button',{name:'Consultar orden',exact:true}).click();await expect(page.getByRole('status')).toContainText('Orden y versión consultadas')}await evidence(name)}
 async function click(name,within=page){await within.getByRole('button',{name,exact:true}).click();await expect(page.getByRole('status')).toContainText('Operación registrada');await expect(page.getByRole('button',{name:'Actualizar desde primera página',exact:true})).toBeEnabled()}
 function unit(serial){return page.getByRole('article',{name:'Serie '+serial,exact:true})}
 async function drop(kind){let dropped=false;await page.route('**/api/enterprise/supply**',async route=>{const r=route.request();if(dropped||r.method()!=='POST'||r.postDataJSON().kind!==kind){await route.continue();return}dropped=true;const response=await route.fetch();expect(response.status()).toBe(200);await route.abort('failed')})}
 async function recover(){await expect(page.getByRole('status')).toContainText('Resultado sin confirmar');const n=posts.length;await page.unrouteAll();await page.reload();await page.getByRole('button',{name:'Consultar resultado pendiente',exact:true}).click();await expect(page.getByRole('status')).toContainText('Resultado recuperado');expect(posts.length).toBe(n)}
 await identity('unprivileged');await page.goto('/supply');await expect(page.getByText('No tenés permiso para consultar este espacio.',{exact:true})).toBeVisible();
 await identity('reader');expect((await context.request.post(base+'/api/enterprise/supply',{headers:{origin:base,'content-type':'application/json'},data:{}})).status()).toBe(403);
 await open('buyer');
 for(const [name,value]of [['Proveedor','supplier'],['Organización de fábrica','factory'],['Moneda','ARS'],['Importe total en unidades menores','90000'],['Referencia de la demanda','Demanda de dos unidades'],['Variante','variant']])await page.getByRole('textbox',{name,exact:true}).fill(value);
 await page.getByRole('spinbutton',{name:'Cantidad',exact:true}).fill('2');await drop('create');await page.getByRole('button',{name:'Crear orden con cantidades',exact:true}).click();await recover();
 const order=await page.getByRole('textbox',{name:'Referencia de la orden',exact:true}).inputValue();expect(order).toMatch(/^[a-f0-9-]{36}$/);await evidence('buyer-confirm');await click('Enviar a fábrica');
 await open('maker',order);await click('Confirmar orden en fábrica');await click('Iniciar producción');
 async function make(serial){await page.getByRole('textbox',{name:'Número de serie',exact:true}).fill(serial);await click('Registrar serie');await click('Registrar montaje',unit(serial));await click('Solicitar revisión de fábrica',unit(serial));await expect(unit(serial).getByRole('button',{name:'Liberar serie en fábrica',exact:true})).toBeDisabled()}
 await make('ROLE-A');await make('ROLE-B');await open('factory-qa',order);await click('Liberar serie en fábrica',unit('ROLE-A'));await click('Rechazar serie en fábrica',unit('ROLE-B'));
 await open('maker',order);await make('ROLE-C');await open('factory-qa',order);await click('Liberar serie en fábrica',unit('ROLE-C'));
 await open('maker',order);for(const serial of ['ROLE-A','ROLE-C'])await unit(serial).getByRole('checkbox',{name:'Seleccionar '+serial,exact:true}).check();await page.getByRole('textbox',{name:'Referencia del envío',exact:true}).fill('ROLE-ASN');await click('Registrar despacho');
 await open('receiver',order);await unit('ROLE-A').getByRole('checkbox',{name:'Seleccionar ROLE-A',exact:true}).check();await page.getByRole('textbox',{name:'Referencia del envío',exact:true}).fill('ROLE-ASN');await drop('receive');await page.getByRole('button',{name:'Registrar recepción en cuarentena',exact:true}).click();await recover();await evidence('receiver');await expect(unit('ROLE-A')).toContainText('Stock: En cuarentena');await expect(unit('ROLE-A').getByRole('button',{name:'Liberar stock recibido',exact:true})).toBeDisabled();
 await open('receipt-qa',order);await click('Rechazar calidad recibida',unit('ROLE-A'));await expect(unit('ROLE-A')).toContainText('Revisión de recepción: Rechazada');await expect(unit('ROLE-A').getByRole('button',{name:'Liberar stock recibido',exact:true})).toBeDisabled();
 await open('receiver',order);await evidence('new-reinspection');await click('Solicitar reinspección',unit('ROLE-A'));await expect(unit('ROLE-A')).toContainText('Revisión de recepción: Pendiente');
 await open('receipt-qa',order);await click('Liberar stock recibido',unit('ROLE-A'));await expect(unit('ROLE-A')).toContainText('Stock: Disponible');
 await open('receiver',order);await unit('ROLE-C').getByRole('checkbox',{name:'Seleccionar ROLE-C',exact:true}).check();await page.getByRole('textbox',{name:'Referencia del envío',exact:true}).fill('ROLE-ASN');await click('Registrar recepción en cuarentena');
 await open('receipt-qa',order);await click('Liberar stock recibido',unit('ROLE-C'));await expect(unit('ROLE-A')).toContainText('Stock: Disponible');await expect(unit('ROLE-C')).toContainText('Stock: Disponible');await expect(page.getByText('Recibida',{exact:true})).toBeVisible();
 await page.screenshot({path:info.outputPath('supply-role-available-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('supply-role-mobile.png'),fullPage:true});
 await identity('foreign');expect((await context.request.get(base+'/api/enterprise/supply?'+new URLSearchParams({organization_id:'foreign',purchase_order_id:order,surface:'franchise'}))).status()).toBe(409);
 expect(posts).toHaveLength(23);expect(errors).toEqual([]);
});
