<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>all</NuGetAuditMode>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../generated/Elite.Arca.Wsfe.Generated.csproj" />
    <ProjectReference Include="../../../../credentials/src/Elite.Arca.Credentials/Elite.Arca.Credentials.csproj" />
  </ItemGroup>
</Project>
