"use client";
import{useEffect,useRef,useState}from"react";
import{usePrivateI18n}from"@/platform/i18n/private-provider";
import{returnOutcome,returnStageLabel,formatReturnMoney,type ReturnOutcome}from"@/platform/returns/outcome";
import styles from"./return-outcome-panel.module.css";
export function ReturnOutcomePanel({organization,authorizationId,scope}:{organization:string;authorizationId:string;scope:string}){
 const{locale}=usePrivateI18n(),en=locale.language==="en";
 const[value,setValue]=useState<ReturnOutcome|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");const request=useRef<AbortController|null>(null),sequence=useRef(0);
 useEffect(()=>{sequence.current++;request.current?.abort();setValue(null);setError("");setLoading(false);return()=>{sequence.current++;request.current?.abort()}},[organization,authorizationId,scope]);
 async function refresh(){request.current?.abort();const controller=new AbortController();request.current=controller;const current=++sequence.current;setLoading(true);setError("");
  try{const response=await fetch("/api/enterprise/franchise/return-outcome?"+new URLSearchParams({organizationId:organization,authorizationId}),{cache:"no-store",signal:controller.signal});if(!response.ok)throw new Error(response.status===403?"denied":"unavailable");const result=returnOutcome.safeParse(await response.json());if(!result.success||result.data.authorization_id!==authorizationId||result.data.organization_id!==organization)throw new Error("unconfirmed");if(current===sequence.current)setValue(result.data)}catch(e){if(current===sequence.current&&!controller.signal.aborted){setValue(null);setError(e instanceof Error&&e.message==="denied"?(en?"You cannot view this return.":"No tenés permiso para ver esta devolución."):(en?"The result could not be confirmed. Try again.":"No pudimos confirmar el resultado. Reintentá."))}}finally{if(current===sequence.current)setLoading(false)}
 }
 const labels:Record<ReturnOutcome["stages"][number]["kind"],[string,string]>={inventory:["Inventario","Inventory"],refund:["Reintegro","Refund"],exchange:["Cambio","Replacement"],accounting:["Contabilidad","Accounting"],fiscal:["Comprobante fiscal","Tax document"]};
 return <details className={styles.panel} onToggle={e=>{if(e.currentTarget.open&&!value&&!loading&&!error)void refresh()}}><summary>{en?"Track resolution":"Seguir resolución"}</summary><div className={styles.content} aria-busy={loading}>
 <div className={styles.top}><h4>{en?"Saved results":"Resultados registrados"}</h4><button type="button" onClick={()=>void refresh()} disabled={loading}>{loading?(en?"Checking…":"Consultando…"):(en?"Refresh":"Actualizar")}</button></div>
 {loading?<p role="status">{en?"Checking saved results…":"Consultando los resultados…"}</p>:null}{error?<p role="alert">{error}</p>:null}
 {value&&!loading?<><ul className={styles.stages}>{value.stages.map(stage=><li key={stage.request_id}><span className={styles.mark} data-complete={stage.status==="succeeded"} aria-hidden="true">{stage.status==="succeeded"?<svg viewBox="0 0 20 20" fill="none" stroke="currentColor"><path d="m4 10 4 4 8-9"/></svg>:<span/>}</span><div><strong>{labels[stage.kind][en?1:0]}</strong><p>{returnStageLabel(stage,en)}</p>{stage.owner?.amount_minor_units&&stage.kind!=="exchange"?<p>{formatReturnMoney(stage.owner.amount_minor_units,stage.owner.currency,locale.locale)}</p>:null}{stage.owner&&stage.status!=="succeeded"&&stage.kind!=="exchange"?<p>{(en?"Provider / ledger: ":"Proveedor / registro: ")+(en?({prepared:"prepared",pending:"pending",requires_action:"action needed",blocked:"blocked",failed:"failed",canceled:"canceled",succeeded:"confirmed",posted:"posted",queued:"queued",authorizing:"authorizing",reconcile_required:"reconciliation needed",authorized:"authorized",rejected:"rejected"} as Record<string,string>)[stage.owner.state]:({prepared:"preparado",pending:"pendiente",requires_action:"requiere acción",blocked:"bloqueado",failed:"fallido",canceled:"cancelado",succeeded:"confirmado",posted:"registrado",queued:"en cola",authorizing:"en autorización",reconcile_required:"requiere conciliación",authorized:"autorizado",rejected:"rechazado"} as Record<string,string>)[stage.owner.state])}</p>:null}{stage.kind==="exchange"&&stage.owner?<p>{stage.owner.handover_state==="accepted"?(en?"Delivery accepted":"Entrega aceptada"):stage.owner.handover_state==="rejected"?(en?"Delivery was rejected":"La entrega fue rechazada"):(en?"Delivery is still pending":"La entrega sigue pendiente")}</p>:null}{stage.owner?.reference?<details><summary>{en?"View receipt":"Ver comprobante"}</summary><code>{stage.owner.reference}</code>{stage.result_sha256?<p><small>SHA-256: {stage.result_sha256}</small></p>:null}</details>:null}{stage.error_code?<details><summary>{en?"Review detail":"Detalle de revisión"}</summary><code>{stage.error_code}</code></details>:null}</div></li>)}</ul>{!value.stages.length?<p>{en?"This return is awaiting an operational decision.":"Esta devolución espera una decisión operativa."}</p>:null}<small>{en?"Checked":"Consultado"}: <time dateTime={value.observed_at}>{new Intl.DateTimeFormat(locale.locale,{dateStyle:"short",timeStyle:"short",timeZone:locale.timeZone}).format(new Date(value.observed_at))}</time></small></>:null}
 </div></details>
}
