package domainbind

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"elite.local/enterprise/internal/agenttools"
)

var (
	ErrIdempotencyRequired = errors.New("domainbind: stable command identity required")
	ErrUnauthenticated     = errors.New("domainbind: protected operation requires an access token")
)

// CommandIdentity is supplied by the ingress owner, never by the LLM. The
// external message identity provides the key and timestamp, making retries
// byte-stable even when the customer used a relative date.
type CommandIdentity struct {
	IdempotencyKey string
	OccurredAt     time.Time
}

// Scope is resolved from the authenticated channel/contact mapping. It is not
// inferred from user text or generated by the model.
type Scope struct {
	OrganizationID string
	LeadID         string
}

func (s Scope) validate() error {
	if strings.TrimSpace(s.OrganizationID) == "" || len(s.OrganizationID) > 128 || strings.TrimSpace(s.LeadID) == "" || len(s.LeadID) > 128 {
		return errors.New("domainbind: organization and lead scope required")
	}
	return nil
}

func (c CommandIdentity) validate() error {
	if len(strings.TrimSpace(c.IdempotencyKey)) < 16 || len(c.IdempotencyKey) > 128 || c.OccurredAt.IsZero() {
		return ErrIdempotencyRequired
	}
	return nil
}

// Gateway implements agenttools.Domain over the franchise backend HTTP API.
type Gateway struct {
	cfg    Config
	client *http.Client
}

// NewGateway returns a validated gateway.
func NewGateway(cfg Config) (*Gateway, error) {
	if err := cfg.Validate(); err != nil {
		return nil, err
	}
	return &Gateway{cfg: cfg, client: &http.Client{Timeout: cfg.Timeout}}, nil
}

func (g *Gateway) post(ctx context.Context, path string, body any, commandKey string, protected bool) error {
	raw, err := json.Marshal(body)
	if err != nil {
		return err
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, strings.TrimRight(g.cfg.BaseURL, "/")+path, bytes.NewReader(raw))
	if err != nil {
		return err
	}
	req.Header.Set("content-type", "application/json")
	if commandKey != "" {
		req.Header.Set("Idempotency-Key", commandKey)
	}
	if protected {
		if err := g.authorize(ctx, req); err != nil {
			return err
		}
	}
	return g.do(req)
}

func (g *Gateway) get(ctx context.Context, path string, protected bool) ([]byte, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, strings.TrimRight(g.cfg.BaseURL, "/")+path, nil)
	if err != nil {
		return nil, err
	}
	if protected {
		if err := g.authorize(ctx, req); err != nil {
			return nil, err
		}
	}
	resp, err := g.client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		data, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
		return nil, fmt.Errorf("domainbind: status %d: %s", resp.StatusCode, strings.TrimSpace(string(data)))
	}
	return io.ReadAll(resp.Body)
}

func (g *Gateway) authorize(ctx context.Context, req *http.Request) error {
	if g.cfg.TokenProvider == nil {
		return ErrUnauthenticated
	}
	token, err := g.cfg.TokenProvider.AccessToken(ctx)
	if err != nil {
		return fmt.Errorf("domainbind: access token: %w", err)
	}
	token = strings.TrimSpace(token)
	if token == "" || strings.ContainsAny(token, "\r\n") {
		return ErrUnauthenticated
	}
	req.Header.Set("Authorization", "Bearer "+token)
	return nil
}

func (g *Gateway) validateTenant(tenantID string) error {
	if strings.TrimSpace(tenantID) == "" || tenantID != g.cfg.TenantID {
		return errors.New("domainbind: tenant scope mismatch")
	}
	return nil
}

func (g *Gateway) do(req *http.Request) error {
	resp, err := g.client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		data, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
		return fmt.Errorf("domainbind: status %d: %s", resp.StatusCode, strings.TrimSpace(string(data)))
	}
	return nil
}

// BookAppointment books a public appointment for the resolved kind and time.
func (g *Gateway) BookAppointment(ctx context.Context, tenantID string, in agenttools.AppointmentInput) (string, error) {
	return "", ErrIdempotencyRequired
}

// BookAppointmentCommand books an appointment with ingress-owned replay identity.
func (g *Gateway) BookAppointmentCommand(ctx context.Context, tenantID string, command CommandIdentity, in agenttools.AppointmentInput) (string, error) {
	return g.BookAppointmentFor(ctx, tenantID, Scope{OrganizationID: g.cfg.OrganizationID, LeadID: g.cfg.LeadID}, command, in)
}

// BookAppointmentFor books an appointment for the resolved contact scope.
func (g *Gateway) BookAppointmentFor(ctx context.Context, tenantID string, scope Scope, command CommandIdentity, in agenttools.AppointmentInput) (string, error) {
	if err := g.validateTenant(tenantID); err != nil {
		return "", err
	}
	if err := scope.validate(); err != nil {
		return "", err
	}
	if err := command.validate(); err != nil {
		return "", err
	}
	kind, err := g.cfg.ResolveService(in.Service)
	if err != nil {
		return "", err
	}
	startsAt, err := parseWhen(in.When, command.OccurredAt)
	if err != nil {
		return "", err
	}
	path := fmt.Sprintf("/v1/public/%s/%s/appointments", urlEscape(g.cfg.TenantCode), urlEscape(scope.OrganizationID))
	body := map[string]any{"lead_id": scope.LeadID, "kind": kind, "starts_at": startsAt.UTC().Format(time.RFC3339)}
	if err := g.post(ctx, path, body, command.IdempotencyKey, false); err != nil {
		return "", err
	}
	return fmt.Sprintf("Turno solicitado para %s (%s).", in.Service, startsAt.Format("2006-01-02 15:04")), nil
}

// CreateQuote creates a franchise quote for the resolved variant.
func (g *Gateway) CreateQuote(ctx context.Context, tenantID string, in agenttools.QuoteInput) (string, error) {
	return "", ErrIdempotencyRequired
}

// CreateQuoteCommand creates a quote with ingress-owned replay identity.
func (g *Gateway) CreateQuoteCommand(ctx context.Context, tenantID string, command CommandIdentity, in agenttools.QuoteInput) (string, error) {
	return g.CreateQuoteFor(ctx, tenantID, Scope{OrganizationID: g.cfg.OrganizationID, LeadID: g.cfg.LeadID}, command, in)
}

// CreateQuoteFor creates a quote for the resolved contact scope.
func (g *Gateway) CreateQuoteFor(ctx context.Context, tenantID string, scope Scope, command CommandIdentity, in agenttools.QuoteInput) (string, error) {
	// The selected quotation owner represents one vehicle, not a quantity line.
	if in.Quantity != 1 {
		return "", errors.New("domainbind: reference quote requires exactly one vehicle")
	}
	if err := g.validateTenant(tenantID); err != nil {
		return "", err
	}
	if err := scope.validate(); err != nil {
		return "", err
	}
	if err := command.validate(); err != nil {
		return "", err
	}
	variant, err := g.cfg.ResolveProduct(in.Product)
	if err != nil {
		return "", err
	}
	validUntil := command.OccurredAt.UTC().Add(time.Duration(g.cfg.ValidMinutes) * time.Minute)
	body := map[string]any{
		"organization_id": scope.OrganizationID,
		"lead_id":         scope.LeadID,
		"variant_id":      variant,
		"price_book_id":   g.cfg.PriceBookID,
		"valid_until":     validUntil.Format(time.RFC3339),
	}
	if err := g.post(ctx, "/v1/franchise/quotes", body, command.IdempotencyKey, true); err != nil {
		return "", err
	}
	return fmt.Sprintf("Cotización creada para %s.", in.Product), nil
}

// OrderStatus returns the state of the customer's orders matching orderID.
func (g *Gateway) OrderStatus(ctx context.Context, tenantID, orderID string) (string, error) {
	return g.OrderStatusFor(ctx, tenantID, Scope{OrganizationID: g.cfg.OrganizationID, LeadID: g.cfg.LeadID}, orderID)
}

// OrderStatusFor returns order status within the resolved organization scope.
func (g *Gateway) OrderStatusFor(ctx context.Context, tenantID string, scope Scope, orderID string) (string, error) {
	if err := g.validateTenant(tenantID); err != nil {
		return "", err
	}
	if err := scope.validate(); err != nil {
		return "", err
	}
	path := fmt.Sprintf("/v1/customer/orders?organization_id=%s", urlEscape(scope.OrganizationID))
	data, err := g.get(ctx, path, true)
	if err != nil {
		return "", err
	}
	var page struct {
		Items []struct {
			OrderID string `json:"order_id"`
			State   string `json:"state"`
		} `json:"items"`
	}
	if err := json.Unmarshal(data, &page); err != nil {
		return "", err
	}
	for _, item := range page.Items {
		if item.OrderID == orderID {
			return fmt.Sprintf("Pedido %s: %s.", orderID, item.State), nil
		}
	}
	return "", fmt.Errorf("domainbind: order %q not found", orderID)
}

// RequestReturn rejects the handover for the order, starting the governed
// return flow. It never executes money/inventory directly.
func (g *Gateway) RequestReturn(ctx context.Context, tenantID string, in agenttools.ReturnInput) (string, error) {
	return g.RequestReturnFor(ctx, tenantID, Scope{OrganizationID: g.cfg.OrganizationID, LeadID: g.cfg.LeadID}, in)
}

// RequestReturnFor starts the governed return flow for a resolved scope.
func (g *Gateway) RequestReturnFor(ctx context.Context, tenantID string, scope Scope, in agenttools.ReturnInput) (string, error) {
	if err := g.validateTenant(tenantID); err != nil {
		return "", err
	}
	if err := scope.validate(); err != nil {
		return "", err
	}
	path := fmt.Sprintf("/v1/customer/journey?organization_id=%s", urlEscape(scope.OrganizationID))
	data, err := g.get(ctx, path, true)
	if err != nil {
		return "", err
	}
	var journey struct {
		Handovers []struct {
			ID      string `json:"id"`
			OrderID string `json:"order_id"`
			Version int64  `json:"version"`
		} `json:"handovers"`
	}
	if err := json.Unmarshal(data, &journey); err != nil {
		return "", err
	}
	for _, h := range journey.Handovers {
		if h.OrderID == in.OrderID {
			body := map[string]any{
				"organization_id": scope.OrganizationID,
				"version":         h.Version,
				"reason_code":     "customer-return",
				"details":         in.Reason,
			}
			if err := g.post(ctx, fmt.Sprintf("/v1/customer/handovers/%s/reject", urlEscape(h.ID)), body, "", true); err != nil {
				return "", err
			}
			return "Devolución solicitada; quedará gobernada por aprobación y los workers de devolución.", nil
		}
	}
	return "", fmt.Errorf("domainbind: no entregable para el pedido %q", in.OrderID)
}

func urlEscape(s string) string {
	return url.PathEscape(s)
}

func parseWhen(when string, now time.Time) (time.Time, error) {
	s := strings.TrimSpace(when)
	switch strings.ToLower(s) {
	case "manana", "mañana":
		return now.Add(24 * time.Hour), nil
	case "hoy":
		return now, nil
	}
	t, err := time.Parse(time.RFC3339, s)
	if err != nil {
		return time.Time{}, errors.New("domainbind: when must be an ISO timestamp or hoy/manana")
	}
	if t.Before(now) {
		return time.Time{}, errors.New("domainbind: when must be in the future")
	}
	return t, nil
}
