import {target,evidence} from "../paths.mjs";
import {createRequire}from'node:module';import{resolve}from'node:path';import{createHash}from'node:crypto';import{pathToFileURL}from'node:url';
import{writeFileSync,readFileSync}from'node:fs';
const require=createRequire(process.env.PLAYWRIGHT_TEST_PACKAGE||resolve(target,'microsoft_playwright_browser_gate/package.json'));
const{test,expect}=require('@playwright/test');
const dep=createRequire(resolve(target,'package.json'));
const{EncryptJWT}=await import(pathToFileURL(dep.resolve('jose')).href);
const base='https://127.0.0.1:4313';
const identity={subject:'operator',tenantId:'tenant',organizations:['store'],permissions:['lead:read','lead:assign','lead:update','quote:write','availability:read','availability:manage','handover:manage','appointment:manage'],accessToken:'fixture-access-token'};
async function login(context,delta={}){const token=await new EncryptJWT({...identity,...delta}).setProtectedHeader({alg:'dir',enc:'A256GCM',typ:'JWT'}).setIssuedAt().setExpirationTime('10m').encrypt(createHash('sha256').update(readFileSync(resolve(evidence,'ephemeral-session.key'),'utf8')).digest());await context.clearCookies();await context.addCookies([{name:'__Host-elite_session',value:token,url:base+'/',secure:true,httpOnly:true,sameSite:'Lax'}]);}
test('catalogue shares system, functions, search and all state presentations',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/experience/reference');
 await expect(page.getByRole('heading',{name:'Todo claro. El próximo paso, a mano.'})).toBeVisible();
 await page.getByLabel('Buscar recorrido').fill('entrega');await expect(page.getByText('2 recorridos disponibles')).toBeVisible();await page.getByLabel('Buscar recorrido').fill('xxxx');await expect(page.getByRole('heading',{name:'Todavía no hay resultados'}).first()).toBeVisible();await page.getByLabel('Buscar recorrido').clear();
 for(const state of ['loading','empty','error','forbidden','slow','uncertain']){await page.getByLabel('Estado a revisar').selectOption(state);await expect(page.locator('#states section')).toBeVisible();}
 expect(await page.getByLabel('Función o tema').locator('option').count()).toBe(11);const contract=JSON.parse(readFileSync(resolve(target,'src/platform/experience/business-functions.v403.json'),'utf8')); for(const fn of contract.functions){await page.getByLabel('Función o tema').selectOption(fn.id);await expect(page).toHaveURL(new RegExp('#/functions/'+fn.id));await expect(page.getByText(fn.purpose,{exact:true})).toBeVisible();for(const task of fn.tasks){await expect(page.getByText(task.title,{exact:true})).toHaveCount(1);await expect(page.getByText('Permiso del producto: '+task.product_permission.id,{exact:true})).toHaveCount(fn.tasks.filter(t=>t.product_permission.id===task.product_permission.id).length);}const limits=page.getByText('Autoridades, límites y continuidad',{exact:true});await limits.click();for(const forbidden of fn.prohibited)await expect(page.locator('pre').filter({hasText:forbidden}).last()).toBeVisible();await limits.click();}
 for(const link of await page.locator('.journeyCards a, .journeyTable a').all()){const visible=(await link.textContent()).trim();expect(await link.getAttribute('aria-label')).toContain(visible);}expect(errors).toEqual([]);
});
test('candidate comparisons for concise app, guided delivery and public web',async({page,context})=>{
 await page.goto('/experience');await expect(page.getByRole('heading',{name:'Operaciones',exact:true})).toBeVisible();expect(await page.locator('main').innerText()).not.toMatch(/PROVEN|fixture|biblioteca|owner|Galaxy|SPEC_READY/i);await expect(page).toHaveScreenshot('v03-app-desktop.png',{fullPage:true});
 await page.setViewportSize({width:390,height:844});await expect(page).toHaveScreenshot('v03-app-mobile.png',{fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.keyboard.press('Tab');await expect(page.locator('.skipLink')).toBeFocused();
 await login(context);await page.goto('/experience/operations');await expect(page.getByLabel('Lista de verificación')).toBeVisible();await expect(page).toHaveScreenshot('v03-delivery-mobile.png',{fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.goto('/franchise');await expect(page.getByRole('heading',{name:'Contactos',exact:true})).toBeVisible();await expect(page).toHaveScreenshot('v03-franchise-desktop.png',{fullPage:true});await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Abrir menú',exact:true}).click();await expect(page).toHaveScreenshot('v03-drawer-mobile.png',{fullPage:true});await page.getByRole('button',{name:'Cerrar menú',exact:true}).click();await page.setViewportSize({width:1440,height:1000});
 await context.clearCookies();await page.goto('/models');await expect(page.getByRole('heading',{name:'Urban',exact:true})).toBeVisible();await expect(page).toHaveScreenshot('v03-public-models-desktop.png',{fullPage:true});await page.locator('.modelInquiry>summary').click();await page.getByLabel('Nombre',{exact:true}).focus();await expect(page.getByLabel('Nombre',{exact:true})).toBeFocused();
 await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:720,height:500});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('named choices execute quote, lead and availability via real BFF and deny unlisted selection',async({page,context})=>{
 await login(context);await page.goto('/franchise');await openContact(page);await page.getByRole('button',{name:'Cotización',exact:true}).click();
 await expect(page.getByRole('combobox',{name:'Producto',exact:true})).toBeEnabled();await page.getByRole('combobox',{name:'Producto',exact:true}).selectOption('variant-v403');await page.getByLabel('Lista de precios',{exact:true}).selectOption('retail-v403');
 const quoteForm=page.getByLabel('Producto',{exact:true}).locator('xpath=ancestor::form');await quoteForm.locator('input[type="datetime-local"]').fill('2030-01-01T10:00');await quoteForm.locator('button[type="submit"],button:not([type])').click();await expect(page.getByText('quote-v403',{exact:false})).toBeVisible();
 await page.getByRole('button',{name:'Seguimiento',exact:true}).click();await openContact(page);await page.getByLabel('Responsable',{exact:true}).selectOption('operator');const leadForm=page.getByLabel('Responsable',{exact:true}).locator('xpath=ancestor::form');await leadForm.locator('button').click();
 await page.getByLabel('Trabajo a realizar').selectOption({label:'Disponibilidad'});await page.getByLabel('Persona o recurso',{exact:true}).selectOption('resource-v403');await page.getByLabel('Motivo',{exact:true}).selectOption('maintenance');const availability=page.getByLabel('Persona o recurso',{exact:true}).locator('xpath=ancestor::form');await availability.locator('[name="startsAt"]').fill('2030-01-01T10:00');await availability.locator('[name="endsAt"]').fill('2030-01-01T11:00');await availability.locator('button:not([type])').click();await expect(page.getByText('availability-v403',{exact:false})).toBeVisible();
 const forbidden=await context.request.post(base+'/api/enterprise/franchise/commands',{headers:{origin:base,'content-type':'application/json','idempotency-key':'quote-11111111-1111-4111-8111-111111111111'},data:{action:'create-quote',organizationId:'store',leadId:'lead-v403',variantId:'unlisted',priceBookId:'retail-v403',validUntil:'2030-01-01T10:00:00Z'}});expect(forbidden.status()).toBe(403);
 const stats=await(await context.request.get('http://127.0.0.1:4314/fixture/stats')).json();expect(stats.writes.filter(x=>x.path==='/v1/franchise/quotes')).toHaveLength(1);expect(stats.writes.filter(x=>x.path.endsWith('/assign'))).toHaveLength(1);expect(stats.writes.filter(x=>x.path==='/v1/franchise/availability')).toHaveLength(1);
});
test('guided handover preserves fields, response-loss fence and reload recovery',async({page,context})=>{
 await login(context);await page.goto('/experience/operations');const region=page.getByRole('region',{name:'Presentación de entrega',exact:true});
 await expect(region.getByLabel('Lista de verificación')).toHaveValue('0');expect(await region.locator('input:not([type="hidden"])[name="handoverId"]').count()).toBe(0);expect(await region.locator('textarea[name="responses"]').count()).toBe(0);
 await region.getByLabel('Número de serie observado').fill('SERIAL-V403');await region.getByRole('checkbox',{name:'Revisé el estado del activo'}).check();await region.getByLabel('Expediente de inspección').selectOption({label:'Inspección técnica verificada'});
 await page.route('**/api/enterprise/franchise/commands',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}const response=await route.fetch();expect(response.status()).toBe(200);await route.abort('failed');});
 await region.getByRole('button',{name:'Confirmar revisión',exact:true}).evaluate(b=>{b.click();b.click()});await expect(region.getByRole('status')).toContainText('No pudimos comprobar el resultado');
 await page.unrouteAll();await page.reload();await region.getByRole('button',{name:'Consultar estado',exact:true}).click();await expect(region.getByRole('status')).toContainText('Presentación recuperada');
 const stats=await(await context.request.get('http://127.0.0.1:4314/fixture/stats')).json();expect(stats.writes.filter(x=>x.path.endsWith('/complete-checklist'))).toHaveLength(1);expect(stats.completion.responses).toEqual([{item_id:'serial-observed',response_text:'SERIAL-V403'},{item_id:'asset-condition',response_text:'confirmed'},{item_id:'inspection-proof',response_text:'Evidence verified',evidence_sha256:'a'.repeat(64)}]);
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('server rejects foreign organization and missing grants without trusting function track',async({page,context})=>{await login(context,{organizations:['foreign']});expect((await context.request.get(base+'/api/enterprise/experience-options?organizationId=store&group=variants')).status()).toBe(403);await login(context,{permissions:[]});expect((await context.request.get(base+'/api/enterprise/experience-checklists?organizationId=store')).status()).toBe(403);await page.goto('/experience/operations');await expect(page.getByRole('heading',{name:'Esta operación requiere otro permiso'})).toBeVisible();});
test('unavailable checklist blocks presentation without a write or lost input',async({page,context})=>{await login(context);await page.route('**/api/enterprise/experience-checklists?*',async route=>route.fulfill({status:503,contentType:'application/json',body:'{"code":"UNAVAILABLE"}'}));await page.goto('/experience/operations');await expect(page.getByRole('heading',{name:'No pudimos cargar la información'})).toBeVisible();await page.waitForTimeout(1750);await expect(page.getByRole('heading',{name:'No pudimos cargar la información'})).toBeVisible();await expect(page.getByRole('button',{name:'Confirmar revisión',exact:true})).toBeDisabled();});
test('computed text contrast on catalogue palettes, states and actual guided form',async({page,context})=>{
 const results=[];
 async function measure(label){const rows=await page.evaluate(()=>{
  const color=s=>{const m=s.match(/[\d.]+/g);return m?m.map(Number):[0,0,0,0];};
  const blend=(a,b)=>{const alpha=a.length>3?a[3]:1;return a.slice(0,3).map((v,i)=>v*alpha+b[i]*(1-alpha));};
  const lum=c=>c.map(v=>{const s=v/255;return s<=.04045?s/12.92:((s+.055)/1.055)**2.4;}).reduce((v,c,i)=>v+c*[.2126,.7152,.0722][i],0);
  return [...document.querySelectorAll('body *')].flatMap(el=>{const style=getComputedStyle(el),rect=el.getBoundingClientRect();if(!rect.width||!rect.height||style.visibility==='hidden'||el.closest('[aria-hidden="true"]')||!Array.from(el.childNodes).some(n=>n.nodeType===3&&n.textContent.trim()))return [];
   const chain=[];for(let p=el;p;p=p.parentElement)chain.push(p);let bg=[255,255,255];for(const p of chain.reverse())bg=blend(color(getComputedStyle(p).backgroundColor),bg);
   const fg=blend(color(style.color),bg),a=lum(fg),b=lum(bg);return [{text:el.textContent.trim().slice(0,64),tag:el.tagName,foreground:style.color,background:bg,ratio:(Math.max(a,b)+.05)/(Math.min(a,b)+.05),opacity:style.opacity}];});
 });results.push({label,rows});expect(rows.length).toBeGreaterThan(8);expect(rows.filter(r=>r.ratio<4.5)).toEqual([]);expect(rows.filter(r=>r.opacity!=='1')).toEqual([]);}
 await page.goto('/experience/reference');for(const brand of ['forest','indigo']){await page.getByLabel('Paleta de referencia').selectOption(brand);for(const state of ['empty','error','forbidden','slow','uncertain']){await page.getByLabel('Estado a revisar').selectOption(state);await measure(brand+':'+state);}}
 await login(context);await page.goto('/experience/operations');await expect(page.getByLabel('Lista de verificación')).toBeVisible();await measure('guided-form');writeFileSync(resolve(evidence,'computed-contrast.json'),JSON.stringify({method:'CHROMIUM_COMPUTED_SRGB_TEXT_AND_SOLID_ANCESTOR_BACKGROUNDS',limits:['No image/gradient analysis','No screen-reader acceptance','Native popup rendering is platform-specific'],results},null,2));
});

test('forbidden checklist remains terminal after slow threshold',async({page,context})=>{await login(context);await page.route('**/api/enterprise/experience-checklists?*',route=>route.fulfill({status:403,contentType:'application/json',body:'{"code":"FORBIDDEN"}'}));await page.goto('/experience/operations');await expect(page.getByRole('heading',{name:'Esta operación requiere otro permiso'})).toBeVisible();await page.waitForTimeout(1750);await expect(page.getByRole('heading',{name:'Esta operación requiere otro permiso'})).toBeVisible();await expect(page.getByRole('button',{name:'Confirmar revisión',exact:true})).toBeDisabled();});

for(const flow of ['quote','lead','availability','checklist']) test(flow+' revocation before effect releases marker and permits corrected reload',async({page,context})=>{
 const configPath=resolve(target,'.next/standalone/config/experience-options.json');const original=readFileSync(configPath,'utf8');
 await context.request.post('http://127.0.0.1:4314/fixture/reset');await login(context);await page.goto(flow==='checklist'?'/experience/operations':'/franchise');await page.evaluate(()=>sessionStorage.clear());await page.reload();
 async function prepare(){
  if(flow==='quote'){await openContact(page);await page.getByRole('button',{name:'Cotización',exact:true}).click();await page.getByLabel('Producto',{exact:true}).selectOption('variant-v403');await page.getByLabel('Lista de precios',{exact:true}).selectOption('retail-v403');const form=page.getByLabel('Producto',{exact:true}).locator('xpath=ancestor::form');await form.locator('input[type="datetime-local"]').fill('2030-01-01T10:00');return form.locator('button[type="submit"],button:not([type])');}
  if(flow==='lead'){await openContact(page);await page.getByLabel('Responsable',{exact:true}).selectOption('operator');return page.getByLabel('Responsable',{exact:true}).locator('xpath=ancestor::form').locator('button');}
  if(flow==='availability'){await page.getByLabel('Trabajo a realizar').selectOption({label:'Disponibilidad'});await page.getByLabel('Persona o recurso',{exact:true}).selectOption('resource-v403');await page.getByLabel('Motivo',{exact:true}).selectOption('maintenance');const form=page.getByLabel('Persona o recurso',{exact:true}).locator('xpath=ancestor::form');await form.locator('[name="startsAt"]').fill('2030-01-01T10:00');await form.locator('[name="endsAt"]').fill('2030-01-01T11:00');return form.locator('button:not([type])');}
  const region=page.getByRole('region',{name:'Presentación de entrega',exact:true});await region.getByLabel('Número de serie observado').fill('SERIAL-V403');await region.getByRole('checkbox',{name:'Revisé el estado del activo'}).check();await region.getByLabel('Expediente de inspección').selectOption({label:'Inspección técnica verificada'});return region.getByRole('button',{name:'Confirmar revisión',exact:true});
 }
 try{const submit=await prepare();const revoked=JSON.parse(original);revoked.tenants.tenant.organizations.store[{quote:'variants',lead:'assignees',availability:'resources',checklist:'evidence'}[flow]]=[];writeFileSync(configPath,JSON.stringify(revoked));const response=page.waitForResponse(r=>r.url().endsWith('/api/enterprise/franchise/commands')&&r.request().method()==='POST');await submit.click();const rejected=await response;expect(rejected.status()).toBe(403);expect((await rejected.json()).operation_effect).toBe('NOT_ATTEMPTED');await expect(page.getByText('Las opciones cambiaron antes del envío.',{exact:false})).toBeVisible();expect(await page.evaluate(()=>Object.keys(sessionStorage))).toEqual([]);const stats=await(await context.request.get('http://127.0.0.1:4314/fixture/stats')).json();expect(stats.writes).toHaveLength(0);
 writeFileSync(configPath,original);await page.reload();const next=await prepare();const success=page.waitForResponse(r=>r.url().endsWith('/api/enterprise/franchise/commands')&&r.request().method()==='POST');await next.click();expect((await success).status()).toBe(["quote","availability"].includes(flow)?201:200);const final=await(await context.request.get('http://127.0.0.1:4314/fixture/stats')).json();expect(final.writes).toHaveLength(1);
 }finally{writeFileSync(configPath,original);await context.request.post('http://127.0.0.1:4314/fixture/reset');}
});

test('focus panes preserve unfinished choices and keep one active task',async({page,context})=>{await login(context);await page.goto('/franchise');await page.getByRole('button',{name:'Gestión diaria',exact:true}).click();await openContact(page);await page.getByRole('button',{name:'Cotización',exact:true}).click();await page.getByLabel('Producto',{exact:true}).selectOption('variant-v403');await page.getByLabel('Lista de precios',{exact:true}).selectOption('retail-v403');const form=page.getByLabel('Producto',{exact:true}).locator('xpath=ancestor::form');await form.locator('input[type="datetime-local"]').fill('2030-01-01T10:00');await page.getByLabel('Trabajo a realizar').selectOption({label:'Disponibilidad'});await expect(page.getByLabel('Producto',{exact:true})).toBeHidden();await page.getByLabel('Trabajo a realizar').selectOption({label:'Contactos'});await expect(page.getByLabel('Producto',{exact:true})).toHaveValue('variant-v403');await expect(form.locator('input[type="datetime-local"]')).toHaveValue('2030-01-01T10:00');expect(await page.evaluate(()=>Object.keys(sessionStorage))).toEqual([]);await page.setViewportSize({width:390,height:844});await expect(page.getByLabel('Producto',{exact:true})).toHaveValue('variant-v403');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);});
test('English private interface translates task labels and preserves backend enum values',async({browser})=>{const context=await browser.newContext({locale:'en-US',ignoreHTTPSErrors:true});try{await login(context);const page=await context.newPage();await page.goto(base+'/franchise');await expect(page.getByRole('heading',{name:'Contacts',exact:true})).toBeVisible();await openContact(page);await expect(page.getByLabel('Assignee',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Status',exact:true}).click();const option=page.locator('select[name="target"] option[value="contacted"]');await expect(option).toHaveText('Contacted');await page.getByRole('button',{name:'Quote',exact:true}).click();await expect(page.getByLabel('Product',{exact:true})).toBeEnabled();await expect(page.getByLabel('Price list',{exact:true})).toBeEnabled();await page.goto(base+'/experience/operations');await expect(page.getByRole('heading',{name:'Prepare delivery',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Confirm review',exact:true})).toBeVisible();}finally{await context.close();}});

async function openContact(page){const control=page.locator('.contactWork>summary').first();if(await control.count()&&!(await control.locator('..').evaluate(node=>node.open))){await control.click();return;}const row=page.getByRole('list',{name:'Contactos',exact:true}).getByRole('button').first();if(await row.count())await row.click();}

test('dark console drawer traps focus, restores it and preserves a draft across work areas',async({page,context})=>{
 await login(context);await page.goto('/franchise');await expect(page.getByRole('heading',{name:'Contactos',exact:true})).toBeVisible();await expect(page.getByLabel('Responsable',{exact:true})).toBeHidden();await openContact(page);await page.getByRole('button',{name:'Cotización',exact:true}).click();await page.getByLabel('Producto',{exact:true}).selectOption('variant-v403');const form=page.getByLabel('Producto',{exact:true}).locator('xpath=ancestor::form');await form.locator('input[type="datetime-local"]').fill('2030-01-01T10:00');
 await page.setViewportSize({width:390,height:844});const opener=page.getByRole('button',{name:'Abrir menú',exact:true});await opener.click();const menu=page.getByRole('dialog',{name:'Menú',exact:true});await expect(menu).toBeVisible();await expect(page.getByRole('button',{name:'Cerrar menú',exact:true})).toBeFocused();
 // Native showModal makes the external document inert; click/focus cannot enter the form.
 expect(await form.locator('input[type="datetime-local"]').evaluate(node=>{node.focus();return document.activeElement===node;})).toBe(false);
 await page.keyboard.press('Shift+Tab');expect(await menu.evaluate(node=>node.contains(document.activeElement))).toBe(true);await page.keyboard.press('Tab');await expect(page.getByRole('button',{name:'Cerrar menú',exact:true})).toBeFocused();for(let i=0;i<22;i++){await page.keyboard.press('Tab');expect(await menu.evaluate(node=>node.contains(document.activeElement))).toBe(true);}
 await page.keyboard.press('Escape');await expect(menu).toBeHidden();await expect(opener).toBeFocused();
 await opener.click();await menu.getByRole('button',{name:'Agenda',exact:true}).click();await expect(menu).toBeHidden();await expect(page.getByLabel('Producto',{exact:true})).toBeHidden();await opener.click();await menu.getByRole('button',{name:'Gestión diaria',exact:true}).click();await expect(page.getByLabel('Producto',{exact:true})).toHaveValue('variant-v403');await expect(form.locator('input[type="datetime-local"]')).toHaveValue('2030-01-01T10:00');
 await opener.click();await page.setViewportSize({width:1440,height:1000});await expect(menu).toBeHidden();expect(await page.evaluate(()=>document.querySelectorAll('dialog[open]').length)).toBe(0);await expect(page.getByLabel('Producto',{exact:true})).toBeEnabled();expect(await page.evaluate(()=>Object.keys(sessionStorage))).toEqual([]);
});

test('public catalogue expands an explicit inquiry action without losing consent',async({page})=>{
 await page.goto('/models');await expect(page.getByRole('heading',{name:'Urban',exact:true})).toBeVisible();await expect(page.getByText('Bicicleta',{exact:true})).toBeVisible();const details=page.locator('.modelInquiry');await expect(details.locator('form')).toBeHidden();await details.locator('summary').click();await expect(details.locator('form')).toBeVisible();await expect(details.getByRole('checkbox')).not.toBeChecked();expect(await details.getByRole('checkbox').evaluate(node=>node.required)).toBe(true);
});

test('keyboard reader resolves only the complete authorized order and never submits on Enter',async({page,context})=>{
 await context.request.post('http://127.0.0.1:4314/fixture/reset');await context.request.post('http://127.0.0.1:4314/fixture/unit-mode?mode=complete');await login(context,{permissions:['supply:read','supply:receive']});await page.goto('/supply?order=supplyOrders-v403');await page.getByLabel('Orden de abastecimiento',{exact:true}).selectOption('supplyOrders-v403');await page.getByLabel('Orden de abastecimiento',{exact:true}).locator('xpath=ancestor::form').locator('button').click();const picker=page.getByRole('region',{name:'Buscar una unidad'});await expect(picker).toBeVisible();const code=picker.getByLabel('Código de unidad',{exact:true});await code.fill('001aB');await code.press('Enter');await expect(code).toHaveValue('001aB');await expect(picker.getByRole('button',{name:'Elegir esta unidad'})).toBeVisible();let stats=await(await context.request.get('http://127.0.0.1:4314/fixture/stats')).json();expect(stats.writes).toHaveLength(0);await picker.getByRole('button',{name:'Elegir esta unidad'}).click();await expect(picker.getByRole('button',{name:'Unidad elegida'})).toBeDisabled();await code.press('Enter');await expect(picker.getByRole('button',{name:'Unidad elegida'})).toBeDisabled();expect((await(await context.request.get('http://127.0.0.1:4314/fixture/stats')).json()).writes).toHaveLength(0);
 await code.fill('001ab');await code.press('Enter');await expect(picker.getByRole('status')).toContainText('No hay una unidad coincidente');await expect(picker.getByRole('button',{name:'Elegir esta unidad'})).toHaveCount(0);
 for(const mode of ['partial','ambiguous']){await context.request.post('http://127.0.0.1:4314/fixture/unit-mode?mode='+mode);await page.reload();await page.getByLabel('Orden de abastecimiento',{exact:true}).locator('xpath=ancestor::form').locator('button').click();await code.fill('001aB');await code.press('Enter');await expect(picker.getByRole('status')).toContainText(mode==='partial'?'parcial':'más de una unidad');await expect(picker.getByRole('button',{name:'Elegir esta unidad'})).toHaveCount(0);}
 await context.request.post('http://127.0.0.1:4314/fixture/unit-mode?mode=complete');
});

test('serial reader Enter never confirms a ready delivery and preserves the literal observation',async({page,context})=>{
 await context.request.post('http://127.0.0.1:4314/fixture/reset');await login(context);await page.goto('/experience/operations');const region=page.getByRole('region',{name:'Presentación de entrega',exact:true});const serial=region.getByLabel('Número de serie observado');await serial.fill('001aB');await region.getByRole('checkbox',{name:'Revisé el estado del activo'}).check();await region.getByLabel('Expediente de inspección').selectOption({label:'Inspección técnica verificada'});await expect(region.getByRole('button',{name:'Confirmar revisión',exact:true})).toBeEnabled();await serial.press('Enter');await expect(serial).toHaveValue('001aB');expect((await(await context.request.get('http://127.0.0.1:4314/fixture/stats')).json()).writes).toHaveLength(0);await serial.fill(' 001aB');expect(await serial.evaluate(node=>node.checkValidity())).toBe(false);await serial.fill('001aB');await region.getByRole('button',{name:'Confirmar revisión',exact:true}).click();const stats=await(await context.request.get('http://127.0.0.1:4314/fixture/stats')).json();expect(stats.writes).toHaveLength(1);expect(stats.completion.responses[0].response_text).toBe('001aB');
});
