import {beforeEach,expect,it,vi}from"vitest";
const m=vi.hoisted(()=>({session:vi.fn(),get:vi.fn(),post:vi.fn()}));
vi.mock("@/platform/auth/session",()=>({readSession:m.session,allowed:(s:{permissions:string[]},p:string)=>s.permissions.includes(p)}));
vi.mock("@/platform/auth/oidc-client",()=>({applicationBaseUrl:()=>new URL("https://portal.example.test")}));
vi.mock("@/platform/backend/protected-client",()=>({protectedGet:m.get,protectedPost:m.post}));
import{GET,POST}from"./route";
const h="a".repeat(64),date="2026-09-11T12:00:00Z",key="a03c7850-13ad-4b38-81d0-120000000001";
const context=()=>({organization_id:"store",order_id:"order",order_line_id:"line",payment_attempt_id:"payment",observation_sha256:h,can_prepare:true,release_effect:"COMMIT_COMMERCIAL_RELEASE_RECEIPT",evaluated_at:date});
const handover=()=>({id:"handover",organization_id:"store",order_id:"order",state:"prepared",version:1});
const prepared=()=>({handover:handover(),order_line_id:"line",reservation_id:"reservation",payment_attempt_id:"payment",observation_sha256:h,contract_id:"profile@1",contract_sha256:h,prepared_by:"operator",prepared_at:date});
const receipt=()=>({id:"receipt",organization_id:"store",handover_id:"handover",order_id:"order",payment_attempt_id:"payment",observation_sha256:h,observation_generation:1,handover_version:3,acceptance_sha256:h,checklist_id:"checklist",checklist_version:1,contract_id:"profile@1",contract_sha256:h,effect:"COMMIT_COMMERCIAL_RELEASE_RECEIPT",released_by:"operator",recorded_at:date,valid_until:"2026-09-11T12:05:00Z"});
const session={subject:"operator",tenantId:"tenant",organizations:["store"],permissions:["handover:manage"],accessToken:"never-browser-token"};
const url="https://portal.example.test/api/enterprise/handovers";
const post=(extra:Record<string,unknown>={})=>new Request(url,{method:"POST",headers:{origin:"https://portal.example.test","content-type":"application/json"},body:JSON.stringify({action:"prepare",organizationId:"store",orderId:"order",requestKey:key,...extra})});
beforeEach(()=>{vi.clearAllMocks();m.session.mockResolvedValue(session);m.get.mockResolvedValue(context());m.post.mockResolvedValue(prepared())});
it("derives preparation bindings server-side and passes the original key",async()=>{const r=await POST(post());expect(r.status).toBe(201);expect(m.post).toHaveBeenCalledWith(session,"/v1/franchise/orders/order/handover",{organization_id:"store",order_line_id:"line",payment_attempt_id:"payment",observation_sha256:h},key);expect(await r.json()).toEqual({handover:handover()})});
it.each(["observationSha256","customerId","amountMinor","stockUnitId","paymentAttemptId"])("rejects browser financial or identity field %s",async field=>{expect((await POST(post({[field]:"forged"}))).status).toBe(400);expect(m.get).not.toHaveBeenCalled();expect(m.post).not.toHaveBeenCalled()});
it.each(["unauthenticated","permission","organization","origin"])("rejects %s before any backend effect",async mode=>{let req=post();if(mode==="unauthenticated")m.session.mockResolvedValue(null);if(mode==="permission")m.session.mockResolvedValue({...session,permissions:[]});if(mode==="organization")req=post({organizationId:"foreign"});if(mode==="origin")req=new Request(req,{headers:{origin:"https://evil.test","content-type":"application/json"}});expect([401,403]).toContain((await POST(req)).status);expect(m.get).not.toHaveBeenCalled();expect(m.post).not.toHaveBeenCalled()});
it("hides provider observation details in the browser context",async()=>{m.get.mockResolvedValue({...context(),client_secret:"not-allowed"});const r=await GET(new Request(url+"?kind=context&organizationId=store&orderId=order"));expect(r.status).toBe(200);const raw=await r.text();expect(raw).not.toContain(h);expect(raw).not.toContain("client_secret");expect(raw).not.toContain("never-browser-token")});
it("recovers preparation via GET with exact idempotency header and no POST",async()=>{m.get.mockResolvedValue(prepared());const r=await GET(new Request(url+"?kind=prepare-result&organizationId=store&orderId=order&requestKey="+key));expect(r.status).toBe(200);expect(m.get).toHaveBeenCalledWith(session,"/v1/franchise/orders/order/handover-result",{organization_id:"store"},key);expect(m.post).not.toHaveBeenCalled()});
it("commits only the accepted handover under explicit commercial profile",async()=>{m.get.mockResolvedValue({...context(),can_prepare:false,handover:{...handover(),state:"accepted",version:3}});m.post.mockResolvedValue(receipt());const r=await POST(post({action:"release"}));expect(r.status).toBe(201);expect(m.post).toHaveBeenCalledWith(session,"/v1/franchise/handovers/handover/commercial-release",{organization_id:"store",observation_sha256:h},key);expect(await r.json()).not.toHaveProperty("current")});
it.each(["prepared","readonly"])("rejects release for %s",async kind=>{m.get.mockResolvedValue({...context(),can_prepare:false,handover:{...handover(),state:kind==="prepared"?"prepared":"accepted"},release_effect:kind==="readonly"?"READ_ONLY_ELIGIBILITY":"COMMIT_COMMERCIAL_RELEASE_RECEIPT"});expect((await POST(post({action:"release"}))).status).toBe(409);expect(m.post).not.toHaveBeenCalled()});
it("recovers historical receipt independently of a held/missing current context",async()=>{m.get.mockResolvedValue(receipt());const r=await GET(new Request(url+"?kind=release-result&organizationId=store&orderId=order&handoverId=handover&requestKey="+key));expect(r.status).toBe(200);expect(await r.json()).toEqual({receipt:receipt()});expect(m.get).toHaveBeenCalledTimes(1);expect(m.post).not.toHaveBeenCalled()});
it("shows current=false after callback without deleting historical receipt",async()=>{m.get.mockResolvedValue({receipt:receipt(),evaluated_at:date,current:false});const r=await GET(new Request(url+"?kind=release-current&organizationId=store&orderId=order&handoverId=handover"));expect(r.status).toBe(200);expect((await r.json()).current).toBe(false)});
it.each(["organizationId=store&organizationId=store","organizationId=store&unexpected=value","organizationId=foreign"])("denies invalid recovery query %s",async org=>{expect([400,403]).toContain((await GET(new Request(url+"?kind=context&orderId=order&"+org))).status);expect(m.get).not.toHaveBeenCalled()});
it("rejects receipt mismatch and never retries or exposes backend errors",async()=>{m.post.mockResolvedValue({...prepared(),handover:{...handover(),order_id:"other"}});expect((await POST(post())).status).toBe(502);expect(m.post).toHaveBeenCalledTimes(1);m.get.mockRejectedValue(new Error("PRIVATE_BACKEND_DETAIL"));const r=await GET(new Request(url+"?kind=context&organizationId=store&orderId=order"));expect(r.status).toBe(503);expect(await r.text()).not.toContain("PRIVATE_BACKEND_DETAIL")});

it("uses exactly one stored-value funding reference for preparation",async()=>{
 m.get.mockResolvedValue({...context(),payment_attempt_id:"",funding_receipt_id:"funding_local"});m.post.mockResolvedValue({...prepared(),payment_attempt_id:"",funding_receipt_id:"funding_local"});
 expect((await POST(post())).status).toBe(201);expect(m.post).toHaveBeenCalledWith(session,"/v1/franchise/orders/order/handover",{organization_id:"store",order_line_id:"line",payment_attempt_id:"",funding_receipt_id:"funding_local",observation_sha256:h},key);
});
it.each(["both","neither"])("rejects %s funding sources before preparation",async mode=>{
 m.get.mockResolvedValue({...context(),payment_attempt_id:mode==="both"?"payment":"",...(mode==="both"?{funding_receipt_id:"funding_local"}:{})});expect((await POST(post())).status).toBe(503);expect(m.post).not.toHaveBeenCalled();
});
