// AUTHORED typed projection of the existing governed runtime; no provider SDK.
import { z } from "zod";
const units=z.string().regex(/^(0|[1-9][0-9]{0,18})$/).refine(x=>BigInt(x)<=9223372036854775807n);
export const aiActivityItem=z.object({
 request_id:z.string().regex(/^wa-reply:[0-9a-f]{64}$/),state:z.enum(["completed","handed_off"]),review_state:z.enum(["pending","approved","rejected"]),
 tool:z.enum(["none","book_appointment","create_quote","order_status"]),attempts:z.number().int().min(1).max(100),reserved_tokens:units,input_tokens:units,output_tokens:units,intent_pinned:z.boolean(),occurred_at:z.iso.datetime({offset:true}),updated_at:z.iso.datetime({offset:true})
}).strict().refine(x=>Date.parse(x.updated_at)>=Date.parse(x.occurred_at));
export const aiActivity=z.object({organization_id:z.string().min(1).max(128),observed_at:z.iso.datetime({offset:true}),scope:z.literal("reviewable_proposals"),has_more:z.boolean(),items:aiActivityItem.array().max(50)}).strict().refine(x=>new Set(x.items.map(y=>y.request_id)).size===x.items.length);
export type AIActivity=z.infer<typeof aiActivity>;
export type ActivityState="all"|"pending"|"handed_off";
export function visibleActivity(value:AIActivity,filter:ActivityState){return value.items.filter(x=>filter==="all"||(filter==="pending"?x.review_state==="pending":x.state==="handed_off"))}
export const aiMessages={
 es:{title:"Actividad de IA",subtitle:"Propuestas que llegaron a revisión.",refresh:"Actualizar",loading:"Consultando actividad…",empty:"No hay propuestas registradas.",filteredEmpty:"No hay propuestas en este filtro.",error:"No pudimos consultar la actividad. Volvé a intentar.",denied:"Tu sesión ya no tiene acceso a esta actividad.",all:"Todas",pending:"Por revisar",handoff:"Intervención humana",completed:"Propuesta preparada",approved:"Aprobada",rejected:"Rechazada",details:"Ver detalle",reviewState:"Revisión",review:"Abrir revisión de respuestas",when:"Registrada",attempts:"Intentos",reserved:"Reserva interna",input:"Entrada registrada",output:"Salida registrada",intent:"Operación fijada",yes:"Sí",no:"No",note:"La reserva es un límite interno en tokens; no es una factura ni confirma un envío.",more:"Se muestran las últimas 50 propuestas registradas.",noAutomaticGrant:"Revisar una respuesta no autoriza a enviarla.",tool:{none:"Respuesta",book_appointment:"Agenda",create_quote:"Cotización",order_status:"Consulta de pedido"}},
 en:{title:"AI activity",subtitle:"Proposals that reached review.",refresh:"Refresh",loading:"Loading activity…",empty:"No recorded proposals.",filteredEmpty:"No proposals match this filter.",error:"Activity could not be loaded. Try again.",denied:"Your session no longer has access to this activity.",all:"All",pending:"Awaiting review",handoff:"Human intervention",completed:"Proposal prepared",approved:"Approved",rejected:"Rejected",details:"View details",reviewState:"Review",review:"Open response review",when:"Recorded",attempts:"Attempts",reserved:"Internal reservation",input:"Recorded input",output:"Recorded output",intent:"Operation pinned",yes:"Yes",no:"No",note:"Reservations are internal token limits; they are not invoices or proof of delivery.",more:"Showing the latest 50 recorded proposals.",noAutomaticGrant:"Reviewing a response does not authorize sending it.",tool:{none:"Response",book_appointment:"Schedule",create_quote:"Quote",order_status:"Order inquiry"}}
} as const;
