"use client";
import {useEffect,useRef,useState} from "react";
import {frameFromFile,frameFromVideo,startCamera,selectedCandidate} from "@/platform/capture-vnext/browser-capture.mjs";
import {decodeSchema,resolutionSchema,type CaptureRecord,type DecodedCapture,type CaptureResolution} from "@/platform/capture-vnext/contract";
import s from "./capture.module.css";
const endpoint="/api/enterprise/capture-vnext";
export function CaptureAssist({disabled,language="es",acceptRecord,onResolved}:{disabled:boolean;language?:string;acceptRecord:(record:CaptureRecord)=>boolean;onResolved:(record:CaptureRecord)=>void}){
 const en=language==="en",tx=(es:string,enText:string)=>en?enText:es;
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[camera,setCamera]=useState(false),[decoded,setDecoded]=useState<DecodedCapture|null>(null),[resolution,setResolution]=useState<CaptureResolution|null>(null),[message,setMessage]=useState("");
 const video=useRef<HTMLVideoElement>(null),request=useRef<AbortController|null>(null),stopCamera=useRef<(()=>void)|null>(null),alive=useRef(true),trigger=useRef<HTMLButtonElement>(null);
 function stop(){stopCamera.current?.();stopCamera.current=null;setCamera(false)}
 function cancel(){request.current?.abort();request.current=null;stop();setBusy(false)}
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;request.current?.abort();stopCamera.current?.()}},[]);
 useEffect(()=>{if(disabled){cancel();setResolution(null);setDecoded(null)}},[disabled]);
 function start(){request.current?.abort();const controller=new AbortController();request.current=controller;setBusy(true);setMessage("");setResolution(null);setDecoded(null);return controller}
 async function resolve(text:string,encoding:"QR_REFERENCE"|"SERIAL",controller:AbortController){const response=await fetch(endpoint+"?action=resolve",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({text,encoding,operation:"lookup"}),cache:"no-store",redirect:"error",signal:AbortSignal.any([controller.signal,AbortSignal.timeout(10000)])});if(response.status===404)throw new Error("NOT_FOUND");if(!response.ok)throw new Error("RESOLVE");const result=resolutionSchema.parse(await response.json());if(!controller.signal.aborted){setResolution(result);if(result.status==="REFINE_SELECTION")setMessage(tx("Hay demasiadas coincidencias. Leé el código de una unidad.","Too many matches. Read an individual unit code."));else if(!result.records.some(acceptRecord))setMessage(tx("No coincide con una unidad disponible en este pedido.","No available unit in this order matches this code."))}}
 function failure(error:unknown){setMessage(error instanceof Error&&error.message==="NOT_FOUND"?tx("No encontramos un registro disponible para tu sesión.","No record is available for your session."):tx("No pudimos leerlo. Probá otra imagen o usá el número de serie.","The code could not be read. Try another image or use its serial number."))}
 async function decode(frame:Uint8Array,controller:AbortController){const response=await fetch(endpoint+"?action=decode",{method:"POST",headers:{"content-type":"application/octet-stream"},body:new Uint8Array(frame).buffer,cache:"no-store",redirect:"error",signal:AbortSignal.any([controller.signal,AbortSignal.timeout(20000)])});if(!response.ok)throw new Error("DECODE");const value=decodeSchema.parse(await response.json());if(controller.signal.aborted)return;setDecoded(value);if(value.status==="DECODED"){const candidate=value.candidates[0]!;await resolve(selectedCandidate(value,0),candidate.symbology==="QR_CODE"?"QR_REFERENCE":"SERIAL",controller)}else if(value.status==="NOT_FOUND")setMessage(tx("No encontramos un código. Acercá la cámara o elegí otra imagen.","No code found. Move closer or choose another image."));else if(value.status!=="MULTIPLE")setMessage(tx("No pudimos completar la lectura. Volvé a intentar.","The reading could not be completed. Try again."))}
 async function fileSelected(file:File){if(busy||disabled)return;const controller=start();stop();try{await decode(await frameFromFile(file,{signal:controller.signal}),controller)}catch(error){if(!controller.signal.aborted&&alive.current)failure(error)}finally{if(!controller.signal.aborted&&alive.current)setBusy(false)}}
 async function cameraStart(){if(busy||disabled||!video.current)return;const controller=start();try{const result=await startCamera(video.current,{signal:controller.signal});if(controller.signal.aborted){result.stop();return}stopCamera.current=result.stop;setCamera(true)}catch{if(!controller.signal.aborted&&alive.current)setMessage(tx("La cámara no está disponible. Podés elegir una imagen.","The camera is unavailable. You can choose an image."))}finally{if(!controller.signal.aborted&&alive.current)setBusy(false)}}
 async function cameraRead(){if(busy||disabled||!video.current)return;let frame:Uint8Array;try{frame=frameFromVideo(video.current)}catch{setMessage(tx("Esperá a que la cámara muestre la imagen.","Wait for the camera preview."));return}stop();const controller=start();try{await decode(frame,controller)}catch(error){if(!controller.signal.aborted&&alive.current)failure(error)}finally{if(!controller.signal.aborted&&alive.current)setBusy(false)}}
 async function chooseCode(index:number){if(busy||disabled||!decoded)return;const value=decoded,candidate=value.candidates[index];if(!candidate)return;const controller=start();setDecoded(value);try{await resolve(selectedCandidate(value,index),candidate.symbology==="QR_CODE"?"QR_REFERENCE":"SERIAL",controller)}catch(error){if(!controller.signal.aborted)failure(error)}finally{if(!controller.signal.aborted&&alive.current)setBusy(false)}}
 return <div className={s.root} data-testid="capture-assist"><button type="button" ref={trigger} className={s.trigger} aria-expanded={open} disabled={disabled} onClick={()=>{if(open){cancel();setOpen(false)}else setOpen(true)}}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 8V4h4m8 0h4v4m0 8v4h-4m-8 0H4v-4M8 8h3v3H8zm5 5h3v3h-3zM8 14v2m6-8h2v2"/></svg>{tx("Escanear código","Scan code")}</button>
 {open?<section className={s.panel} aria-label={tx("Leer un código","Read a code")} aria-busy={busy} data-testid="capture-panel"><div className={s.actions}><button type="button" disabled={disabled||busy||camera} onClick={()=>void cameraStart()}>{tx("Usar cámara","Use camera")}</button><label className={s.file}>{tx("Elegir imagen","Choose image")}<input type="file" accept="image/png,image/jpeg,.png,.jpg,.jpeg" disabled={busy||disabled} onChange={event=>{const file=event.target.files?.[0];event.target.value="";if(file)void fileSelected(file)}}/></label></div>
 <video ref={video} hidden={!camera} muted playsInline className={s.video} aria-label={tx("Vista de cámara","Camera view")}/>{camera?<div className={s.actions}><button type="button" disabled={busy||disabled} onClick={()=>void cameraRead()}>{tx("Leer código","Read code")}</button><button type="button" onClick={stop}>{tx("Apagar cámara","Stop camera")}</button></div>:null}
 {busy?<p role="status">{tx("Leyendo código…","Reading code…")}</p>:null}{message?<p role="status">{message}</p>:null}
 {decoded?.status==="MULTIPLE"&&!resolution?<div className={s.choices}><p>{tx("Elegí el código que querés consultar","Choose the code to look up")}</p>{decoded.candidates.map((candidate,index)=><button type="button" key={index} disabled={busy||disabled} onClick={()=>void chooseCode(index)}>{tx("Código","Code")} {index+1} · {candidate.symbology==="QR_CODE"?"QR":tx("Barras","Barcode")}</button>)}</div>:null}
 {resolution?.authorized?<div className={s.choices}>{resolution.records.filter(acceptRecord).map(record=><div className={s.record} key={record.kind+record.id}><div><strong>{record.label}</strong><span>{record.serial}</span></div><button type="button" disabled={busy||disabled||!acceptRecord(record)} onClick={()=>{if(!disabled&&acceptRecord(record)){onResolved(record);cancel();setOpen(false);setResolution(null);trigger.current?.focus()}}}>{tx("Elegir esta unidad","Choose this unit")}</button></div>)}</div>:null}
 </section>:null}</div>
}
