import{z}from"zod";
export const actions=["royalty_policy","royalty_accrue","royalty_open","royalty_close","royalty_reverse","royalty_reconcile","accounting_account","accounting_period","accounting_journal","accounting_post","accounting_reverse","accounting_close","fx_conversion","fx_journal"]as const;
export const actionSchema=z.enum(actions),keySchema=z.string().regex(/^[A-Za-z0-9_-]{16,128}$/u),idSchema=z.string().min(1).max(128),currencySchema=z.string().regex(/^[A-Z]{3}$/u),minorSchema=z.string().regex(/^-?(?:0|[1-9][0-9]*)$/u).refine(v=>BigInt(v)>=-9223372036854775808n&&BigInt(v)<=9223372036854775807n),versionSchema=z.number().int().positive().max(Number.MAX_SAFE_INTEGER),dateSchema=z.string().datetime();
const reason=z.string().min(3).max(500),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/u);
export const payloads={
 royalty_policy:z.object({agreement_id:idSchema,currency:currencySchema,rate_basis_points:z.number().int().min(1).max(10000),valid_from:dateSchema,valid_until:dateSchema.optional()}).strict(),
 royalty_accrue:z.object({payment_attempt_id:idSchema,payment_expected_version:versionSchema,state:z.enum(["captured","refunded"]),occurred_at:dateSchema,source_event_key:keySchema}).strict(),
 royalty_open:z.object({currency:currencySchema,period_start:dateSchema,period_end:dateSchema}).strict(),
 royalty_close:z.object({settlement_id:idSchema,expected_version:versionSchema}).strict(),
 royalty_reverse:z.object({settlement_id:idSchema,expected_version:versionSchema,reason}).strict(),
 royalty_reconcile:z.object({settlement_id:idSchema,external_reference:z.string().min(1).max(250),actual_minor_units:minorSchema}).strict(),
 accounting_account:z.object({code:z.string().regex(/^[A-Z0-9][A-Z0-9._-]{0,31}$/u),name:z.string().min(2).max(120),type:z.enum(["asset","liability","equity","revenue","expense"])}).strict(),
 accounting_period:z.object({starts_on:dateSchema,ends_on:dateSchema}).strict(),
 accounting_journal:z.object({period_id:idSchema,source_type:z.string().regex(/^[A-Z0-9][A-Z0-9._-]{0,31}$/u).refine(v=>v!=="FX_CONVERSION"),source_id:idSchema,currency:currencySchema,posting_date:dateSchema,lines:z.array(z.object({line_no:z.number().int().positive(),account_code:z.string().regex(/^[A-Z0-9][A-Z0-9._-]{0,31}$/u),description:z.string().max(250),debit_minor_units:minorSchema,credit_minor_units:minorSchema}).strict()).min(2).max(100)}).strict(),
 accounting_post:z.object({journal_id:idSchema,expected_version:versionSchema}).strict(),
 accounting_reverse:z.object({journal_id:idSchema,expected_version:versionSchema,reason}).strict(),
 accounting_close:z.object({period_id:idSchema,expected_version:versionSchema}).strict(),
 fx_conversion:z.object({from_currency:currencySchema,to_currency:currencySchema,amount_minor:minorSchema,conversion_date:date}).strict(),
 fx_journal:z.object({conversion_id:idSchema,conversion_request_key:keySchema,period_id:idSchema,debit_account:z.string().min(1).max(32),credit_account:z.string().min(1).max(32),description:z.string().max(250)}).strict()
};
export type FinanceAction=typeof actions[number];export type FinancePayload=Record<string,unknown>;
export const commandSchema=z.object({action:actionSchema,key:keySchema,payload:z.record(z.string(),z.unknown())}).strict().superRefine((v,ctx)=>{if(!payloads[v.action].safeParse(v.payload).success)ctx.addIssue({code:"custom",message:"Invalid action payload"})});
export const accessSchema=z.object({schema:z.literal("finance-workspace-access/v1"),organization_id:idSchema,organization_name:z.string().min(1).max(200),subject:z.string().min(1).max(256),actions:z.array(z.string()).max(30),fx:z.object({enabled:z.boolean(),profile_id:z.string().optional(),source_id:z.string().optional(),local_currency:currencySchema.optional(),date_from:date.optional(),date_through:date.optional(),currencies:z.array(z.object({code:currencySchema,minor_unit_decimals:z.number().int().min(0).max(6),rounding_precision_minor:minorSchema})).max(64),rates:z.array(z.record(z.string(),z.unknown())).max(4096)}).strict()}).strict();
export const pageSchema=z.object({schema:z.literal("finance-workspace-list/v1"),view:z.string().min(1).max(32),organization_id:idSchema,items:z.array(z.record(z.string(),z.unknown())).max(50),next_cursor:z.string().min(1).max(256).nullable()}).strict();
export const resultSchema=z.object({schema:z.literal("finance-ui-result/v1"),outcome:z.enum(['CONFIRMED','REJECTED']),action:actionSchema,key:keySchema,organization_id:idSchema,proof_sha256:z.string().regex(/^[a-f0-9]{64}$/u),result:z.record(z.string(),z.unknown())}).strict();
export const markerSchema=z.object({key:keySchema,action:actionSchema,request_sha256:z.string().regex(/^[a-f0-9]{64}$/u),proof_sha256:z.string().regex(/^[a-f0-9]{64}$/u)}).strict();
export const clientAccessSchema=accessSchema.extend({scope:z.string().regex(/^[a-f0-9]{64}$/u)});
export type FinanceAccess=z.infer<typeof clientAccessSchema>;export type FinancePage=z.infer<typeof pageSchema>;export type FinanceResult=z.infer<typeof resultSchema>;export type FinanceMarker=z.infer<typeof markerSchema>;
export const permission:Record<FinanceAction,string>={royalty_policy:"royalty:policy",royalty_accrue:"royalty:post",royalty_open:"royalty:settle",royalty_close:"royalty:settle",royalty_reverse:"royalty:reverse",royalty_reconcile:"royalty:reconcile",accounting_account:"accounting:manage",accounting_period:"accounting:manage",accounting_journal:"accounting:write",accounting_post:"accounting:post",accounting_reverse:"accounting:reverse",accounting_close:"accounting:close",fx_conversion:"accounting:write",fx_journal:"accounting:write"};
export function stableJSON(value:unknown):string{function sorted(v:unknown):unknown{if(Array.isArray(v))return v.map(sorted);if(v&&typeof v==="object")return Object.fromEntries(Object.entries(v).sort(([a],[b])=>a<b?-1:a>b?1:0).map(([k,x])=>[k,sorted(x)]));return v}return JSON.stringify(sorted(value)).replace(/[<>&\u2028\u2029]/gu,c=>"\\u"+c.charCodeAt(0).toString(16).padStart(4,"0"))}
export async function digest(value:unknown){const bytes=new TextEncoder().encode(stableJSON(value));return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))).map(v=>v.toString(16).padStart(2,"0")).join("")}
export function expectedProjection(action:FinanceAction,payload:FinancePayload,organization:string){if(action==="fx_conversion")return{organization_id:organization,from_currency:payload.from_currency,to_currency:payload.to_currency,amount_minor:payload.amount_minor,conversion_date:payload.conversion_date};if(action==="fx_journal"){const{conversion_request_key,...projection}=payload;return{organization_id:organization,...projection}}return{action,organization_id:organization,payload}}
export function decimalMinor(text:string,decimals:number):string{if(!Number.isInteger(decimals)||decimals<0||decimals>6||!new RegExp(`^-?(?:0|[1-9][0-9]*)(?:\\.[0-9]{1,${Math.max(decimals,1)}})?$`,'u').test(text)||decimals===0&&text.includes('.'))throw new Error("Importe inválido");const negative=text.startsWith('-'),[whole,part='']=text.replace(/^-/,'').split('.');const n=BigInt(whole!)*10n**BigInt(decimals)+BigInt(part.padEnd(decimals,'0')||'0');return minorSchema.parse(((negative?-1n:1n)*n).toString())}
export function minorDisplay(value:unknown,decimals:number|undefined){const raw=String(value??'');if(!minorSchema.safeParse(raw).success)return '—';if(decimals===undefined)return raw+' u. mín.';const negative=raw.startsWith('-'),digits=raw.replace(/^-/,'').padStart(decimals+1,'0');return (negative?'-':'')+(decimals?digits.slice(0,-decimals)+','+digits.slice(-decimals):digits)}

export const journalLineSchema=z.object({line_no:z.number().int().positive(),account_code:idSchema,label:z.string().max(200),description:z.string().max(250),debit_minor_units:minorSchema,credit_minor_units:minorSchema}).strict();
export const balanceRowSchema=z.object({account_code:idSchema,currency:currencySchema,debit_minor_units:minorSchema,credit_minor_units:minorSchema,net_minor_units:minorSchema}).strict();
