// AUTHORED fixed-route BFF; origin/config/session bind scope before any effect.
import {createHash}from"node:crypto";import {z}from"zod";
import{allowed,type PortalSession}from"@/platform/auth/session";
import{boundedDocumentBytes}from"@/platform/documents-vnext/gateway";
import{actionSchema,accessSchema,journalLineSchema,balanceRowSchema,minorSchema,pageSchema,resultSchema,keySchema,commandSchema,permission,stableJSON,expectedProjection,type FinanceAction,type FinancePayload}from"./contract";
export type FinanceConfig={origin:string;tenant:string;organization:string};
export type FinanceTransport=(session:PortalSession,path:string,method:string,body?:string,key?:string)=>Promise<Response>;
const hash=(value:unknown)=>createHash("sha256").update(stableJSON(value)).digest('hex');
const reply=(status:number,value:unknown)=>Response.json(value,{status,headers:{"cache-control":"no-store","x-content-type-options":"nosniff"}});
const rejected=(status:number,code:string)=>reply(status,{code,effect:"NOT_ATTEMPTED"});
export function financeEntry(session:PortalSession){return ['accounting:read','royalty:policy','royalty:post','royalty:settle','royalty:reverse','royalty:reconcile'].some(p=>allowed(session,p))}
const storedReceipt=z.object({schema:z.literal('finance-command-receipt/v1'),outcome:z.enum(['CONFIRMED','REJECTED']),request_key:keySchema,action:actionSchema,organization_id:z.string(),requested_by:z.string(),payload_sha256:z.string().regex(/^[a-f0-9]{64}$/u),result:z.record(z.string(),z.unknown())}).strict();
function result(action:FinanceAction,key:string,raw:any,config:FinanceConfig,session:PortalSession){let proof:string,value:Record<string,unknown>,outcome:"CONFIRMED"|"REJECTED"="CONFIRMED";
 if(action==='fx_conversion'){if(raw.request_key!==key||raw.requested_by!==session.subject||raw.snapshot?.tenant_id!==config.tenant||raw.snapshot?.organization_id!==config.organization||raw.effect!=='CONVERSION_RECEIPT_ONLY'||typeof raw.conversion_id!=='string')throw new Error('FX_BINDING');const c=raw.conversion;if(!c||!minorSchema.safeParse(c.input_minor).success||!minorSchema.safeParse(c.output_minor).success)throw new Error('FX_AMOUNT');proof=hash({organization_id:config.organization,from_currency:c.from_currency,to_currency:c.to_currency,amount_minor:c.input_minor,conversion_date:c.conversion_date});value=raw}
 else if(action==='fx_journal'){const r=raw.receipt;if(!r||r.request_key!==key||r.requested_by!==session.subject||r.organization_id!==config.organization||typeof r.journal_id!=='string'||!minorSchema.safeParse(r.amount_minor).success)throw new Error('JOURNAL_BINDING');proof=hash({organization_id:config.organization,conversion_id:r.conversion_id,period_id:r.period_id,debit_account:r.debit_account,credit_account:r.credit_account,description:r.description});value=raw}
 else{const receipt=storedReceipt.parse(raw);if(receipt.action!==action||receipt.request_key!==key||receipt.organization_id!==config.organization||receipt.requested_by!==session.subject)throw new Error('RECEIPT_BINDING');proof=receipt.payload_sha256;value=receipt.result;outcome=receipt.outcome;if(outcome==="REJECTED"&&(!["INVALID_COMMAND","STATE_CONFLICT"].includes(String(value.code))||value.business_effect!==false))throw new Error("REJECTION_CONTRACT")}
 return resultSchema.parse({schema:'finance-ui-result/v1',outcome,action,key,organization_id:config.organization,proof_sha256:proof,result:value})}
export function createFinanceGateway(deps:{session:()=>Promise<PortalSession|null>;config:()=>FinanceConfig;transport:FinanceTransport}){return async(request:Request)=>{
 const session=await deps.session();if(!session)return rejected(401,'UNAUTHENTICATED');if(!financeEntry(session))return rejected(403,'FORBIDDEN');let config:FinanceConfig;try{config=deps.config()}catch{return rejected(503,'FINANCE_UNAVAILABLE')};if(session.tenantId!==config.tenant||!session.organizations.includes(config.organization))return rejected(403,'FORBIDDEN');
 const url=new URL(request.url);for(const[key,values]of url.searchParams){if(!['view','cursor','limit','result','key','record'].includes(key)||url.searchParams.getAll(key).length!==1)return rejected(400,'INVALID_QUERY')}
 const org=encodeURIComponent(config.organization);let path='',body:string|undefined,key:string|undefined,action:FinanceAction|undefined,expected:string|undefined;
 try{
 if(request.method==='GET'){
  if(!url.search)path='/v1/finance/workspace?organization_id='+org;
  else if(url.searchParams.has('result')){if([...url.searchParams].length!==2)return rejected(400,'INVALID_QUERY');action=actionSchema.parse(url.searchParams.get('result'));key=keySchema.parse(url.searchParams.get('key'));if(!allowed(session,permission[action]))return rejected(403,'FORBIDDEN');path=action==='fx_conversion'?'/v1/accounting/fx/conversions/result?organization_id='+org:action==='fx_journal'?'/v1/accounting/fx/journals/result?organization_id='+org:'/v1/finance/commands/result?organization_id='+org}
  else{if(url.searchParams.has('result')||url.searchParams.has('key'))return rejected(400,'INVALID_QUERY');const view=url.searchParams.get('view'),cursor=url.searchParams.get('cursor'),limit=url.searchParams.get('limit')??'25',record=url.searchParams.get('record');if(!/^(?:[1-9]|[1-4][0-9]|50)$/u.test(limit)||cursor!==null&&(!cursor||cursor.length>256||/[\x00-\x20\x7f]/u.test(cursor)))return rejected(400,'INVALID_QUERY');if(view==='journal_lines'){if(!record||record.length>128)return rejected(400,'INVALID_QUERY');path='/v1/finance/journals/'+encodeURIComponent(record)+'/lines?organization_id='+org+'&limit='+limit+(cursor?'&cursor='+encodeURIComponent(cursor):'')}else if(view==='trial_balance'){if(!record||record.length>128||cursor||url.searchParams.has('limit'))return rejected(400,'INVALID_QUERY');path='/v1/finance/trial-balance?organization_id='+org+'&period_id='+encodeURIComponent(record)}else{if(!['accounts','periods','agreements','policies','settlements','payments','conversions','journals'].includes(view??'')||record)return rejected(400,'INVALID_QUERY');path='/v1/finance/workspace?organization_id='+org+'&view='+view+'&limit='+limit+(cursor?'&cursor='+encodeURIComponent(cursor):'')}}
 }else if(request.method==='POST'){
  if(request.headers.get('origin')!==config.origin)return rejected(403,'CROSS_ORIGIN_REJECTED');if(url.search||request.headers.get('content-type')!=='application/json')return rejected(400,'INVALID_COMMAND');const cmd=commandSchema.parse(JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(await boundedDocumentBytes(request,16384))));action=cmd.action;key=cmd.key;if(!allowed(session,permission[action]))return rejected(403,'FORBIDDEN');expected=hash(expectedProjection(action,cmd.payload,config.organization));path=action==='fx_conversion'?'/v1/accounting/fx/conversions':action==='fx_journal'?'/v1/accounting/fx/journals':'/v1/finance/commands';body=JSON.stringify(action.startsWith('fx_')?{organization_id:config.organization,...cmd.payload}:{action,organization_id:config.organization,payload:cmd.payload});
 }else return rejected(405,'METHOD_NOT_ALLOWED');
 }catch{return rejected(400,'INVALID_COMMAND')}
 try{const response=await deps.transport(session,path,request.method,body,key);if(!response.ok)return reply([400,401,403,404,409,413,429,503].includes(response.status)?response.status:503,{code:response.status===404?'NOT_FOUND':'FINANCE_UNCONFIRMED',effect:'UNCONFIRMED'});const raw=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(await boundedDocumentBytes(response,2097152)));
  if(action&&key){const value=result(action,key,raw,config,session);if(expected&&value.proof_sha256!==expected)throw new Error('PROOF');return reply(200,value)}
  if(!url.search){const value=accessSchema.parse(raw);if(value.organization_id!==config.organization||value.subject!==session.subject||value.actions.some(a=>a==='accounting_read'?!allowed(session,'accounting:read'):!actionSchema.safeParse(a).success||!allowed(session,permission[a as FinanceAction])))throw new Error('ACCESS_BINDING');return reply(200,{...value,scope:hash([config.tenant,config.organization,session.subject])})}
  if(url.searchParams.get('view')==='trial_balance'){const rows=z.array(balanceRowSchema).max(10000).parse(raw);return reply(200,rows)}
  const page=pageSchema.parse(raw);if(page.organization_id!==config.organization||page.view!==url.searchParams.get('view'))throw new Error('PAGE_BINDING');if(page.view==='journal_lines')page.items=page.items.map(row=>journalLineSchema.parse(row));return reply(200,page)
 }catch{return reply(503,{code:'FINANCE_UNCONFIRMED',effect:'UNCONFIRMED'})}
}}
