import {describe,it,expect} from "vitest";
import {createHash} from "node:crypto";
import {parsePortalProfile} from "./portal-profile";
function fixture(){return{schema:"elite.oidc.portal-lifecycle.v1",profile_id:"fixture",revision:1,transport:"TLS",issuer:"https://issuer.invalid",authorization_endpoint:"https://issuer.invalid/authorize",token_endpoint:"https://issuer.invalid/token",jwks_endpoint:"https://issuer.invalid/jwks",revocation_endpoint:"https://issuer.invalid/revoke",end_session_endpoint:"https://issuer.invalid/logout",client_id:"portal",callback_url:"https://portal.invalid/api/auth/callback",post_logout_url:"https://portal.invalid/",bridge_url:"https://backend.invalid",backend_audience:"api",service_client_id:"service",service_subject:"service",service_scopes:["portal-session:manage"],service_audience_parameter:"api",tenant_id:"tenant",organization_ids:["org"],allowed_permissions:["customer:read"],scopes:["openid","offline_access"],maximum_session_seconds:3600,refresh_before_seconds:30,retention_seconds:86400}}
function parse(value:unknown){const bytes=Buffer.from(JSON.stringify(value));return parsePortalProfile(bytes,createHash("sha256").update(bytes).digest("hex"))}
describe("hash-bound portal profile",()=>{
 it("accepts explicit TLS profile and prevents mutation",()=>{const p=parse(fixture());expect(p.tenant_id).toBe("tenant");expect(()=>p.organization_ids.push("foreign")).toThrow()});
 it.each([['transport',{transport:"LOOPBACK_FIXTURE"}],['HTTP',{issuer:"http://issuer.invalid"}],['secret URL',{token_endpoint:"https://user:secret@issuer.invalid/token"}],['wildcard',{allowed_permissions:["*"]}],['duplicate',{organization_ids:["org","org"]}],['missing refresh',{scopes:["openid"]}],['callback origin',{post_logout_url:"https://foreign.invalid/"}],['bridge path',{bridge_url:"https://backend.invalid/path"}],['audience',{service_audience_parameter:"foreign"}],['refresh margin',{refresh_before_seconds:300,maximum_session_seconds:300}],['unknown',{unknown:true}]])("rejects %s",(_name,change)=>{expect(()=>parse({...fixture(),...(change as object)})).toThrow()});
 it("rejects changed bytes and duplicate root names",()=>{const bytes=Buffer.from(JSON.stringify(fixture()));expect(()=>parsePortalProfile(bytes,"0".repeat(64))).toThrow();const duplicate=Buffer.from('{"profile_id":"other",'+bytes.toString().slice(1));expect(()=>parsePortalProfile(duplicate,createHash("sha256").update(duplicate).digest("hex"))).toThrow()});
});
