import {describe,it,expect,vi,afterEach} from "vitest";
import {mkdtempSync,writeFileSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {createHash} from "node:crypto";
import {parsePortalProfile} from "./portal-profile";
import {portalConfiguration} from "./portal-protocol";
let serial=0;
const directories:string[]=[];
afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();for(const directory of directories.splice(0))rmSync(directory,{recursive:true,force:true})});
function configured(){const directory=mkdtempSync(join(tmpdir(),"elite-portal-protocol-fixture-"));directories.push(directory);const secret=join(directory,"synthetic-secret");writeFileSync(secret,"synthetic-fixture-credential");vi.stubEnv("OIDC_PORTAL_CLIENT_SECRET_FILE",secret);const example={"schema":"elite.oidc.portal-lifecycle.v1","profile_id":"reference-portal","revision":1,"transport":"TLS","issuer":"https://issuer.invalid","authorization_endpoint":"https://issuer.invalid/authorize","token_endpoint":"https://issuer.invalid/token","jwks_endpoint":"https://issuer.invalid/jwks","revocation_endpoint":"https://issuer.invalid/revoke","end_session_endpoint":"https://issuer.invalid/logout","client_id":"reference-portal","callback_url":"https://portal.invalid/api/auth/callback","post_logout_url":"https://portal.invalid/","bridge_url":"https://backend.invalid","backend_audience":"reference-api","service_client_id":"reference-portal-maintenance","service_subject":"reference-portal-maintenance","service_scopes":["portal-session:manage"],"service_audience_parameter":"reference-api","tenant_id":"00000000-0000-4000-8000-000000000001","organization_ids":["00000000-0000-4000-8000-000000000002"],"allowed_permissions":["customer:read"],"scopes":["openid","offline_access"],"maximum_session_seconds":3600,"refresh_before_seconds":30,"retention_seconds":86400} as Record<string,unknown>;const bytes=Buffer.from(JSON.stringify({...example,profile_id:"protocol-boundary-"+(++serial)}));return parsePortalProfile(bytes,createHash("sha256").update(bytes).digest("hex"))}
describe("official SDK transport response boundary",()=>{
 it("cancels a streamed discovery body over262144bytes with one request",async()=>{const p=configured();let cancelled=false,calls=0;vi.stubGlobal("fetch",vi.fn(async()=>{calls++;return new Response(new ReadableStream<Uint8Array>({start(controller){controller.enqueue(new Uint8Array(262145))},cancel(){cancelled=true}}),{headers:{"content-type":"application/json"}})}));await expect(portalConfiguration(p)).rejects.toThrow();expect(calls).toBe(1);expect(cancelled).toBe(true)});
 it("passes the bounded valid discovery through the official SDK and refuses metadata endpoint drift",async()=>{const p=configured();const metadata={issuer:p.issuer,authorization_endpoint:p.authorization_endpoint,token_endpoint:p.token_endpoint,jwks_uri:p.jwks_endpoint,revocation_endpoint:p.revocation_endpoint,end_session_endpoint:p.end_session_endpoint,response_types_supported:["code"],subject_types_supported:["public"],id_token_signing_alg_values_supported:["RS256"],token_endpoint_auth_methods_supported:["client_secret_basic"]};const seen:string[]=[];vi.stubGlobal("fetch",vi.fn(async(input:unknown,init:RequestInit)=>{seen.push(String(input));expect(init.redirect).toBe("error");expect(init.signal).toBeDefined();return new Response(JSON.stringify(metadata),{headers:{"content-type":"application/json"}})}));expect((await portalConfiguration(p)).serverMetadata().issuer).toBe(p.issuer);expect(seen).toEqual([p.issuer+"/.well-known/openid-configuration"]);const changed=configured();vi.stubGlobal("fetch",vi.fn(async()=>new Response(JSON.stringify({...metadata,token_endpoint:"https://foreign.invalid/token"}),{headers:{"content-type":"application/json"}})));await expect(portalConfiguration(changed)).rejects.toThrow("OIDC_METADATA_REJECTED")});
});
