import {readFileSync} from "node:fs";
import {it,expect} from "vitest";
import {catalogCanonical,catalogSHA} from "@/platform/catalog/authoring";
import {warrantyCommand,warrantyPayload,warrantyPermission,warrantyPath,warrantyStepReference,warrantyStepMatches} from "./contract";
const cases=JSON.parse(readFileSync("deploy/warranty/role-goldens.json","utf8"))as{name:string;payload:Record<string,unknown>;canonical:string;sha256:string}[];
const role=(a:string)=>["acknowledge","accept","open"].includes(a)?"customer":a==="reconcile"?"factory":"franchise";
it.each(cases)("matches exact Go $name wire without rounding int64",async c=>{const v=warrantyCommand.parse({action:c.name,organization_id:"store",surface:role(c.name),...c.payload});expect(catalogCanonical(warrantyPayload(v))).toBe(c.canonical);expect(await catalogSHA(catalogCanonical(warrantyPayload(v)))).toBe(c.sha256);expect(warrantyPermission(v)).toBeTruthy();expect(warrantyPath(v)).toMatch(/^\/v1\/(franchise|customer|factory)\/warranty\//)});
it("binds open recovery to fixed open command and rejects other identities and versions",async()=>{const c=cases.find(c=>c.name==="open")!,v=warrantyCommand.parse({action:"open",surface:"customer",organization_id:"store",...c.payload}),p=await warrantyStepReference(v);expect(p.command_id).toBe("open");expect(p.version).toBe("1");const r={...p,actor:"customer",state:"opened" as const,payload_sha256:"a".repeat(64),payload:{},recorded_at:"2026-09-12T00:00:00Z",replay:false};expect(warrantyStepMatches(r,p,"customer")).toBe(true);for(const patch of [{actor:"other"},{version:"2"},{request_sha256:"b".repeat(64)},{case_id:"other"}])expect(warrantyStepMatches({...r,...patch},p,"customer")).toBe(false)});
it("does not map staff acceptance or customer work to an authorized write",()=>{for(const[name,surface]of[["accept","franchise"],["work","customer"],["reconcile","customer"]]){const c=cases.find(c=>c.name===name)!,v=warrantyCommand.parse({action:name,surface,organization_id:"store",...c.payload});expect(warrantyPermission(v)).toBeNull()}});
